### PR TITLE
Added bug fix PR language

### PR DESCRIPTION
**Pull request by jessemapel**
## Description

Added language to the Contributing document about labeling bug fix PRs.

## Related Issue

No issue, related to #4615

## Motivation and Context

We need to make sure folks are properly tagging their PRs for the cherry-pick action to work.

## How Has This Been Tested?

No testing, just a markdown document

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Documentation change (update to the documentation; no code change)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] I have read and agree to abide by the [Code of Conduct](https://github.com/USGS-Astrogeology/ISIS3/blob/dev/Code-Of-Conduct.md)
- [x] I have read the [**CONTRIBUTING**](https://github.com/USGS-Astrogeology/ISIS3/blob/dev/CONTRIBUTING.md) document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [x] I have added myself to the [.zenodo.json](https://github.com/USGS-Astrogeology/ISIS3/blob/dev/.zenodo.json) document.
- [ ] I have added any user impacting changes to the [CHANGELOG.md](https://github.com/USGS-Astrogeology/ISIS3/blob/dev/CHANGELOG.md) document.

## Licensing
This project is mostly composed of free and unencumbered software released into the public domain, and we are unlikely to accept contributions that are not also released into the public domain. Somewhere near the top of each file should have these words:

> This work is free and unencumbered software released into the public domain. In jurisdictions that recognize copyright laws, the author or authors of this software dedicate any and all copyright interest in the software to the public domain.

- [x] I dedicate any and all copyright interest in this software to the public domain. I make this dedication for the benefit of the public at large and to the detriment of my heirs and successors. I intend this dedication to be an overt act of relinquishment in perpetuity of all present and future rights to this software under copyright law.

### CODE REVIEW

**Comment by jessemapel** [comment]
Should I add something to our PR checklist? Maybe a note on the part about what type of PR is this?

Part of me just feels like we need to do a wholesale rewrite of the checklist.

**Review by AustinSanders — APPROVED** [review]

**Comment by AustinSanders** [comment]
@jessemapel I considered adding something to the PR checklist as well, but I wasn't sure where/how it fit.  It might be beneficial to add it, especially while we're trying to get everyone used to the new automation tool.

**Comment by acpaquette** [comment]
@jessemapel I would be nice if you can check the bugfix box, which would add the tag but I don't know if that's even possible. We should probably turn the types of changes into tags rather than just little check boxes

**Comment by jessemapel** [comment]
This is just a documentation change, not a bug fix. It doesn't need to be back-ported.

**Review by acpaquette — APPROVED** [review]

**Pull request merged**
