### PR TITLE
Bundleout Reformat 

### LINKED ISSUE #3227: The jigsaw bundleout.txt file needs to be cleaned up
**Description**  
At present, some columns of data do not have headers describing the column values, or unit descriptions such as km/s.

**Example**  
Currently:  
IMAGE MEASURES SUMMARY
==========================

input/Sub4-AS15-M-0583_msk.cub     131 of   131  1.478  2.742  2.202
input/Sub4-AS15-M-0584_msk.cub     205 of   205  1.323  1.241  1.282
input/Sub4-AS15-M-0585_msk.cub     219 of   219  1.055  1.250  1.156
input/Sub4-AS15-M-0586_msk.cub     229 of   229  1.350  1.354  1.352
input/Sub4-AS15-M-0587_msk.cub     166 of   166  1.026  1.168  1.099
input/Sub4-AS15-M-1423.cub       9 of     9  1.482  1.801  1.649
input/Sub4-AS15-M-1537.cub      10 of    10 14.959  8.857 12.293

With the change:

IMAGE MEASURES SUMMARY
==========================
           Image Name                                 Images      RMS1 RMS2 RMS3 
                                                                Accepted      
input/Sub4-AS15-M-0583_msk.cub     131 of   131  1.478  2.742  2.202
input/Sub4-AS15-M-0584_msk.cub     205 of   205  1.323  1.241  1.282
input/Sub4-AS15-M-0585_msk.cub     219 of   219  1.055  1.250  1.156
input/Sub4-AS15-M-0586_msk.cub     229 of   229  1.350  1.354  1.352
input/Sub4-AS15-M-0587_msk.cub     166 of   166  1.026  1.168  1.099
input/Sub4-AS15-M-1423.cub       9 of     9  1.482  1.801  1.649
input/Sub4-AS15-M-1537.cub      10 of    10 14.959  8.857 12.293

Stretch:  Find a way to output this file in a format which would allow it to be easily
imported into a pandas dataframe or into R so that advanced statistical analysis can be
performed on it.

### PR DESCRIPTION
**Pull request by acpaquette**
Reformat to the bundleout.txt file produced by jigsaw. 

## Description
General updates and changes to the format of the bundleout.txt to make things easier to understand.

## Related Issue
Closes #3227

## Motivation and Context
This change was needed to make the bundleout.txt file human readable and standardized between viewers. Mainly removes the tabs that were being used to format the text output.

## How Has This Been Tested?
This has been tested through the BundleUtilities unit test.

## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation change (update to the documentation; no code change)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [X] I have read and agree to abide by the [Code of Conduct](https://usgs-astrogeology.github.io/code/)
- [X] I have read the [**CONTRIBUTING**](https://github.com/USGS-Astrogeology/ISIS3/blob/dev/CONTRIBUTING.md) document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [X] All new and existing tests passed.

## Licensing
This project is mostly composed of free and unencumbered software released into the public domain, and we are unlikely to accept contributions that are not also released into the public domain. Somewhere near the top of each file should have these words:

> This work is free and unencumbered software released into the public domain. In jurisdictions that recognize copyright laws, the author or authors of this software dedicate any and all copyright interest in the software to the public domain.

- [X] I dedicate any and all copyright interest in this software to the public domain. I make this dedication for the benefit of the public at large and to the detriment of my heirs and successors. I intend this dedication to be an overt act of relinquishment in perpetuity of all present and future rights to this software under copyright law.

### CODE REVIEW

**Comment by jlaura** [comment]
@acpaquette Could you post an example of the output from this so that @lwellerastro can take a look at what the output looks like?

**Comment by acpaquette** [comment]
Example output from the apollo jigsaw test in ISIS [bundleout.txt](https://github.com/USGS-Astrogeology/ISIS3/files/3597698/bundleout.txt)

**Comment by jlaura** [comment]
@acpaquette Thanks!

**Comment by jlaura** [comment]
How is the `IMAGE MEASURES SUMMARY` section rendering for you? I am seeing some weirdness associated with the width of my terminal (which I suspect is unavoidable in a plain txt file). Does it render with nice columns on a side screen?

**Comment by lwellerastro** [comment]
Chatted with @acpaquette already about that when he stopped by to see what I thought (it didn't get any changes so it looks the same as before).  He's on it.

**Comment by acpaquette** [comment]
Okay, new output with fixed RMS formatting [bundleout.txt](https://github.com/USGS-Astrogeology/ISIS3/files/3598129/bundleout.txt)

**Comment by lwellerastro** [comment]
Good to go.  Thanks!

**Review by jessemapel — APPROVED** [review]
Looks good to me, is there a truthdata update for one of the jigsaw app tests too?

**Comment by acpaquette** [comment]
No, there are no jigsaw app tests that check the bundleout.txt files

**Pull request merged**
