### PR TITLE
disabled broken tests

### PR DESCRIPTION
**Pull request by Kelvinrr**
## Description

Disables tests they have been failing for an extended period of time with known issues which haven't been addressed. 

## Related Issue

Issue tracking fixing these tests: #4666

TGO failures: #4661
ObservationPair fixture Failures: #4609 
edrget is also expected to be deprecated? No dedicated issue, but was mentioned in #4633

## Motivation and Context

These tests have been failing for a while, so might as well disable them until they're properly addressed. 

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation change (update to the documentation; no code change)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] I have read and agree to abide by the [Code of Conduct](https://github.com/USGS-Astrogeology/ISIS3/blob/dev/Code-Of-Conduct.md)
- [ ] I have read the [**CONTRIBUTING**](https://github.com/USGS-Astrogeology/ISIS3/blob/dev/CONTRIBUTING.md) document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [ ] I have added myself to the [.zenodo.json](https://github.com/USGS-Astrogeology/ISIS3/blob/dev/.zenodo.json) document.
- [ ] I have added any user impacting changes to the [CHANGELOG.md](https://github.com/USGS-Astrogeology/ISIS3/blob/dev/CHANGELOG.md) document.

## Licensing
This project is mostly composed of free and unencumbered software released into the public domain, and we are unlikely to accept contributions that are not also released into the public domain. Somewhere near the top of each file should have these words:

> This work is free and unencumbered software released into the public domain. In jurisdictions that recognize copyright laws, the author or authors of this software dedicate any and all copyright interest in the software to the public domain.

- [ ] I dedicate any and all copyright interest in this software to the public domain. I make this dedication for the benefit of the public at large and to the detriment of my heirs and successors. I intend this dedication to be an overt act of relinquishment in perpetuity of all present and future rights to this software under copyright law.

### CODE REVIEW

**Comment by KrisBecker** [comment]
Why is disabling failing tests with known issues an acceptable solution to this problem?

**Comment by jlaura** [comment]
@KrisBecker These are tests that are consistently failing because of reasons outside of the test. They are not valid test cases because they are not testing anything. The development team is ignoring them as valid tests and asserting that the software is clean because these tests are brittle. 

They are not being removed from the code base (though the EDRGET ones will be if and when EDRGET is deprecated; see the RFC), but are being disabled until a PR can be put in to make these tests less brittle.

**Comment by jlaura** [comment]
@Kelvinrr These changes look good. We need associated issues (or one über issue) to get these tests turned back on with proper updates so that they are less brittle.

**Comment by Kelvinrr** [comment]
@jlaura I can do one for all of them. I just imagine it was somewhat redundant since the source of the errors are already the subject in other issues.

**Comment by Kelvinrr** [comment]
updated the description to point to new issue

**Review by jlaura — DISMISSED** [review]

**Comment by jlaura** [comment]
Delete instead of comment out?

**Comment by Kelvinrr** [comment]
@jlaura the tests were not being properly disabled and were instead failing with "no target found" since they were empty makefiles. 

I don't think there is a good way to disable these tests with deleting things.

**Comment by jessemapel** [comment]
When we've done this in the past with Makefile tests, we've commented out the test commands and instead just had it run an echo that explains why it was disabled.

**Review by jessemapel — APPROVED** [review]

**Comment by Kelvinrr** [comment]
App test "passed" after updating the truth so this should be good.

**Pull request merged**
