### PR TITLE
Add Utilities, clean up testing

### PR DESCRIPTION
**Pull request by jessemapel**

### CODE REVIEW

**Comment by jessemapel** [comment]
Example QString comparison output on failure
`QStrings GetParam().first (#000000gf) and Color::toRGBAString(GetParam().second) (#000000ff) are not the same.`

**Comment by jessemapel** [comment]
Example IException bad message failure `IException e's error message (**ERROR** Can not convert an invalid color to an RGBA string.  There is no string representation of an invalid color.) does not contain message (Can not convert an invalid color to an RGBA string.  There is no string representation of an invalid color.blah).`

**Comment by jessemapel** [comment]
Example IExcpetion bad error type failure `IException e's error code (1) does not equal IException::Programmer (3).`

**Review by SgStapleton — APPROVED** [review]
Everything looks good. I will implement a refactor of TestUtilities as discussed with @jessemapel

**Review by krlberry — COMMENTED** [review]
:+1: All looks good to me.

**Pull request merged**
