### PR TITLE
Qt 5.15.8 Update

### PR DESCRIPTION
**Pull request by amystamile-usgs**
## Description

Updating qt to 5.15.8

The following changes are regarding the following depreciations:

**1735 warnings left**

- [x] 'QXmlDefaultHandler' is deprecated **(805 warnings)**
- [x] 'QXmlParseException' is deprecated **(868 warnings)**
- [x] 'QXmlSimpleReader' is deprecated: Use QXmlStreamReader **(44 warnings)**
- [x] 'QXmlAttributes' is deprecated **(1 warning)**
- [x] 'QXmlInputSource' is deprecated **(17 warnings)**
- [x] 'QMatrix' is deprecated: Use QTransform
- [x] 'endl' is deprecated: Use Qt::endl
- [x] 'qSort<QList<QString>>' is deprecated: Use std::sort
- [x] 'width' is deprecated: Use QFontMetrics::horizontalAdvance
- [x] 'split' is deprecated: Use Qt::SplitBehavior variant instead
- [x] 'QFlags' is deprecated: Use default constructor instead	
- [x] 'lastIndexOf' is deprecated: Use QString's toUtf8(), toLatin1() or toLocal8Bit() 
- [x] 'toSet' is deprecated: Use QSet<T>(list.begin(), list.end()) instead.
- [x] 'fromSet' is deprecated: Use QList<T>(set.begin(), set.end()) instead.
- [x] 'start' is deprecated: Use QElapsedTimer instead
- [x] 'elapsed' is deprecated: Use QElapsedTimer instead
- [x] 'toStdVector' is deprecated: Use std::vector<T>(vector.begin(), vector.end()) instead.
- [x] 'qLess<double>' is deprecated: Use std::less
- [x] 'null' is deprecated: use QString()
- [x] 'fromStdVector' is deprecated: Use QVector<T>(vector.begin(), vector.end()) instead.
- [x] 'insertMulti' is deprecated: Use QMultiMap for maps storing multiple values with the same key.
- [x] 'primaryScreen' is deprecated: Use QGuiApplication::primaryScreen()
- [x] 'availableGeometry' is deprecated: Use QGuiApplication::screens()
- [x] 'toList' is deprecated: Use values() instead.
- [x] 'qVariantFromValue<Isis::Image *>' is deprecated: Use QVariant::fromValue() instead.
- [x] 'append' is deprecated: Use QString's toUtf8(), toLatin1() or toLocal8Bit()
- [x] 'qStableSort<QList<Isis::AbstractTreeItem *>::iterator, Isis::AbstractTableModel::LessThanFunctor>' is deprecated: Use std::stable_sort
- [x] 'screenGeometry' is deprecated: Use QGuiApplication::screens()
- [x] 'isItemSelected' is deprecated: Use QListWidgetItem::isSelected() instead
- [x] 'light' is deprecated: Use QColor::lighter() instead
- [x] 'dark' is deprecated: Use QColor::darker() instead
- [x] 'intersect' is deprecated: Use intersects() instead
- [x] 'drawRoundRect' is deprecated: Use drawRoundedRect(..., Qt::RelativeSize) instead
- [x] 'operator=' is deprecated: Use QDir::setPath() instead
- [x] 'setPageSize' is deprecated: Use setPageSize(QPageSize) instead.
- [x] qBinaryFind<QList<QString>::iterator, QString>' is deprecated: Use std::binary_search
- [x] 'qsrand' is deprecated: use QRandomGenerator instead
- [x] 'uniqueKeys' is deprecated: Use QMultiMap for maps storing multiple values with the same key.
- [x] 'values' is deprecated: Use QMultiMap for maps storing multiple values with the same key.
- [x] local variable 'frameMap' will be copied despite being returned by name call 'std::move' explicitly to avoid copying
- [x] qFind<QList<Isis::Image *>::iterator, Isis::Image *>' is deprecated: Use std::find
- [x] 'start' is deprecated: Use QProcess::start(const QString &program, const QStringList &arguments,OpenMode mode = ReadWrite) instead

## Related Issue

#5336 

## Motivation and Context

Isis Dependencies Sprint

## How Has This Been Tested?

Running PR against Jenkins for any test failures

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation change (update to the documentation; no code change)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] I have read and agree to abide by the [Code of Conduct](https://github.com/USGS-Astrogeology/ISIS3/blob/dev/Code-Of-Conduct.md)
- [ ] I have read the [**CONTRIBUTING**](https://github.com/USGS-Astrogeology/ISIS3/blob/dev/CONTRIBUTING.md) document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [ ] I have added myself to the [.zenodo.json](https://github.com/USGS-Astrogeology/ISIS3/blob/dev/.zenodo.json) document.
- [ ] I have added any user impacting changes to the [CHANGELOG.md](https://github.com/USGS-Astrogeology/ISIS3/blob/dev/CHANGELOG.md) document.

## Licensing
This project is mostly composed of free and unencumbered software released into the public domain, and we are unlikely to accept contributions that are not also released into the public domain. Somewhere near the top of each file should have these words:

> This work is free and unencumbered software released into the public domain. In jurisdictions that recognize copyright laws, the author or authors of this software dedicate any and all copyright interest in the software to the public domain.

- [ ] I dedicate any and all copyright interest in this software to the public domain. I make this dedication for the benefit of the public at large and to the detriment of my heirs and successors. I intend this dedication to be an overt act of relinquishment in perpetuity of all present and future rights to this software under copyright law.

### CODE REVIEW

**Comment by acpaquette** [comment]
With regards to `endl`, that should be part of a standard library in C++. I guess I'm just confused why an update to Qt would deprecate `endl`?

**Comment by amystamile-usgs** [comment]
> With regards to `endl`, that should be part of a standard library in C++. I guess I'm just confused why an update to Qt would deprecate `endl`?

@acpaquette It's anytime endl is being piped into a QDebug.

**Comment by amystamile-usgs** [comment]
Linux is failing the conda environment with the following incompatibilites:

````
The following specifications were found to be incompatible with your system:

  - feature:/linux-64::__glibc==2.27=0
  - feature:|@/linux-64::__glibc==2.27=0
  - ale=0.8.6 -> libgcc-ng[version='>=9.3.0'] -> __glibc[version='>=2.17']
  - armadillo -> libgcc-ng[version='>=9.3.0'] -> __glibc[version='>=2.17']
  - blas -> libgfortran-ng -> __glibc[version='>=2.17']
  - boost-cpp=1.72 -> libgcc-ng[version='>=9.3.0'] -> __glibc[version='>=2.17']
  - boost=1.72 -> libgcc-ng[version='>=7.5.0'] -> __glibc[version='>=2.17']
  - bzip2 -> libgcc-ng[version='>=9.3.0'] -> __glibc[version='>=2.17']
  - cmake[version='>=3.15'] -> libgcc-ng[version='>=9.3.0'] -> __glibc[version='>=2.17']
  - csm[version='>=3.0.3,<3.0.4'] -> libgcc-ng[version='>=7.5.0'] -> __glibc[version='>=2.17']
  - cspice -> libgcc-ng[version='>=9.3.0'] -> __glibc[version='>=2.17']
  - curl -> libgcc-ng[version='>=9.3.0'] -> __glibc[version='>=2.17']
  - doxygen -> libgcc-ng[version='>=9.3.0'] -> __glibc[version='>=2.17']
  - eigen[version='<3.4'] -> libgcc-ng[version='>=9.3.0'] -> __glibc[version='>=2.17']
  - ffmpeg -> libgcc-ng[version='>=9.3.0'] -> __glibc[version='>=2.17']
  - geos[version='>=3.7,<3.8'] -> libgcc-ng[version='>=7.3.0'] -> __glibc[version='>=2.17']
  - geotiff -> libgcc-ng[version='>=9.3.0'] -> __glibc[version='>=2.17']
  - gmp -> libgcc-ng[version='>=7.5.0'] -> __glibc[version='>=2.17']
  - graphviz -> libgcc-ng[version='>=9.3.0'] -> __glibc[version='>=2.17']
  - gsl[version='>=2.6'] -> libgcc-ng[version='>=9.3.0'] -> __glibc[version='>=2.17']
  - hdf5 -> libgfortran-ng -> __glibc[version='>=2.17']
  - icu -> libgcc-ng[version='>=7.5.0'] -> __glibc[version='>=2.17']
  - inja -> libgcc-ng[version='>=9.3.0'] -> __glibc[version='>=2.17']
  - jpeg -> libgcc-ng[version='>=7.5.0'] -> __glibc[version='>=2.17']
  - krb5 -> libgcc-ng[version='>=9.3.0'] -> __glibc[version='>=2.17']
  - libopencv[version='>=4.5.2'] -> libgcc-ng[version='>=9.3.0'] -> __glibc[version='>=2.17']
  - libpng[version='>=1.6.34'] -> libgcc-ng[version='>=7.5.0'] -> __glibc[version='>=2.17']
  - libprotobuf -> libgcc-ng[version='>=9.3.0'] -> __glibc[version='>=2.17']
  - libtiff[version='>=4.0'] -> libgcc-ng[version='>=9.3.0'] -> __glibc[version='>=2.17']
  - libxml2 -> libgcc-ng[version='>=9.3.0'] -> __glibc[version='>=2.17']
  - make -> libgcc-ng[version='>=7.5.0'] -> __glibc[version='>=2.17']
  - mesalib -> __glibc[version='>=2.17,<3.0.a0']
  - mesalib -> libgcc-ng[version='>=7.3.0'] -> __glibc[version='>=2.17']
  - mysql -> libgcc-ng[version='>=7.3.0'] -> __glibc[version='>=2.17']
  - mysql-connector-c -> libgcc-ng[version='>=7.5.0'] -> __glibc[version='>=2.17']
  - nn -> libgcc-ng[version='>=7.3.0'] -> __glibc[version='>=2.17']
  - opencv[version='>=4.5.2'] -> libgcc-ng[version='>=7.5.0'] -> __glibc[version='>=2.17']
  - openssl[version='>=1.1.1k'] -> libgcc-ng[version='>=9.3.0'] -> __glibc[version='>=2.17']
  - pcl[version='>=1.10.0'] -> vtk[version='>=9.1.0,<9.1.1.0a0'] -> __glibc[version='>=2.17|>=2.17,<3.0.a0']
  - protobuf -> libgcc-ng[version='>=9.3.0'] -> __glibc[version='>=2.17']
  - python[version='>=3.7.11'] -> libgcc-ng[version='>=9.3.0'] -> __glibc[version='>=2.17']
  - qhull -> libgcc-ng[version='>=9.3.0'] -> __glibc[version='>=2.17']
  - qt-main[version='>=5.15.2'] -> __glibc[version='>=2.17,<3.0.a0']
  - qwt[version='>=6.2.0'] -> __glibc[version='>=2.17,<3.0.a0']
  - qwt[version='>=6.2.0'] -> libgcc-ng[version='>=9.3.0'] -> __glibc[version='>=2.17']
  - suitesparse -> libgcc-ng[version='>=9.3.0'] -> __glibc[version='>=2.17']
  - superlu -> libgcc-ng[version='>=9.3.0'] -> __glibc[version='>=2.17']
  - swig -> libgcc-ng[version='>=9.3.0'] -> __glibc[version='>=2.17']
  - texlive-core -> libgcc-ng[version='>=9.3.0'] -> __glibc[version='>=2.17']
  - x264 -> libgcc-ng[version='>=9.3.0'] -> __glibc[version='>=2.17']
  - xalan-c -> libgcc-ng[version='>=7.3.0'] -> __glibc[version='>=2.17']
  - xerces-c=3 -> libgcc-ng[version='>=9.3.0'] -> __glibc[version='>=2.17']
  - xorg-kbproto -> libgcc-ng[version='>=9.3.0'] -> __glibc[version='>=2.17']
  - xorg-libice -> libgcc-ng[version='>=9.3.0'] -> __glibc[version='>=2.17']
  - xorg-libsm -> libgcc-ng[version='>=9.3.0'] -> __glibc[version='>=2.17']
  - xorg-libx11 -> libgcc-ng[version='>=9.3.0'] -> __glibc[version='>=2.17']
  - xorg-libxi -> libgcc-ng[version='>=9.3.0'] -> __glibc[version='>=2.17']
  - zlib -> libgcc-ng[version='>=7.5.0'] -> __glibc[version='>=2.17']
````

**Comment by acpaquette** [comment]
@amystamile-usgs I've run into this before on updating some other package. Trying to remember why it happend

**Comment by acpaquette** [comment]
It seems like the issues on linux are related to the pinned version of ALE, then after that is handled `libopencv` cannot be solved for since there is not version of `libopencv` that is built with Qt 5.15. I have put an issue in with the Opencv feedstock to see if this can be updated.

https://github.com/conda-forge/opencv-feedstock/issues/312

**Comment by jlaura** [comment]
@amystamile-usgs @acpaquette What is the status on this? Can we schedule this for completion or does this have outstanding external dependencies?

**Comment by acpaquette** [comment]
@jlaura Sorry to take so long on this, I think that the linux solve issues may be resolved? I just built an isis build environment on prog28 that picked up qt 5.15, going to confirm this. I know that there was still somethings to solve on the actual code side of things as well

**Comment by jlaura** [comment]
@acpaquette No worries on the timeline! Does that mean that this needs to get updated and merged, or that this was resolved external to us?

**Comment by acpaquette** [comment]
This is also going to run into issue with protobuf and opencv. See:
https://github.com/protocolbuffers/protobuf/issues/9947

**Comment by acpaquette** [comment]
@jlaura This was resolved externally but it looks like we will be running into other issues from external dependencies as per my previous comment

**Comment by acpaquette** [comment]
@jlaura @jessemapel Supporting Ubuntu 20.04 and 22 would likely require updates to Qt that this PR has started

**Comment by jessemapel** [comment]
#5031

**Comment by acpaquette** [comment]
@amystamile-usgs Jenkins is failing to solve the env, we may need to change the environment file. Pinning the python version to 3.9 may be enough.

**Comment by amystamile-usgs** [comment]
~~Refreshing my memory on this PR. It is currently on hold because we need to rework the XML Reader/Writer. I think Adam was working on this at some point.~~

Accidentally removed Adam's commits with these fixes. Added them back in.

**Comment by amystamile-usgs** [comment]
Splitting up this PR into multiple smaller PRs

**Pull request closed without merging**
