### PR TITLE
Updates googletest to version 1.12.1 for Monterey Update

### PR DESCRIPTION
**Pull request by amystamile-usgs**
## Description

Compiling errors with current version of google tests on Monterey OS with C++14. 1.12.1 version handles C++14. It should also handle C++11 and up. Therefore this needs to be tested on a Mac machine that is on an older OS version.

Ran into a weird issue where after the update where any TEST_P gtests would cause segfaults when creating the RunISISTest executable. I could not figure out why this was the case. I ended up just converting these parameterization tests to regular gtests.

This is a breaking change for people with C++ compilers less than version 11.

## Related Issue

#5074 

## How Has This Been Validated?

Still needs to be testing on older OS vesions

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation change (update to the documentation; no code change)
- [X] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Infrastructure change (changes to things like CI or the build system that do not impact users)

## Checklist:

- [x] I have read and agree to abide by the [Code of Conduct](https://github.com/USGS-Astrogeology/ISIS3/blob/dev/Code-Of-Conduct.md)
- [x] I have read the [**CONTRIBUTING**](https://github.com/USGS-Astrogeology/ISIS3/blob/dev/CONTRIBUTING.md) document.
- [ ] My change requires a change to the documentation and I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.
- [ ] I have added myself to the [.zenodo.json](https://github.com/USGS-Astrogeology/ISIS3/blob/dev/.zenodo.json) document.
- [ ] I have added any user impacting changes to the [CHANGELOG.md](https://github.com/USGS-Astrogeology/ISIS3/blob/dev/CHANGELOG.md) document.

## Licensing
This project is mostly composed of free and unencumbered software released into the public domain, and we are unlikely to accept contributions that are not also released into the public domain. Somewhere near the top of each file should have these words:

> This work is free and unencumbered software released into the public domain. In jurisdictions that recognize copyright laws, the author or authors of this software dedicate any and all copyright interest in the software to the public domain.

- [x] I dedicate any and all copyright interest in this software to the public domain. I make this dedication for the benefit of the public at large and to the detriment of my heirs and successors. I intend this dedication to be an overt act of relinquishment in perpetuity of all present and future rights to this software under copyright law.

### CODE REVIEW

**Comment by amystamile-usgs** [comment]
@jlaura Would you be able to test this on your Big Sur OS? Not sure if we have any mac machines to test on anymore.

**Comment by jlaura** [comment]
~@amystamile-usgs Should I be re-cloning the gtest submodule?~

Build is happening now. I need to mount the data/testdata to be able to run the tests on BigSur. Hopefully done before 9AM.

### Update:
Not sure how far this has to run before failing. Here is the current output:

```bash
❯ ctest
Test project /Users/jlaura/github/isis3/build
          Start    1: SensorUtilities.ImagePt.NoBandInit
   1/2372 Test    #1: SensorUtilities.ImagePt.NoBandInit .........................................................   Passed    0.05 sec
          Start    2: SensorUtilities.Magnitude.Unit
   2/2372 Test    #2: SensorUtilities.Magnitude.Unit .............................................................   Passed    0.01 sec
          Start    3: SensorUtilities.Magnitude.NonUnit
   3/2372 Test    #3: SensorUtilities.Magnitude.NonUnit ..........................................................   Passed    0.01 sec
          Start    4: SensorUtilities.Difference.vec
   4/2372 Test    #4: SensorUtilities.Difference.vec .............................................................   Passed    0.01 sec
          Start    5: SensorUtilities.SepAngle.RightAngle
   5/2372 Test    #5: SensorUtilities.SepAngle.RightAngle ........................................................   Passed    0.01 sec
          Start    6: SensorUtilities.SepAngle.AcuteAngle
   6/2372 Test    #6: SensorUtilities.SepAngle.AcuteAngle ........................................................   Passed    0.01 sec
          Start    7: SensorUtilities.SepAngle.ObtuseAngle
   7/2372 Test    #7: SensorUtilities.SepAngle.ObtuseAngle .......................................................   Passed    0.01 sec
          Start    8: SensorUtilities.SepAngle.Normalization
   8/2372 Test    #8: SensorUtilities.SepAngle.Normalization .....................................................   Passed    0.01 sec
          Start    9: SensorUtilities.SphericalToRect.Axes
   9/2372 Test    #9: SensorUtilities.SphericalToRect.Axes .......................................................   Passed    0.01 sec
          Start   10: SensorUtilities.RectToSpherical.Axes
  10/2372 Test   #10: SensorUtilities.RectToSpherical.Axes .......................................................   Passed    0.01 sec
          Start   11: SensorUtilities.PhaseAngle.Acute
  11/2372 Test   #11: SensorUtilities.PhaseAngle.Acute ...........................................................   Passed    0.01 sec
          Start   12: SensorUtilities.EmissionAngle.Acute
  12/2372 Test   #12: SensorUtilities.EmissionAngle.Acute ........................................................   Passed    0.01 sec
          Start   13: SensorUtilities.IlluminationDistance.Earth
  13/2372 Test   #13: SensorUtilities.IlluminationDistance.Earth .................................................   Passed    0.01 sec
          Start   14: SensorUtilities.SubSpacecraftPoint.LatLon
  14/2372 Test   #14: SensorUtilities.SubSpacecraftPoint.LatLon ..................................................   Passed    0.01 sec
          Start   15: SensorUtilities.SubSpacecraftPoint.LatLonRad
  15/2372 Test   #15: SensorUtilities.SubSpacecraftPoint.LatLonRad ...............................................   Passed    0.01 sec
          Start   16: SensorUtilities.SubSolarPoint.LatLon
  16/2372 Test   #16: SensorUtilities.SubSolarPoint.LatLon .......................................................   Passed    0.00 sec
          Start   17: SensorUtilities.SubSolarPoint.LatLonRad
  17/2372 Test   #17: SensorUtilities.SubSolarPoint.LatLonRad ....................................................   Passed    0.00 sec
          Start   18: SensorUtilities.LocalRadius.Intersection
  18/2372 Test   #18: SensorUtilities.LocalRadius.Intersection ...................................................   Passed    0.00 sec
          Start   19: SensorUtilities.LocalRadius.Ground
  19/2372 Test   #19: SensorUtilities.LocalRadius.Ground .........................................................   Passed    0.00 sec
          Start   20: isis_unit_test_AbstractPlate
  20/2372 Test   #20: isis_unit_test_AbstractPlate ...............................................................   Passed    2.97 sec
          Start   21: isis_unit_test_AbstractShape
  21/2372 Test   #21: isis_unit_test_AbstractShape ...............................................................   Passed    0.51 sec
          Start   22: isis_unit_test_AdaptiveGruen
  22/2372 Test   #22: isis_unit_test_AdaptiveGruen ...............................................................   Passed    8.78 sec
          Start   23: isis_unit_test_Affine
  23/2372 Test   #23: isis_unit_test_Affine ......................................................................   Passed    0.50 sec
          Start   24: isis_unit_test_Albedo
  24/2372 Test   #24: isis_unit_test_Albedo ......................................................................   Passed    0.94 sec
          Start   25: isis_unit_test_AlbedoAtm
  25/2372 Test   #25: isis_unit_test_AlbedoAtm ...................................................................   Passed    0.91 sec
          Start   26: isis_unit_test_AlphaCube
  26/2372 Test   #26: isis_unit_test_AlphaCube ...................................................................   Passed    3.64 sec
          Start   27: isis_unit_test_Angle
  27/2372 Test   #27: isis_unit_test_Angle .......................................................................   Passed    0.71 sec
          Start   28: isis_unit_test_Anisotropic1
  28/2372 Test   #28: isis_unit_test_Anisotropic1 ................................................................   Passed    0.50 sec
          Start   29: isis_unit_test_Anisotropic2
  29/2372 Test   #29: isis_unit_test_Anisotropic2 ................................................................   Passed    0.75 sec
          Start   30: isis_unit_test_Application
  30/2372 Test   #30: isis_unit_test_Application .................................................................   Passed    0.65 sec
          Start   31: isis_unit_test_Area3D
  31/2372 Test   #31: isis_unit_test_Area3D ......................................................................   Passed    0.51 sec
          Start   32: isis_unit_test_AtmosModel
  32/2372 Test   #32: isis_unit_test_AtmosModel ..................................................................   Passed    0.54 sec
          Start   33: isis_unit_test_AtmosModelFactory
  33/2372 Test   #33: isis_unit_test_AtmosModelFactory ...........................................................   Passed    0.50 sec
          Start   34: isis_unit_test_AutoReg
  34/2372 Test   #34: isis_unit_test_AutoReg .....................................................................   Passed   27.85 sec
          Start   35: isis_unit_test_AutoRegFactory
  35/2372 Test   #35: isis_unit_test_AutoRegFactory ..............................................................   Passed    0.71 sec
          Start   36: isis_unit_test_BandManager
  36/2372 Test   #36: isis_unit_test_BandManager .................................................................   Passed    2.52 sec
          Start   37: isis_unit_test_Basis1VariableFunction
  37/2372 Test   #37: isis_unit_test_Basis1VariableFunction ......................................................   Passed    0.51 sec
          Start   38: isis_unit_test_Blob
  38/2372 Test   #38: isis_unit_test_Blob ........................................................................   Passed    0.55 sec
          Start   39: isis_unit_test_Blobber
  39/2372 Test   #39: isis_unit_test_Blobber .....................................................................   Passed    5.35 sec
          Start   40: isis_unit_test_BoxcarCachingAlgorithm
  40/2372 Test   #40: isis_unit_test_BoxcarCachingAlgorithm ......................................................   Passed    0.50 sec
          Start   41: isis_unit_test_BoxcarManager
  41/2372 Test   #41: isis_unit_test_BoxcarManager ...............................................................   Passed    1.69 sec
          Start   42: isis_unit_test_Brick
  42/2372 Test   #42: isis_unit_test_Brick .......................................................................   Passed    0.50 sec
          Start   43: isis_unit_test_Buffer
  43/2372 Test   #43: isis_unit_test_Buffer ......................................................................   Passed    0.50 sec
          Start   44: isis_unit_test_BufferManager
  44/2372 Test   #44: isis_unit_test_BufferManager ...............................................................   Passed    0.50 sec
          Start   45: isis_unit_test_BulletShapeModel
  45/2372 Test   #45: isis_unit_test_BulletShapeModel ............................................................***Failed    5.00 sec
```

**Comment by amystamile-usgs** [comment]
@jlaura I was more worried about whether you would be able to run the tests or not. So it's good to see that you are running them! I did run the entire test suite last night and got 876 tests failed out of 2370. I need to go back through and see if this is relating to the gtest changes or not. Seems like the majority of them are unit and app tests.

**Comment by jlaura** [comment]
@amystamile-usgs Awesome. Tests are quite slow because I"m just mounting the EFS (no local cache for me yet). I'll let you know how many failures I see on my side.

I did have to resync gtest, but I'm not sure if that was a product of this PR or because my local copy was super out of date.

```bash
❯ git submodule update --init --recursive
Submodule 'gtest' (https://github.com/google/googletest.git) registered for path '../gtest'
Cloning into '/Users/jlaura/github/isis3/gtest'...
Submodule path '../gtest': checked out '912db742531bf82efb01194bc08140416e3b3467'
```

**Comment by amystamile-usgs** [comment]
@jlaura Yeah resyncing is expected. I ran these changes on prog28 and had compile errors with gtest. Turns out, that linux machine has g++ version 7.4.0 so not sure how we should handle gtests with older compiler versions.

**Comment by acpaquette** [comment]
@amystamile-usgs I would ignore the prog machines and use the jenkins builds to validate the linux issues:
https://jenkins.prod-asc.chs.usgs.gov:8443/job/ISIS/view/change-requests/job/PR-5076/

**Comment by jlaura** [comment]
This worked on OSX up until the point that that the NFS mount randomly dropped. Then all the tests, naturally failed. Do you want me to clone down the test data locally and run?

**Comment by amystamile-usgs** [comment]
@acpaquette Looks like jenkins is running into the same build errors as prog28.

@jlaura don't worry about rerunning the tests.

**Comment by KrisBecker** [comment]
Not sure if you prefer me to post in this PR or in #5074.

I updated the Googletest module using the command `git submodule update --remote --merge` as suggested in #5074. The output looked pretty ominous (in the following snippet):

```
(Nov162022) kbecker@zion3 ISIS3 % git submodule update --remote --merge
Updating 703bd9ca..4408a028
Fast-forward
 .github/ISSUE_TEMPLATE/00-bug_report.md                                      |   43 +
 .github/ISSUE_TEMPLATE/10-feature_request.md                                 |   24 +
 .github/ISSUE_TEMPLATE/config.yml                                            |    1 +
 .github/workflows/gtest-ci.yml                                               |   43 +
 .travis.yml                                                                  |   73 -
 BUILD.bazel                                                                  |   45 +-
 CMakeLists.txt                                                               |   23 +-
 CONTRIBUTING.md                                                              |   27 +-
 googletest/CONTRIBUTORS => CONTRIBUTORS                                      |   28 +
 README.md                                                                    |  121 +-
 WORKSPACE                                                                    |   39 +-
 appveyor.yml                                                                 |  154 -
 ci/build-linux-bazel.sh                                                      |   37 -
 ci/build-platformio.sh                                                       |    2 -
.
.
.
Submodule path 'gtest': merged in '4408a0288b24fbe9156a9b14bbecd148ea64f40f'
```

The build nearly completes. It is failing during test discovery. I had found some people suggesting to turn off threads for gtest, but that made no difference. It still segfaults with and without threads enabled.

I built with debug on and have a traceback from the crash log. Not sure what to make of it - whether its an ISIS or a googletest problem - but its in the BundleObservation tests:

```
Thread 0 Crashed::  Dispatch queue: com.apple.main-thread
0   libc++.1.dylib                	    0x7ff8102b590a std::__1::istreambuf_iterator<char, std::__1::char_traits<char> > std::__1::num_get<char, std::__1::istreambuf_iterator<char, std::__1::char_traits<char> > >::__do_get_unsigned<unsigned short>(std::__1::istreambuf_iterator<char, std::__1::char_traits<char> >, std::__1::istreambuf_iterator<char, std::__1::char_traits<char> >, std::__1::ios_base&, unsigned int&, unsigned short&) const + 54
1   libc++.1.0.dylib              	       0x11a91b8d8 std::__1::basic_ostream<char, std::__1::char_traits<char> >::operator<<(unsigned long) + 248
2   runISISTests                  	       0x10932e5f0 testing::Message& testing::Message::operator<<<unsigned long>(unsigned long const&) + 48 (gtest-message.h:130)
3   runISISTests                  	       0x10932e509 std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > testing::internal::DefaultParamName<QPair<Isis::BundleObservationSolveSettings::CSMSolveOption, QString> >(testing::TestParamInfo<QPair<Isis::BundleObservationSolveSettings::CSMSolveOption, QString> > const&) + 57 (gtest-param-util.h:380)
4   runISISTests                  	       0x1093152a6 gtest_BundleObservationSolveSettingsCSMSolveOptionStrings_EvalGenerateName_(testing::TestParamInfo<QPair<Isis::BundleObservationSolveSettings::CSMSolveOption, QString> > const&) + 742 (BundleObservationSolveSettingsTests.cpp:496)
5   runISISTests                  	       0x109341608 testing::internal::ParameterizedTestSuiteInfo<CSMSolveOptionStrings>::RegisterTests() + 744 (gtest-param-util.h:580)
6   libgtest.1.12.1.dylib         	       0x11a763182 testing::internal::ParameterizedTestSuiteRegistry::RegisterTests() + 98 (gtest-param-util.h:731)
7   libgtest.1.12.1.dylib         	       0x11a7630f1 testing::internal::UnitTestImpl::RegisterParameterizedTests() + 49 (gtest.cc:2824)
8   libgtest.1.12.1.dylib         	       0x11a774a93 testing::internal::UnitTestImpl::PostFlagParsingInit() + 67 (gtest.cc:5655)
9   libgtest.1.12.1.dylib         	       0x11a777754 void testing::internal::InitGoogleTestImpl<char>(int*, char**) + 212 (gtest.cc:6710)
10  libgtest.1.12.1.dylib         	       0x11a77766d testing::InitGoogleTest(int*, char**) + 29 (gtest.cc:6728)
11  runISISTests                  	       0x10925ea2d main + 45 (IsisTestMain.cpp:9)
12  dyld                          	       0x11d04852e start + 462
```

**Comment by amystamile-usgs** [comment]
@KrisBecker I figured out the segfaults with runISISTests were due to the TEST_P functions in our gtests. I could not figure out why these functions were causing issues but this PR just converts all the TEST_P to regular TEST functions. This allow me to successfully build isis. The bundle observation tests were one of the files I updating here. Feel free to test these changes locally to see if you get past the errors you are seeing.

**Comment by jlaura** [comment]
@KrisBecker  To hopefully put your mind at ease - that looks like a pretty standard update when merging. The fact that it was a fast-forward is nice to see.

> Not sure if you prefer me to post in this PR or in #5074.
> 
> I updated the Googletest module using the command `git submodule update --remote --merge` as suggested in #5074. The output looked pretty ominous (in the following snippet):
> 
> ```
> (Nov162022) kbecker@zion3 ISIS3 % git submodule update --remote --merge
> Updating 703bd9ca..4408a028
> Fast-forward
>  .github/ISSUE_TEMPLATE/00-bug_report.md                                      |   43 +
>  .github/ISSUE_TEMPLATE/10-feature_request.md                                 |   24 +
>  .github/ISSUE_TEMPLATE/config.yml                                            |    1 +
>  .github/workflows/gtest-ci.yml                                               |   43 +
>  .travis.yml                                                                  |   73 -
>  BUILD.bazel                                                                  |   45 +-
>  CMakeLists.txt                                                               |   23 +-
>  CONTRIBUTING.md                                                              |   27 +-
>  googletest/CONTRIBUTORS => CONTRIBUTORS                                      |   28 +
>  README.md                                                                    |  121 +-
>  WORKSPACE                                                                    |   39 +-
>  appveyor.yml                                                                 |  154 -
>  ci/build-linux-bazel.sh                                                      |   37 -
>  ci/build-platformio.sh                                                       |    2 -
> .
> .
> .
> Submodule path 'gtest': merged in '4408a0288b24fbe9156a9b14bbecd148ea64f40f'
> ```

**Pull request closed without merging**
