### PR TITLE
7.0 rc2 manual cherry picks

### PR DESCRIPTION
**Pull request by jessemapel**
Manually cherry-picked the following changes to 7.0 for 7.0 RC2:

#4892 

New website work
#4839 
#4847 
#4851 
#4852 
#4856 
#4865
#4859 
#4872 
#4871

### CODE REVIEW

**Comment by jessemapel** [comment]
Please do not squash this PR, it should be rebased

**Review by Kelvinrr — COMMENTED** [review]
Other than verifying the HRSC changes I dont think I have much more to contribute.

**Comment by jessemapel** [comment]
That's all I'm looking for. Just making sure I didn't miss anything. I'm more concerned about the doc updates because that went in across multiple PRs.

**Review by scsides — APPROVED** [review]
Seems like a reasonable list.

**Pull request merged**
