### PR TITLE
Update Dev Env

### PR DESCRIPTION
**Pull request by acpaquette**
## Description
Updates the dev environment.yml and meta.yml to limit dependency updates for more "volatile" packages. Limits potential updates to bug fix versions for major packages.

## Related Issue
CI/CD

## How Has This Been Validated?
Validated through 8.2 builds/releases

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation change (update to the documentation; no code change)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Infrastructure change (changes to things like CI or the build system that do not impact users)

## Checklist:

- [x] I have read and agree to abide by the [Code of Conduct](https://github.com/USGS-Astrogeology/ISIS3/blob/dev/Code-Of-Conduct.md)
- [x] I have read the [**CONTRIBUTING**](https://github.com/USGS-Astrogeology/ISIS3/blob/dev/CONTRIBUTING.md) document.
- [ ] My change requires a change to the documentation and I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] I have added myself to the [.zenodo.json](https://github.com/USGS-Astrogeology/ISIS3/blob/dev/.zenodo.json) document.
- [ ] I have added my user impacting change to the [CHANGELOG.md](https://github.com/USGS-Astrogeology/ISIS3/blob/dev/CHANGELOG.md) document. 

## Licensing
This project is mostly composed of free and unencumbered software released into the public domain, and we are unlikely to accept contributions that are not also released into the public domain. Somewhere near the top of each file should have these words:

> This work is free and unencumbered software released into the public domain. In jurisdictions that recognize copyright laws, the author or authors of this software dedicate any and all copyright interest in the software to the public domain.

- [x] I dedicate any and all copyright interest in this software to the public domain. I make this dedication for the benefit of the public at large and to the detriment of my heirs and successors. I intend this dedication to be an overt act of relinquishment in perpetuity of all present and future rights to this software under copyright law.

### CODE REVIEW

**Comment by Kelvinrr** [comment]
@amystamile-usgs probably the first to test and see if it fixes things on dev as well on the CI side.

**Comment by amystamile-usgs** [comment]
Started tests - build run: `IsisCodeBuild-52nifRxFNgrA:86764b3d-d40a-47c2-8d21-69727edc6a76`

**Comment by amystamile-usgs** [comment]
@acpaquette Running into cmake errors: 

```

-- The C compiler identification is GNU 12.3.0
--
494 | -- The CXX compiler identification is GNU 12.3.0
495 | -- Detecting C compiler ABI info
496 | -- Detecting C compiler ABI info - done
497 | -- Check for working C compiler: /root/miniconda/envs/isis/bin/x86_64-conda-linux-gnu-cc - skipped
498 | -- Detecting C compile features
499 | -- Detecting C compile features - done
500 | -- Detecting CXX compiler ABI info
501 | -- Detecting CXX compiler ABI info - done
502 | -- Check for working CXX compiler: /root/miniconda/envs/isis/bin/x86_64-conda-linux-gnu-c++ - skipped
503 | -- Detecting CXX compile features
504 | -- Detecting CXX compile features - done
505 | Detected Operating System: Linux_x86_64_Ubuntu22_04
506 | Writing test data folders to = /codebuild/output/src717920724/src/ISIS3/build/testOutputDir
507 | CONFIGURATION
508 | BUILD STATIC CORE: OFF
509 | BUILD TESTS: ON
510 | BUILD CORE: ON
511 | BUILD MISSIONS: ON
512 | JP2K SUPPORT: ON
513 | PYTHON BINDINGS: ON
514 | ISISDATA: /codebuild/readonly/astro_efs/isis_data
515 | ISISTESTDATA: /codebuild/readonly/astro_efs/isis_testData
516 | TEST OUTPUT DIR: /codebuild/output/src717920724/src/ISIS3/build/testOutputDir
517 | INSTALL PREFIX: /root/miniconda/envs/isis
518 | CONDA PREFIX: /root/miniconda/envs/isis
519 | -- Found Boost: /root/miniconda/envs/isis/lib/cmake/Boost-1.78.0/BoostConfig.cmake (found suitable version "1.78.0", minimum required is "1.59.0") found components: atomic log regex log_setup serialization chrono math_c99 container math_c99f context math_c99l system math_tr1 math_tr1f math_tr1l test_exec_monitor date_time thread exception timer filesystem prg_exec_monitor program_options unit_test_framework iostreams wave random wserialization
520 | -- ALE INCLUDE DIR: /root/miniconda/envs/isis/include/ale
521 | -- ALE LIB: /root/miniconda/envs/isis/lib/libale.so
522 | -- JSON INCLUDE DIR: /root/miniconda/envs/isis/include/nlohmann
523 | -- Found Bullet: /root/miniconda/envs/isis/lib/libBulletDynamics.so (Required is at least version "2.86")
524 | -- CHOLMOD INCLUDE: /root/miniconda/envs/isis/include
525 | -- CHOLMOD LIB: /root/miniconda/envs/isis/lib/libcholmod.so
526 | -- CCOLMOD LIB: /root/miniconda/envs/isis/lib/libccolamd.so
527 | -- CAMD LIB: /root/miniconda/envs/isis/lib/libcamd.so
528 | -- AMD LIB: /root/miniconda/envs/isis/lib/libamd.so
529 | -- SUITESPARSE LIB: /root/miniconda/envs/isis/lib/libsuitesparseconfig.so
530 | -- BLAS LIB: /root/miniconda/envs/isis/lib/libblas.so
531 | -- LAPACK LIB: /root/miniconda/envs/isis/lib/liblapack.so
532 | -- CSM INCLUDE: /root/miniconda/envs/isis/include/csm
533 | -- CSM LIB: /root/miniconda/envs/isis/lib/libcsmapi.so
534 | -- CSPICE INCLUDE: /root/miniconda/envs/isis/include/cspice
535 | -- CSPICE LIB: /root/miniconda/envs/isis/lib/libcspice.so
536 | -- EIGEN INCLUDE DIR: /root/miniconda/envs/isis/include/eigen3
537 | -- GEOTIFF INCLUDE DIR: /root/miniconda/envs/isis/include
538 | -- GEOTIFF LIB: /root/miniconda/envs/isis/lib/libgeotiff.so
539 | -- Found GSL: /root/miniconda/envs/isis/include (found suitable version "2.6", minimum required is "2.2.1")
540 | -- Found HDF5: /root/miniconda/envs/isis/lib/libhdf5.so;/root/miniconda/envs/isis/lib/libcrypto.so;/root/miniconda/envs/isis/lib/libcurl.so;/root/miniconda/envs/isis/x86_64-conda-linux-gnu/sysroot/usr/lib/librt.so;/root/miniconda/envs/isis/x86_64-conda-linux-gnu/sysroot/usr/lib/libpthread.so;/root/miniconda/envs/isis/lib/libsz.so;/root/miniconda/envs/isis/lib/libz.so;/root/miniconda/envs/isis/x86_64-conda-linux-gnu/sysroot/usr/lib/libdl.so;/root/miniconda/envs/isis/x86_64-conda-linux-gnu/sysroot/usr/lib/libm.so (found suitable version "1.14.1-2", minimum required is "1.8.15")
541 | -- JAMA INCLUDE DIR: /root/miniconda/envs/isis/include/jama
542 | -- NN INCLUDE DIR: /root/miniconda/envs/isis/include
543 | -- NN LIB: /root/miniconda/envs/isis/lib/libnn.a
544 | -- OPENCV INCLUDE DIR: /root/miniconda/envs/isis/include/opencv4/opencv2
545 | -- OPENCV CORE LIB: /root/miniconda/envs/isis/lib/libopencv_core.so
546 | -- OPENCV VIDEOSTAB LIB: /root/miniconda/envs/isis/lib/libopencv_videostab.so
547 | -- OPENCV SUPERRES LIB: /root/miniconda/envs/isis/lib/libopencv_superres.so
548 | -- OPENCV STITCHING LIB: /root/miniconda/envs/isis/lib/libopencv_stitching.so
549 | -- OPENCV PHOTO LIB: /root/miniconda/envs/isis/lib/libopencv_photo.so
550 | -- OPENCV OBJDETECT LIB: /root/miniconda/envs/isis/lib/libopencv_objdetect.so
551 | -- OPENCV IMGCODECS LIB: /root/miniconda/envs/isis/lib/libopencv_imgcodecs.so
552 | -- OPENCV IMGPROC LIB: /root/miniconda/envs/isis/lib/libopencv_imgproc.so
553 | -- OPENCV CALIB3D LIB: /root/miniconda/envs/isis/lib/libopencv_calib3d.so
554 | -- OPENCV FEATURES2D LIB: /root/miniconda/envs/isis/lib/libopencv_features2d.so
555 | -- OPENCV xFEATURES2D LIB: /root/miniconda/envs/isis/lib/libopencv_xfeatures2d.so
556 | -- OPENCV HIGHGUI LIB: /root/miniconda/envs/isis/lib/libopencv_highgui.so
557 | -- OPENCV FLANN LIB: /root/miniconda/envs/isis/lib/libopencv_flann.so
558 | -- PCL INCLUDE DIR: /root/miniconda/envs/isis/include/pcl-1.13/pcl
559 | -- PCL COMMON LIB: /root/miniconda/envs/isis/lib/libpcl_common.so
560 | -- PCL OCTREE LIB: /root/miniconda/envs/isis/lib/libpcl_octree.so
561 | -- PCL IO LIB: /root/miniconda/envs/isis/lib/libpcl_io.so
562 | CMake Error at CMakeLists.txt:278 (find_package):
563 | Could not find a package configuration file provided by "protobuf" with any
564 | of the following names:
565 |  
566 | protobufConfig.cmake
567 | protobuf-config.cmake
568 |  
569 | Add the installation prefix of "protobuf" to CMAKE_PREFIX_PATH or set
570 | "protobuf_DIR" to a directory containing one of the above files.  If
571 | "protobuf" provides a separate development package or SDK, be sure it has
572 | been installed.

```

**Comment by Kelvinrr** [comment]
I recall @acpaquette  had to make some changes to how protobuf was discovered, maybe an additional change is missing

**Comment by acpaquette** [comment]
@Kelvinrr @amystamile-usgs Updated, apologies for the lag time

**Comment by amystamile-usgs** [comment]
Tests look good. I believe these are the expected failures we are seeing on dev.

Screenshot 2024-07-15 at 2 12 24 PM

**Review by amystamile-usgs — APPROVED** [review]

**Pull request merged**
