### PR TITLE
MacOS tests

### PR DESCRIPTION
**Pull request by Kelvinrr**
Mostly from #3720 

This appends to the PR some changes needed to get ISIS passing for MacOS 10.15 

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation change (update to the documentation; no code change)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] I have read and agree to abide by the [Code of Conduct](https://usgs-astrogeology.github.io/code/)
- [ ] I have read the [**CONTRIBUTING**](https://github.com/USGS-Astrogeology/ISIS3/blob/dev/CONTRIBUTING.md) document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

## Licensing
This project is mostly composed of free and unencumbered software released into the public domain, and we are unlikely to accept contributions that are not also released into the public domain. Somewhere near the top of each file should have these words:

> This work is free and unencumbered software released into the public domain. In jurisdictions that recognize copyright laws, the author or authors of this software dedicate any and all copyright interest in the software to the public domain.

- [ ] I dedicate any and all copyright interest in this software to the public domain. I make this dedication for the benefit of the public at large and to the detriment of my heirs and successors. I intend this dedication to be an overt act of relinquishment in perpetuity of all present and future rights to this software under copyright law.

### CODE REVIEW

**Comment by Kelvinrr** [comment]
build status here: https://astroservices.usgs.gov/jenkins/job/ISIS-Builds/job/isis-build-tests-dev/

**Comment by jessemapel** [comment]
Can we close #3720 in favor of this?

**Review by jessemapel — COMMENTED** [review]
Looks reasonable. Once Jenkins is sorted, testing can be evaluated.

**Comment by kaitlyndlee** [comment]
Looks good to me after Jesse's comment is responded to.

**Review by scsides — DISMISSED** [review]
Is there a way to parameterize the docker files? They look to be nearly identical

**Comment by Kelvinrr** [comment]
@jessemapel  We can close  #3720 in favor of this one. ~Once tests finish on Jenkins I think this is good to merge.~ Some module tests failed that I need to check out. If they look fine local I'll merge it. Most app failures are NFS failures.

**Review by jessemapel — APPROVED** [review]

**Comment by Kelvinrr** [comment]
Failing fedora unit test passed locally, so I'll assume it was a fluke and merge this.

**Pull request merged**
