### PR TITLE
Potential fix for bandnorm test fails

### PR DESCRIPTION
**Pull request by tgiroux**
## Description

There have been intermittent test failures on FunctionalTestBandnorm. I replaced some absolute paths to /tmp/pencil.txt which could be causing the problem.

## Related Issue

#4416

## How Has This Been Tested?

All bandnorm tests passed. This failure is intermittent, though, so passing once isn't sure-fire.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation change (update to the documentation; no code change)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] I have read and agree to abide by the [Code of Conduct](https://github.com/USGS-Astrogeology/ISIS3/blob/dev/Code-Of-Conduct.md)
- [x] I have read the [**CONTRIBUTING**](https://github.com/USGS-Astrogeology/ISIS3/blob/dev/CONTRIBUTING.md) document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [x] I have added myself to the [.zenodo.json](https://github.com/USGS-Astrogeology/ISIS3/blob/dev/.zenodo.json) document.
- [x] I have added any user impacting changes to the [CHANGELOG.md](https://github.com/USGS-Astrogeology/ISIS3/blob/dev/CHANGELOG.md) document.

## Licensing
This project is mostly composed of free and unencumbered software released into the public domain, and we are unlikely to accept contributions that are not also released into the public domain. Somewhere near the top of each file should have these words:

> This work is free and unencumbered software released into the public domain. In jurisdictions that recognize copyright laws, the author or authors of this software dedicate any and all copyright interest in the software to the public domain.

- [x] I dedicate any and all copyright interest in this software to the public domain. I make this dedication for the benefit of the public at large and to the detriment of my heirs and successors. I intend this dedication to be an overt act of relinquishment in perpetuity of all present and future rights to this software under copyright law.

### CODE REVIEW

**Comment by Kelvinrr** [comment]
Mac is being wonky on PRs, manually ran another Jenkins job. Not sure the best way to really test this other than constantly re-running Jenkins?

**Comment by jessemapel** [comment]
We could add a repeat x100 for this test on the PR temporarily.

**Comment by Kelvinrr** [comment]
Specifically, adding the ctest command `ctest -R <bandnorm test> --repeat-until-fail <n>` and letting a Jenkins job run once.

**Comment by tgiroux** [comment]
^ Think that'll work? I haven't messed with the Jenkinsfile before.

**Comment by Kelvinrr** [comment]
@tgiroux  Looks right to me, as Jenkins hasn't triggered yet, I would put it first before unit tests so we can know sooner

**Review by Kelvinrr — DISMISSED** [review]
[Good enough for me](https://astroservices.usgs.gov/jenkins/job/USGS-Astrogeology/job/ISIS3/job/PR-4501/5/execution/node/94/log/)

**Comment by Kelvinrr** [comment]
@tgiroux Maybe approved a bit early, we know this is good but should remove the bandnorm repeat then we can merge.

**Review by Kelvinrr — APPROVED** [review]

**Pull request merged**
