### PR TITLE
WIP requiring python 3.7.11 or newer

### PR DESCRIPTION
**Pull request by AndrewAnnex**
naive first steps towards bumping the Python version in ISIS to 3.7.11
I do not expect this PR to build successfully or to be merged so consider it a WIP to gather information on what is actually needed to increase the minimum python version in isis through failed build logs.

# Task List

Most of the tasks for this PR involve transitioning ISIS from using ASC maintained feedstocks to those on the conda forge. 
For the most part this requires specifying newer versions of dependencies that are available on conda-forge, but some feedstocks from https://github.com/USGS-Astrogeology/isis3_dependencies/ may have to be submitted as-is to the conda-forge staged-recipes project. Mostly this involves updating the yaml files to specify to use the conda-forge channel for each dependency and to avoid the defaults channel. 

Kakadu can't be moved to conda-forge, but since it doesn't depend on much/anything likely no action is needed.

Given that conda-forge is using a much more modern version of GCC than v4, it may cause some issues simultaneously supporting older centos versions. 

- [x] TNT
  - [x] add TNT to conda forge https://github.com/conda-forge/tnt-feedstock
  - [x] add ASC maintainer
- [x] JAMA
  - [x] add JAMA to conda forge  https://github.com/conda-forge/jama-feedstock
  - [x] add ASC maintainer
- [x] GMM 
  - [x] add GMM to conda forge https://github.com/conda-forge/gmm-feedstock
  - [x] add ASC maintainer
- [ ] Bullet
  - [ ] @KrisBecker's PR to patch/refactor bullet usage in ISIS
  - [ ] make bullet build variant with Double Precision https://github.com/conda-forge/bullet-feedstock/issues/39  
  - [ ] add ASC maintainer
- [ ] OpenCV
  - [ ] upgrade to version 3.4.7 should be modern enough for python versions younger than 3.6
- [ ] embree
  - [ ] switch to conda-forge
- [ ] qhull
  - [ ] switch to conda-forge
- [ ] qt 
  - [ ] switch to conda-forge
- [ ] qwt
  - [ ] switch to conda-forge
- [ ] xerces-c
  - [ ] switch to conda-forge
- [ ] x264
  - [ ] update to newer build on conda-forge
- [ ] jpeg
  - [ ] update to newer build on conda-forge 

## Description
add python as an explicit dependency in as many yaml files as I could find

## Related Issue
#3885 

## How Has This Been Tested?
not tested because of boost issues and lack of publicly accessible test data

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Documentation change (update to the documentation; no code change)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] I have read and agree to abide by the [Code of Conduct](https://github.com/USGS-Astrogeology/ISIS3/blob/dev/Code-Of-Conduct.md)
- [x] I have read the [**CONTRIBUTING**](https://github.com/USGS-Astrogeology/ISIS3/blob/dev/CONTRIBUTING.md) document.
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [x] I have added myself to the [.zenodo.json](https://github.com/USGS-Astrogeology/ISIS3/blob/dev/.zenodo.json) document.
- [ ] I have added any user impacting changes to the [CHANGELOG.md](https://github.com/USGS-Astrogeology/ISIS3/blob/dev/CHANGELOG.md) document.

## Licensing
This project is mostly composed of free and unencumbered software released into the public domain, and we are unlikely to accept contributions that are not also released into the public domain. Somewhere near the top of each file should have these words:

> This work is free and unencumbered software released into the public domain. In jurisdictions that recognize copyright laws, the author or authors of this software dedicate any and all copyright interest in the software to the public domain.

- [x] I dedicate any and all copyright interest in this software to the public domain. I make this dedication for the benefit of the public at large and to the detriment of my heirs and successors. I intend this dedication to be an overt act of relinquishment in perpetuity of all present and future rights to this software under copyright law.

### CODE REVIEW

**Comment by AndrewAnnex** [comment]
In reality, a better target for this pr would be 3.8 not 3.7

**Comment by AndrewAnnex** [comment]
so I might be reading the console wrong, but is it an issue with x264?

"UnsatisfiableError: The following specifications were found to be incompatible with a past
explicit spec that is not an explicit spec in this operation (x264):"

**Comment by AndrewAnnex** [comment]
looks like conda-forge qhull 2015.2 is equivalent to usgs-astrogeology qhull 7.2.0 https://github.com/conda-forge/qhull-feedstock/blob/7767bb3128b6a9f8aaf377bbabaf66fabb873f94/recipe/meta.yaml

**Comment by AndrewAnnex** [comment]
pcl 1.8.1 is also on conda forge

**Comment by AndrewAnnex** [comment]
to help migrate things more to conda-forge the following feedstock repos were made:
1. https://github.com/conda-forge/staged-recipes/pull/15584
2. https://github.com/conda-forge/staged-recipes/pull/15585
3. https://github.com/conda-forge/staged-recipes/pull/15587

in the end, hopefully just kakadu can be hosted by usgs

**Comment by KrisBecker** [comment]
I am concerned about the use of conda-forge:bullet. ISIS has very specific requirements for the Bullet library. There are at least two major issues:

1. Bullet must be built with double precision and that requires a specific cmake flag setting, since it is [not turned on](https://github.com/bulletphysics/bullet3/blob/0e124cb2f103c40de4afac6c100b7e8e1f5d9e15/CMakeLists.txt#L26) by default. As best I can tell from the Anaconda [conda-forge/bullet-feedstock](https://github.com/conda-forge/bullet-feedstock), it does not explicitly turn on double precision in its [build script](https://github.com/conda-forge/bullet-feedstock/blob/master/recipe/build_cpp.sh) that executes cmake. This is required due to precision issues with single precision ray tracing on NAIF DSKs and OBJ shape models. This requirement is manifested in the [IsisBullet.h](https://github.com/USGS-Astrogeology/ISIS3/blob/dev/isis/src/base/objs/BulletShapeModel/IsisBullet.h) file.
2. The amount of data that Bullet can store in any single body part of the triangle mesh has been modified in the Bullet environment. There is a [patch](https://github.com/jessemapel/isis3_dependencies/blob/master/recipes/bullet/0001-max-num-parts-in-bits.patch) that is applied in the USGS/Astro [build specs](https://github.com/USGS-Astrogeology/isis3_dependencies/blob/master/recipes/bullet/build.sh), which also shows how Bullet is built for ISIS. Note the flag for double precision.

I don't believe we can use the conda-forge:bullet version as is, without creating an additional Bullet package expressly built with double precision.

The body part issue requires a fundamental code change to ISIS in order to support the configuration as provided by conda-forge:bullet. Our OREX/ISIS version has addressed this problem, albeit with a hefty overhaul of how Bullet is used in ISIS.

Thanks...

**Comment by AndrewAnnex** [comment]
Thanks Kris that’s very interesting, by making this PR I am hoping to uncover issues like this. I think it is possible to fork the existing conda forge bullet feedstock and add the patch and differing cmake flags into the recipe, but maybe it is worth opening an issue on the existing feedstock to see if there is a better solution. -edit- just found https://github.com/jessemapel/isis3_dependencies so this portion of my comment was incorrect

-Andrew Annex

**Comment by jlaura** [comment]
@AndrewAnnex Your work so far looks awesome. I am hoping to have some dev time later this summer (August / September timeframe) to get some more folks working on this. Please keep documenting and hopefully we can get you a dedicated assist as needed in a few more week.

I really appreciate the work you are doing on this!

**Comment by AndrewAnnex** [comment]
So I was a bit curious and I *think* that the recipe for bullet can be incorporated into the existing conda-forge bullet feedstock via the build variant mechanism in the conda-build documentation. Those docs are a bit sparse for me, but I think that the VTK-feedstock https://github.com/conda-forge/vtk-feedstock/tree/master/recipe may demonstrate an example of this working "in the wild" for the conda-forge. As I currently understand it, it would require adding some form of environment variable flag conda_build_config.yaml to the recipe and updating the recipe to check for the flag to apply the patch and in the build.sh file to add the cmake flag or not. I am not sure how accepted specialized build variants are in the conda-forge, I suppose there isn't a way to set the num_bits variable at runtime instead of via a patch?

**Comment by KrisBecker** [comment]
There is no mechanism to alter MAX_NUM_PARTS_IN_BITS at runtime. This sets a macro that is used directly in the Bullet API.

While your proposal looks great, I am not at all advocating for this patch to be applied anywhere outside of ISIS. It is a very ISIS specific workaround to simplify the implementation at the time. And I am almost certain it would break lots of other code out there if developers were to pull this patched version. It essentially dramatically reduces the number of distinct parts/body from 1024 (max triangles/part=2097152) to 16 (max triangles/part=134217728 )! We have used multiple very high resolution shape models per ISIS cube file with more that 4 million triangles/facets each that uses the unpatched, double precision version of Bullet.

I think the best thing to do would be to only provide a Bullet version built with double precision (maybe called bullet-double) and fix ISIS to use that version without the parts restriction.

**Comment by AndrewAnnex** [comment]
@KrisBecker , okay I mis interpreted your earlier message, so you are saying that patch really isn't needed anymore and only the double precision cmake flag is needed? If so that makes my idea, assuming it can work, much more appealing.

**Comment by KrisBecker** [comment]
The patch is still required until the ISIS/Bullet implementation is modified to adhere to the max triangles/part spec as configured in the Bullet distribution. That fix does not currently exist in the public version, but has been addressed in changes I have made but not submitted yet. 

After that is fixed, then the only requirement is for Bullet to be built with double precision.

**Comment by AndrewAnnex** [comment]
okay that makes sense

**Comment by AndrewAnnex** [comment]
with addition of https://github.com/conda-forge/jama-feedstock, https://github.com/conda-forge/tnt-feedstock, and soon-to-be https://github.com/conda-forge/gmm-feedstock, progress is being made. Likely no changes are needed to the existing conda yamls to take advantage of them, although the channel priority may cause the USGS conda cloud versions to be used instead

@jessemapel @jlaura if we can get 2 ASC devs to volunteer as maintainers for these feedstocks via https://conda-forge.org/docs/maintainer/updating_pkgs.html#updating-the-maintainer-list that would make it easier for ASC to update those feedstocks going forward

**Comment by jlaura** [comment]
@AndrewAnnex :+1: Nice work! I think we can get some ASC devs to help support by being maintainers on these.

**Comment by AndrewAnnex** [comment]
@jlaura the GMM feedstock has been merged into the staged-recipes for conda-forge as of 20 minutes ago, so that feedstock should be available soon. The sooner additional ASC devs can volunteer to help maintain these projects via the conda-forge mechanisms the better.

I think the next step will be to work with the bullet feedstock to add a build variant for the double precision cmake flag, at the same time @KrisBecker's update to ISIS could be turned into a PR. There maybe a stage where the usgs-astrogeology feedstock would need to be updated to remove the patch for bullet before a full transition to the conda forge bullet can happen. 

I will probably also update this pr's first post to include a checklist of the version updates/migrations to conda forge that remain. The biggest remaining one IIRC is opencv

**Comment by jlaura** [comment]
@AndrewAnnex We likely have 1+ folks that will be looking at this this week. Do you think you will have time to update the first post with a tabular view of the current status? That will help get coordinated the most I suspect.

**Comment by AndrewAnnex** [comment]
@jlaura I added a quick checklist, if you actually need a table that should be enough to start from

**Comment by jessemapel** [comment]
@AndrewAnnex I've put in to be a maintainer on these feedstocks. These are very stable packages and I do not expect it to be much work.

**Comment by jessemapel** [comment]
Moving to a newer OpenCV version will be tricky because findfeatures links against the algorithms served by OpenCV2 and there has been significant change in that set. So, we would have to either: move to a more plugin style algorithm setup or just update the algorithms everytime we change OpenCV and the set of algorithms changes.

**Comment by AndrewAnnex** [comment]
@jessemapel maybe it would be worth creating a new issue specifically about the opencv question that just links back to this PR to keep track of it. Version 3.4.15 maybe a better target for a long-term release support but I don't see that release provided on the conda-forge. Opencv release notes imply version 5 isn't that far away either.

**Comment by acpaquette** [comment]
@AndrewAnnex I have a [branch](https://github.com/acpaquette/ISIS3/tree/dev) up that has the majority of these updates for just the `environment.yml`. Should I PR this into your branch that this PR is attached to or should I just open a new PR? 

There are some issues holding back the CentOS build environment from matching the `environment.yml` file. Some of those issues I will talk about on #3566

**Comment by AndrewAnnex** [comment]
@acpaquette you should open a new PR to supersede this one. Once it is up I will close this pr and we can continue posting progress to that PR instead going forward

**Comment by acpaquette** [comment]
@AndrewAnnex PR is up! This should be good to close

**Comment by AndrewAnnex** [comment]
closing in favor of #4634

**Pull request closed without merging**
