### PR TITLE
Thm2isis App and Test Update

### PR DESCRIPTION
**Pull request by acpaquette**
App conversion for thm2isis and test conversion to gtests

## Description
Updates the thm2isis app format and converts all existing make tests into gtests.

## Related Issue
N/A

## Motivation and Context
For the push to convert apps and gtests. Also reduces overall test data footprint.

## How Has This Been Tested?
These are tests.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation change (update to the documentation; no code change)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] I have read and agree to abide by the [Code of Conduct](https://github.com/USGS-Astrogeology/ISIS3/blob/dev/Code-Of-Conduct.md)
- [x] I have read the [**CONTRIBUTING**](https://github.com/USGS-Astrogeology/ISIS3/blob/dev/CONTRIBUTING.md) document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [x] I have added myself to the [.zenodo.json](https://github.com/USGS-Astrogeology/ISIS3/blob/dev/.zenodo.json) document.
- [x] I have added any user impacting changes to the [CHANGELOG.md](https://github.com/USGS-Astrogeology/ISIS3/blob/dev/CHANGELOG.md) document.

## Licensing
This project is mostly composed of free and unencumbered software released into the public domain, and we are unlikely to accept contributions that are not also released into the public domain. Somewhere near the top of each file should have these words:

> This work is free and unencumbered software released into the public domain. In jurisdictions that recognize copyright laws, the author or authors of this software dedicate any and all copyright interest in the software to the public domain.

- [x] I dedicate any and all copyright interest in this software to the public domain. I make this dedication for the benefit of the public at large and to the detriment of my heirs and successors. I intend this dedication to be an overt act of relinquishment in perpetuity of all present and future rights to this software under copyright law.

### CODE REVIEW

**Review by AustinSanders — DISMISSED** [review]
This looks good to go.  One question about the original test though, it looks like one of the original test cases explicitly set the data type of the output cub to 32 bits, but it looks like they're being set to 32 bit (real) by default anyway.  Am I missing something?

**Comment by acpaquette** [comment]
@AustinSanders I am unsure exactly why the 32bit was being set. In looking into this and running the thm2isis with different bit type outputs set (`+8bit` and `+16bit`) the app is not propagating the bit types correctly

**Review by AustinSanders — DISMISSED** [review]
I've tested the original thm2isis app, and it seems like it's also not converting the bit type properly.  Since this isn't a new bug, my vote is to merge this and write up an issue.

**Comment by Kelvinrr** [comment]
I think if we get this updated to only have the cropping notebook, this can get merged.

**Comment by acpaquette** [comment]
@Kelvinrr This should be good to go now! Doesn't have to go in right now but it should be ready whenever

**Review by Kelvinrr — APPROVED** [review]
Sweet, this looks good.

**Pull request merged**
