### PR TITLE
Port #3910 to 4.1

### PR DESCRIPTION
**Pull request by jessemapel**
## Description

#3910 was made after isis2ascii was ported to the new app format so I had to hand patch over the changes.

## Related Issue

#3859 

## Motivation and Context

ISIS 4.1.1 release prep

## How Has This Been Tested?

All tests passed on Ubuntu 18 and isis2ascii tests passed on MAC OS 10.13

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation change (update to the documentation; no code change)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] I have read and agree to abide by the [Code of Conduct](https://usgs-astrogeology.github.io/code/)
- [x] I have read the [**CONTRIBUTING**](https://github.com/USGS-Astrogeology/ISIS3/blob/dev/CONTRIBUTING.md) document.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

## Licensing
This project is mostly composed of free and unencumbered software released into the public domain, and we are unlikely to accept contributions that are not also released into the public domain. Somewhere near the top of each file should have these words:

> This work is free and unencumbered software released into the public domain. In jurisdictions that recognize copyright laws, the author or authors of this software dedicate any and all copyright interest in the software to the public domain.

- [x] I dedicate any and all copyright interest in this software to the public domain. I make this dedication for the benefit of the public at large and to the detriment of my heirs and successors. I intend this dedication to be an overt act of relinquishment in perpetuity of all present and future rights to this software under copyright law.

### CODE REVIEW

**Comment by Kelvinrr** [comment]
Seems to be missing this change? 

https://github.com/USGS-Astrogeology/ISIS3/pull/3910/files#diff-8ab20d05d5e237bbcce67b03a3e4d432R92-R98

**Comment by jessemapel** [comment]
@Kelvinrr That change isn't in here because the header change from #3903 was purposefully left out.

**Review by Kelvinrr — APPROVED** [review]
I'd feel more comfortable if @acpaquette also gives his input but it looks good to me.

**Review by acpaquette — APPROVED** [review]
@jessemapel Looks good!

**Pull request merged**
