### PR TITLE
Update date and other metadata in CMakeLists.txt

### PR DESCRIPTION
**Pull request by krlberry**
## Description
Update date and other metadata in CMakeLists.txt for 3.7.1 release. 

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Documentation change (update to the documentation; no code change)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] I have read and agree to abide by the [Code of Conduct](https://usgs-astrogeology.github.io/code/)
- [x] I have read the [**CONTRIBUTING**](https://github.com/USGS-Astrogeology/ISIS3/blob/dev/CONTRIBUTING.md) document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

## Licensing
This project is mostly composed of free and unencumbered software released into the public domain, and we are unlikely to accept contributions that are not also released into the public domain. Somewhere near the top of each file should have these words:

> This work is free and unencumbered software released into the public domain. In jurisdictions that recognize copyright laws, the author or authors of this software dedicate any and all copyright interest in the software to the public domain.

- [x] I dedicate any and all copyright interest in this software to the public domain. I make this dedication for the benefit of the public at large and to the detriment of my heirs and successors. I intend this dedication to be an overt act of relinquishment in perpetuity of all present and future rights to this software under copyright law.

### CODE REVIEW

**Review by jlaura — COMMENTED** [review]
This looks fine. One question though, do we want this information going into dev? or should this be PRed into the 3.7.1 branch - dev is never a stable release; a branch/tag might be pulled off dev and called stable, but that is slightly different.

**Comment by jessemapel** [comment]
I could see keeping dev as "alpha" and the release branches be "stable". Then, when we pull the RC off for the next minor version change dev to "beta"

**Comment by jlaura** [comment]
Can we get the release docs updated as well.

**Comment by jessemapel** [comment]
@jlaura Make an issue for that and merge this PR?

**Comment by jlaura** [comment]
@jessemapel I think that this PR has to aim into 3.7.x branch? Then we can merge.

**Comment by jessemapel** [comment]
@jlaura yes!

**Comment by jlaura** [comment]
@kberryUSGS Can you update the branch that this PR is seeking to merge into? Then we can merge it. Thanks!

**Comment by krlberry** [comment]
@jlaura Yes, and apologies for not noticing this earlier (I'd thought this was already merged.) The date also needs to be updated again--there were some problems with the prog26/mac build yesterday that delayed this, so I'll update the date and the branch.

**Pull request merged**
