### PR TITLE
Add sensor model support for Calibrated VIRTIS_M_IR and VIRTIS_M_VIS images to ISIS 

### PR DESCRIPTION
**Pull request by krlberry**
## Description
This PR contains the work done on the Rosetta project to support VIRTIS during FY2018.

These updates allow one to `rosvirtis2isis`, `spiceinit`, and run other applications (i.e. cam2map) on calibrated VIRTIS-M images. The updated camera model has good pointing for calibrated (level 3) VIRTIS_M_IR and VIRTIS_M_VIS images.

This PR adds camera model support for only calibrated (level 3) VIRTIS-M (VIS and IR) images. Uncalibrated images (level 2) and VIRTIS-H are not supported. This is significant as the current version of Rosetta software in ISIS does not have a working camera model.

## Related Issues
https://isis.astrogeology.usgs.gov/fixit/issues/5420
https://isis.astrogeology.usgs.gov/fixit/issues/5398
#646 

## Motivation and Context
Previously, VIRTIS images were unable to be used in ISIS3 with applications that required a working sensor model.

## How Has This Been Tested?

To test that it is possible to ingest and spiceinit without error: By running rosvirtis2isis and spiceinit on a significant subset of the available calibrated VIRTIS imagery. 
To test the pointing: By running phocube to get the local incidence angle from the DEM associated with an image and comparing how well surface features in the image and the local incidence angle backplane line up. See the screenshots below for a representative example of each of VIRTIS-M_VIS and VIRTIS-M_IR.

## Screenshots (if appropriate):
Example of VIRTIS_M_IR : 

VIRTIS-M-IR, Level 3 (calibrated):
I1_00382172310.CAL (STP042)
Using the ROS_CG_K050_OSPGDLR_U_V1.BDS DSK
VIRTIS_M_IR
R/B = DNs
G = DKS's emission angle ("where ISIS thinks the comet is")

Example of VIRTIS_M_VIS: 

VIRTIS-M-VIS, Level 3 (calibrated):
V1_00388238556.CAL (STP052)
Using the ROS_CG_K050_OSPGDLR_U_V1.BDS DSK
V1
R/B = DNs
G = DKS's emission angle ("where ISIS thinks the comet is")

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Documentation change (update to the documentation; no code change)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] I have read and agree to abide by the [Code of Conduct](https://usgs-astrogeology.github.io/code/)
- [x] I have read the [**CONTRIBUTING**](https://github.com/USGS-Astrogeology/ISIS3/blob/dev/CONTRIBUTING.md) document.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

## Licensing
This project is mostly composed of free and unencumbered software released into the public domain, and we are unlikely to accept contributions that are not also released into the public domain. Somewhere near the top of each file should have these words:

> This work is free and unencumbered software released into the public domain. In jurisdictions that recognize copyright laws, the author or authors of this software dedicate any and all copyright interest in the software to the public domain.

- [x] I dedicate any and all copyright interest in this software to the public domain. I make this dedication for the benefit of the public at large and to the detriment of my heirs and successors. I intend this dedication to be an overt act of relinquishment in perpetuity of all present and future rights to this software under copyright law.

### CODE REVIEW

**Comment by jlaura** [comment]
@kberryUSGS Who would it make sense to do the review on this?

**Comment by jessemapel** [comment]
@kberryUSGS  As this is a merge from the virits branch, I'm going to close this until the virits branch is cleaned up.

**Comment by krlberry** [comment]
Can this get merged as-is? I updated the comment to indicate that this provides good calibrated VIRTIS_M_IR support ONLY.

**Comment by jlaura** [comment]
@kberryUSGS I would rather not push this in the Friday before a conference without more review. This is a prime candidate to get finished in the next support sprint. (August)

**Comment by krlberry** [comment]
@jlaura :+1: on not pushing this right before the conference. Does this mean that would be available in the next ISIS release or in the one after? (If it's the one after I need to communicate the date to Tim.)

**Comment by jlaura** [comment]
Likely the one after unless someone is able to review this before July 1. So the best thing Tim could say would be coming in either 3.8 or 3.9.

**Comment by krlberry** [comment]
(The most recent change to fix VIRTIS-M-VIS's pointing was in an associated data file, not in the code on here.)

**Review by scsides — APPROVED** [review]
The changes to ISIS look safe, other changes to the camera model only fix known issues. I see no reason to not merge this

**Comment by jessemapel** [comment]
I am fine with merging this and if there is an issue we have somehow missed we can pull it during the RFC.

**Pull request merged**
