### PR TITLE
8.1.0_RC2 Updates

### PR DESCRIPTION
**Pull request by chkim-usgs**
## Description

Updating `dev` to introduce upcoming 8.1.0_RC2 release, will cherry-pick this commit into `8.1` branch after merge and will cut a release from there.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation change (update to the documentation; no code change)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Infrastructure change (changes to things like CI or the build system that do not impact users)

## Checklist:

- [x] I have read and agree to abide by the [Code of Conduct](https://github.com/USGS-Astrogeology/ISIS3/blob/dev/Code-Of-Conduct.md)
- [x] I have read the [**CONTRIBUTING**](https://github.com/USGS-Astrogeology/ISIS3/blob/dev/CONTRIBUTING.md) document.
- [ ] My change requires a change to the documentation and I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] I have added myself to the [.zenodo.json](https://github.com/USGS-Astrogeology/ISIS3/blob/dev/.zenodo.json) document.
- [x] I have added my user impacting change to the [CHANGELOG.md](https://github.com/USGS-Astrogeology/ISIS3/blob/dev/CHANGELOG.md) document. 

## Licensing
This project is mostly composed of free and unencumbered software released into the public domain, and we are unlikely to accept contributions that are not also released into the public domain. Somewhere near the top of each file should have these words:

> This work is free and unencumbered software released into the public domain. In jurisdictions that recognize copyright laws, the author or authors of this software dedicate any and all copyright interest in the software to the public domain.

- [x] I dedicate any and all copyright interest in this software to the public domain. I make this dedication for the benefit of the public at large and to the detriment of my heirs and successors. I intend this dedication to be an overt act of relinquishment in perpetuity of all present and future rights to this software under copyright law.

### CODE REVIEW

**Comment by Kelvinrr** [comment]
I think this also needs the change that adds `pybindings=ON`? I don't see that anywhere on the changelogs. Looking at the PR, it seems we missed it, so maybe add it here?

**Comment by chkim-usgs** [comment]
@Kelvinrr Yes, looks like the changelog was not updated to show the pybindings change (https://github.com/DOI-USGS/ISIS3/pull/5389). Just added a changelog entry.

**Comment by acpaquette** [comment]
We may want to bump ALE to 0.10.0 here and in the 8.1 branch

**Comment by chkim-usgs** [comment]
@acpaquette Once this PR gets merged, I'll cherry pick the PR merge commit into the release prep PR all the changes in this PR get into the `8.1` branch.

**Comment by acpaquette** [comment]
@chkim-usgs Merged another PR that was ready to go and it messed with the changelog. Just need to fix conflicts and this should be good

**Review by acpaquette — APPROVED** [review]

**Pull request merged**
