### PR TITLE
Updates qmos to fix grid-drawing if LongitudeDirection is PositiveWest

### LINKED ISSUE #2696: qmos - grid hangs when LongitudeDirection=PositiveWest
---

Author Name: **Lynn Weller** (Lynn Weller)

---

Working under isis3beta2018-09-18, but does not appear to be a new bug as it exits under old OS isis3production2016-11-22.
Test data under /work/users/lweller/Isis3Tests/Qmos/LonDirection/

Open qmos and load 2 supplied images from test directory
use quick map to select Enc_MeanR_PosEast360_100m_NP.map - footprints reproject
select grid icon - grid is placed on footprints
unselect Show Grid - grid goes away
use quick map load to select Enc_MeanR_PosWest360_100m.map - footprints reproject
select Show Grid (may need to select grid tool if not selected/enabled in icon menu)

program hangs and grid never created
have to kill application even after forcing a close by clicking on window x

qmos seems to understand longitude direction in general, but grid doesn't know what to do with it

### PR DESCRIPTION
**Pull request by krlberry**
Updated qmos to successfully draw a grid, rather than hanging indefinitely when `LongitudeDirection` is set to `PositiveWest` in the map file used..

Fixes #2696 

## Description
The changed file was just updated to swap the mix/max Longitudes when LongitudeDirection is set to PositiveWest in the class used by qmos to draw grids.

## Related Issue
#2696 

## How Has This Been Tested?
This has been tested by-hand on Lynn's test case provided in #2696. No automated tests are available for this part of ISIS. 

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation change (update to the documentation; no code change)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] I have read and agree to abide by the [Code of Conduct](https://usgs-astrogeology.github.io/code/)
- [x] I have read the [**CONTRIBUTING**](https://github.com/USGS-Astrogeology/ISIS3/blob/dev/CONTRIBUTING.md) document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

## Licensing
This project is mostly composed of free and unencumbered software released into the public domain, and we are unlikely to accept contributions that are not also released into the public domain. Somewhere near the top of each file should have these words:

> This work is free and unencumbered software released into the public domain. In jurisdictions that recognize copyright laws, the author or authors of this software dedicate any and all copyright interest in the software to the public domain.

- [x] I dedicate any and all copyright interest in this software to the public domain. I make this dedication for the benefit of the public at large and to the detriment of my heirs and successors. I intend this dedication to be an overt act of relinquishment in perpetuity of all present and future rights to this software under copyright law.

### CODE REVIEW

**Comment by jessemapel** [comment]
Is this a functional change to qmos in that we are no longer supporting wrapping in qmos for positive west longitudes?

**Comment by Kelvinrr** [comment]
What do you mean? It's still wrapping, it seems more like the original code wasn't accounting adjusting min/max based on longitude direction.

**Review by jessemapel — APPROVED** [review]

**Comment by jessemapel** [comment]
Are we running qmos through some other tests or can this just be merged now?

**Comment by Kelvinrr** [comment]
Not really sure how we can test this further. Do we have a testing process for GUIs outside of waiting until the RC is in user's hands? If not, should be mergeable now.

**Comment by jessemapel** [comment]
I think Ethan had some tests he did for qmos, I'll go ask him.

**Comment by jessemapel** [comment]
Ethan said he didn't have any tests for qmos so this is good to go.

This will also need to be PR'd into the 3.8 branch now.

**Pull request merged**
