### PR TITLE
Removed unneeded LineEquation includes

### PR DESCRIPTION
**Pull request by krlberry**
Removed unneeded LineEquation.h includes. Noticed that they were no longer used while looking for good unit tests to convert.

### CODE REVIEW

**Comment by jessemapel** [comment]
Can this go onto dev?

**Comment by krlberry** [comment]
Sure.

**Comment by krlberry** [comment]
Oops, let me fix this so it can actually go into dev.

**Comment by krlberry** [comment]
@jessemapel See: PR #580

**Pull request closed without merging**
