### PR TITLE
Update LRO appdata

### PR DESCRIPTION
**Pull request by scsides**
Initial commits for moving lro small files out of ISISDATA and into git
## Description
Initial commits for moving lro small files out of ISISDATA and into git

## Motivation and Context
RFC4

## How Has This Been Tested?
NOTE: Many tests are still failing. Each mission is being converted and PRed separately. When base is PRed many tests will start working. Leftovers will be fixed one at time

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Documentation change (update to the documentation; no code change)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] I have read and agree to abide by the [Code of Conduct](https://usgs-astrogeology.github.io/code/)
- [ ] I have read the [**CONTRIBUTING**](https://github.com/USGS-Astrogeology/ISIS3/blob/dev/CONTRIBUTING.md) document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

## Licensing
This project is mostly composed of free and unencumbered software released into the public domain, and we are unlikely to accept contributions that are not also released into the public domain. Somewhere near the top of each file should have these words:

> This work is free and unencumbered software released into the public domain. In jurisdictions that recognize copyright laws, the author or authors of this software dedicate any and all copyright interest in the software to the public domain.

- [X] I dedicate any and all copyright interest in this software to the public domain. I make this dedication for the benefit of the public at large and to the detriment of my heirs and successors. I intend this dedication to be an overt act of relinquishment in perpetuity of all present and future rights to this software under copyright law.

### CODE REVIEW

**Review by KrisBecker — COMMENTED** [review]
I am a bit concerned to see absolute paths using $ISISROOT being used here. This appears to be heading in the same direction as our current ISIS3DATA->ISISDATA issue.

What was nice about the relative translation file scheme was that you had more control over isolating/insulating your work using a local IsisPreferences configuration. Looks like this option is being abandoned?

**Comment by jessemapel** [comment]
The ability to change your translation files and such is still available, just instead of having to specify a different data directory, you change the files in your source tree the same way you would change the code.

I can definitely see us having to make all of these changes again if we change the package name. Would it be worth putting some sort of function to get the build root and have that access ISISROOT? That way if we change the ISISROOT variable it's only a change in 1 place instead of having to change all of these again?

**Comment by krlberry** [comment]
This looks like a good addition to the discussion about this work on issue #3727 that shouldn't get lost when this PR is closed, since this comment is about what we're doing in general and applies to multiple PRs. @KrisBecker @jessemapel  could you move your comments on this PR to the issue at #3727?

**Comment by KrisBecker** [comment]
@jessemapel...

> The ability to change your translation files and such is still available, just instead of having to specify a different data directory, you change the files in your source tree the same way you would change the code.

On more than one occasion, I have used IsisPreferences for testing problems in a live, running system with minimal changes and without the need to completely copy the system elsewhere or directly alter any system file in the running tree. This can change the environment just enough so that the behavior you are testing cannot be reproduced. This PR does not preserve this capability.

**Comment by jessemapel** [comment]
@krisbecker Can you provide a more specific example of the functionality you are concerned about?

**Comment by KrisBecker** [comment]
@jessemapel you have two examples in the current [IsisPreferences ](https://github.com/USGS-Astrogeology/ISIS3/blob/dev/isis/IsisPreferences) file in the repo. The Clipper and Osirisrex data directories show a path outside the shipped directory structure. 

```
Clipper      = $ISIS3DATA/../datalocal/clipper
OsirisRex    = $ISIS3DATA/../datalocal/osirisrex
```
How is it possible to isolate translation files in the source tree and not ship them prematurely?

**Comment by scsides** [comment]
@KrisBecker @jessemapel, This discussion seems related to every PR that is or will be part of this branch. It is important to capture all of these comments in the related issue. Can we please move this over to the issue?  #3727

**Review by krlberry — APPROVED** [review]
:+1: Looks good to me.

**Pull request merged**
