### PR TITLE
Old build system working alongside cmake

### PR DESCRIPTION
**Pull request by jessemapel**
The top level and 3rdParty Makefiles got removed when it was planned that cmake would just replace the old system. Adding CMakeLists.txt to the src Makefile filter allows for building and testing with the old make system. Hyper can build but not test for right now.

### CODE REVIEW

**Comment by jessemapel** [comment]
[The cmake system needs to be able to work with the old make system (for now)](https://trello.com/c/zLVW7Vzr/98-the-cmake-system-needs-to-be-able-to-work-with-the-old-make-system-for-now)

**Review by celbal — COMMENTED** [review]
Have you tested making cmake with this build system as well?

**Comment by jessemapel** [comment]
@makaylas I was able to build with cmake on fedora25 without conflict.

**Comment by Kelvinrr** [comment]
Since we decided that the CMake system is no longer going to be backwards compatible with v00X libraries, this PR isn't needed anymore.

**Pull request closed without merging**
