### PR TITLE
Remove old doc pages

### PR DESCRIPTION
**Pull request by amystamile-usgs**
## Description

Removes:
- docs that have already been transferred to astrogeology.usgs.gov/docs
- docs that are no longer needed/relevant

The follow pages have not been removed and waiting to be transferred to new docs site:
- https://github.com/DOI-USGS/asc-public-docs/issues/53
- https://github.com/DOI-USGS/asc-public-docs/issues/54
- IsisHistory (Move to Drupal page?)
- https://github.com/DOI-USGS/asc-public-docs/issues/55
- https://github.com/DOI-USGS/asc-public-docs/issues/56
- https://github.com/DOI-USGS/asc-public-docs/issues/57
- https://github.com/DOI-USGS/asc-public-docs/issues/58

All the pages being removed will still exist on older versions of the isis docs.

## Related Issue

https://github.com/DOI-USGS/asc-public-docs/issues/50

## How Has This Been Validated?

ran `ninja docs` and tested website locally

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Documentation change (update to the documentation; no code change)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Infrastructure change (changes to things like CI or the build system that do not impact users)

## Checklist:

- [x] I have read and agree to abide by the [Code of Conduct](https://github.com/USGS-Astrogeology/ISIS3/blob/dev/Code-Of-Conduct.md)
- [x] I have read the [**CONTRIBUTING**](https://github.com/USGS-Astrogeology/ISIS3/blob/dev/CONTRIBUTING.md) document.
- [x] My change requires a change to the documentation and I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] I have added myself to the [.zenodo.json](https://github.com/USGS-Astrogeology/ISIS3/blob/dev/.zenodo.json) document.
- [ ] I have added my user impacting change to the [CHANGELOG.md](https://github.com/USGS-Astrogeology/ISIS3/blob/dev/CHANGELOG.md) document. 

## Licensing
This project is mostly composed of free and unencumbered software released into the public domain, and we are unlikely to accept contributions that are not also released into the public domain. Somewhere near the top of each file should have these words:

> This work is free and unencumbered software released into the public domain. In jurisdictions that recognize copyright laws, the author or authors of this software dedicate any and all copyright interest in the software to the public domain.

- [x] I dedicate any and all copyright interest in this software to the public domain. I make this dedication for the benefit of the public at large and to the detriment of my heirs and successors. I intend this dedication to be an overt act of relinquishment in perpetuity of all present and future rights to this software under copyright law.

### CODE REVIEW

**Comment by amystamile-usgs** [comment]
Build started: 
https://us-west-2.console.aws.amazon.com/codesuite/codebuild/950438895271/projects/IsisCodeBuild-52nifRxFNgrA/build/IsisCodeBuild-52nifRxFNgrA%3Ac7a629be-19ca-40e5-9b3b-6f83665b25ff/?region=us-west-2

**Comment by amystamile-usgs** [comment]
Build started: https://us-west-2.console.aws.amazon.com/codesuite/codebuild/950438895271/projects/IsisCodeBuild-52nifRxFNgrA/build/IsisCodeBuild-52nifRxFNgrA%3A558eb4c8-aeff-4e67-b96c-1d61fcc3506d/?region=us-west-2

**Comment by amystamile-usgs** [comment]
Build started:
https://us-west-2.console.aws.amazon.com/codesuite/codebuild/950438895271/projects/IsisCodeBuild-52nifRxFNgrA/build/IsisCodeBuild-52nifRxFNgrA%3A558eb4c8-aeff-4e67-b96c-1d61fcc3506d/?region=us-west-2

**Comment by amystamile-usgs** [comment]
Tests passing for this PR.

**Review by Kelvinrr — APPROVED** [review]

**Pull request merged**
