### PR TITLE
Update IsisPreferences to include backwards compatibility with instances of $ISIS3DATA

### PR DESCRIPTION
**Pull request by krlberry**
## Description
Update IsisPreferences to include backwards compatibility with instances of $ISIS3DATA in cubes or preference files. 

This would be useful in cases such as: A cube was spiceinited with a dem, and the path was set as "$ISIS3DATA/base/dems/dem.cub". And was tested on this case.

## Related Issue
#3727, but deliberately left out of the big PR for that issue due to wanting to put this change in separately.

## Motivation and Context
See description.

## How Has This Been Tested?
I spiceinited a cube with a dem with `$ISIS3DATA` included in the path. Without these updates, campt on that cube fails. With these updates, it succeeds.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation change (update to the documentation; no code change)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] I have read and agree to abide by the [Code of Conduct](https://usgs-astrogeology.github.io/code/)
- [x] I have read the [**CONTRIBUTING**](https://github.com/USGS-Astrogeology/ISIS3/blob/dev/CONTRIBUTING.md) document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

## Licensing
This project is mostly composed of free and unencumbered software released into the public domain, and we are unlikely to accept contributions that are not also released into the public domain. Somewhere near the top of each file should have these words:

> This work is free and unencumbered software released into the public domain. In jurisdictions that recognize copyright laws, the author or authors of this software dedicate any and all copyright interest in the software to the public domain.

- [x] I dedicate any and all copyright interest in this software to the public domain. I make this dedication for the benefit of the public at large and to the detriment of my heirs and successors. I intend this dedication to be an overt act of relinquishment in perpetuity of all present and future rights to this software under copyright law.

### CODE REVIEW

**Comment by jessemapel** [comment]
Can you re-base this onto dev to clean up the commits.

**Review by scsides — DISMISSED** [review]

**Comment by krlberry** [comment]
@jessemapel Cleaned up the commits! Does this have any effect when we squash and merge everything, though? Or is it a "cleaner PR" type thing?

**Comment by jessemapel** [comment]
@kberryUSGS Having those extra commits won't change any code when this gets squashed, but the message in the squashed commit would say it contained all of those changes.

**Review by scsides — APPROVED** [review]

**Review by jessemapel — APPROVED** [review]
Only CI failures are vimscal and they are happening the same way in dev, so this looks good.

**Comment by krlberry** [comment]
@jessemapel Thanks! I had stopped rebasing onto dev because I didn't think that it made a difference with squash + merge. I'll go ahead and fix this for the Hayabusa2 ticket.

**Pull request merged**
