### PR TITLE
Changed installation instructions back to conda

### PR DESCRIPTION
**Pull request by jessemapel**
## Description

Changed install instructions back to conda instead of mamba.

## Related Issue

Related to #4778 

## Motivation and Context

We've had numerous use reports of issues installing with mamba that were resolved by moving back to conda.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Documentation change (update to the documentation; no code change)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] I have read and agree to abide by the [Code of Conduct](https://github.com/USGS-Astrogeology/ISIS3/blob/dev/Code-Of-Conduct.md)
- [x] I have read the [**CONTRIBUTING**](https://github.com/USGS-Astrogeology/ISIS3/blob/dev/CONTRIBUTING.md) document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [x] I have added myself to the [.zenodo.json](https://github.com/USGS-Astrogeology/ISIS3/blob/dev/.zenodo.json) document.
- [x] I have added any user impacting changes to the [CHANGELOG.md](https://github.com/USGS-Astrogeology/ISIS3/blob/dev/CHANGELOG.md) document.

## Licensing
This project is mostly composed of free and unencumbered software released into the public domain, and we are unlikely to accept contributions that are not also released into the public domain. Somewhere near the top of each file should have these words:

> This work is free and unencumbered software released into the public domain. In jurisdictions that recognize copyright laws, the author or authors of this software dedicate any and all copyright interest in the software to the public domain.

- [ ] I dedicate any and all copyright interest in this software to the public domain. I make this dedication for the benefit of the public at large and to the detriment of my heirs and successors. I intend this dedication to be an overt act of relinquishment in perpetuity of all present and future rights to this software under copyright law.

### CODE REVIEW

**Comment by jessemapel** [comment]
Added a version to the install line to help with situations like #4801

**Review by AustinSanders — APPROVED** [review]

**Comment by michaelaye** [comment]
What issues were those? Was the `channel_priority` config setting considered as a potential culprit?

**Comment by jessemapel** [comment]
We had multiple reports of mamba not being able to properly resolve the environment, primarily due to openssl. There may be a work around with channel_priority but my testing with it in the past has broken the environment worse because it makes it harder to handle our split dependency sources.

With the new environment coming in 7.0, mamba isn't as needed. I can install the 7.0 RC in just a couple minutes.

**Comment by michaelaye** [comment]
We better make sure that mamba installs work, as it is being prepared to fully replace conda, IIUC.
I started a new issue to keep track of mamba stuff: #4891

**Pull request merged**
