### PR TITLE
Re-add and refactor lrowacphomap

### PR DESCRIPTION
**Pull request by cordellmichaud**
## Description

- Re-added lrowacphomap app
- Refactored lrowacphomap app to be callable for testing
- Moved previously global variables into new callable lrowacphomap function
- Converted lrowacphomap helper functions into lambdas with captures
- Updated lrowacphomap xml file history section with changes
- Added functional tests and associated test data for lrowacphomap to validate output

## Related Issue

 #4960 

## Motivation and Context

This change enables applying photometric correction to WAC cubes with a parameter cube defining Hapke model parameters for the correction, a PVL file defining the algorithm, and an optional backplane cube.

This change also brings lrowacphomap in line with the newer testing framework for ISIS and covers the re-addition and refactoring with functional tests.

## How Has This Been Tested?

Functional tests were added to `isis/tests/FunctionalTestsLrowacphomap.cpp` to cover the re-addition by validating its output.

The app was also tested and validated by the science team at LROC.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Documentation change (update to the documentation; no code change)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] I have read and agree to abide by the [Code of Conduct](https://github.com/USGS-Astrogeology/ISIS3/blob/dev/Code-Of-Conduct.md)
- [x] I have read the [**CONTRIBUTING**](https://github.com/USGS-Astrogeology/ISIS3/blob/dev/CONTRIBUTING.md) document.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.
- [x] I have added myself to the [.zenodo.json](https://github.com/USGS-Astrogeology/ISIS3/blob/dev/.zenodo.json) document.
- [x] I have added any user impacting changes to the [CHANGELOG.md](https://github.com/USGS-Astrogeology/ISIS3/blob/dev/CHANGELOG.md) document.

## Licensing
This project is mostly composed of free and unencumbered software released into the public domain, and we are unlikely to accept contributions that are not also released into the public domain. Somewhere near the top of each file should have these words:

> This work is free and unencumbered software released into the public domain. In jurisdictions that recognize copyright laws, the author or authors of this software dedicate any and all copyright interest in the software to the public domain.

- [x] I dedicate any and all copyright interest in this software to the public domain. I make this dedication for the benefit of the public at large and to the detriment of my heirs and successors. I intend this dedication to be an overt act of relinquishment in perpetuity of all present and future rights to this software under copyright law.

### CODE REVIEW

**Comment by scsides** [comment]
Working on the review. I'll start a CI test for this as well.

**Comment by scsides** [comment]
While I'm finishing the review, you might want to check out the test failure: https://astroservices.usgs.gov/jenkins/job/USGS-Astrogeology/job/ISIS3/view/change-requests/job/PR-4961/2/execution/node/31/log/?consoleFull

Scroll to the bottom to see the error, then search for the error number, or just search for the program or test name

**Comment by cordellmichaud** [comment]
These new commits should solve the Lrowacphomap.FunctionalTestLrowacphomapNoBack failure.

**Comment by jessemapel** [comment]
The failure for 2030 - TestKernelDb.TestKernelsSmithOffset (Failed) is not from this PR so disregard for now

**Review by scsides — APPROVED** [review]
This looks good. I've started another CI build for this PR. If the tests pass then it is good to merge.

**Comment by scsides** [comment]
CI ran without errors caused by this. Merged

**Pull request merged**
