### PR TITLE
Added subwindow support to Rosetta OSIRIS camera model

### PR DESCRIPTION
**Pull request by jessemapel**
There is also a change to the IAK for the WAC that is not currently in the data area, but it resolves a different problem.

### CODE REVIEW

**Review by krlberry — APPROVED** [review]
:+1: This looks good to me!

**Comment by krlberry** [comment]
@jessemapel Can I merge this, or did you want @jcwbacker to review it as well, first? (I noticed that she's also marked as a reviewer.)

**Comment by jessemapel** [comment]
This can be merged, I just wanted one of you two to review it.

**Comment by krlberry** [comment]
@jessemapel I already merged this, but at some point could you either make a test for the subwindowing or add a card for it on Trello to remind one of us to do it?

**Comment by jessemapel** [comment]
@kberryUSGS :+1:

**Comment by jessemapel** [comment]
I'll put a PR in for that this weekend

**Pull request merged**
