### PR TITLE
Should fix #3939

### LINKED ISSUE #3939: Qview - Nomenclature tool broken
**ISIS version(s) affected**: 4.1.1 as well as older 3.x.y versions

**Description**  
Using nomenclature tool on mosaic produces an error dialog.  Can't connect to features database.

**How to reproduce**  
Open an mosaic (or unprojected data, I think) and turn on nomenclature tool (ID icon).

QviewNomenclatureError

### PR DESCRIPTION
**Pull request by evindunn**
## Description
Changes the path for planetarynames at isis/src/qisis/objs/FeatureNomenclature/FeatureNomenclature.cpp

## Related Issue
#3939 

## Motivation and Context
ISIS compatibility with QView

## How Has This Been Tested?
Not sure how to test, maybe someone has a suggestion?

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation change (update to the documentation; no code change)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [x] I have read and agree to abide by the [Code of Conduct](https://usgs-astrogeology.github.io/code/)
- [x] I have read the [**CONTRIBUTING**](https://github.com/USGS-Astrogeology/ISIS3/blob/dev/CONTRIBUTING.md) document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [x] I have added myself to the [.zenodo.json](https://github.com/USGS-Astrogeology/ISIS3/blob/dev/.zenodo.json) document.
- [ ] I have added any user impacting changes to the [CHANGELOG.md](https://github.com/USGS-Astrogeology/ISIS3/blob/dev/CHANGELOG.md) document.

## Licensing
This project is mostly composed of free and unencumbered software released into the public domain, and we are unlikely to accept contributions that are not also released into the public domain. Somewhere near the top of each file should have these words:

> This work is free and unencumbered software released into the public domain. In jurisdictions that recognize copyright laws, the author or authors of this software dedicate any and all copyright interest in the software to the public domain.

- [x] I dedicate any and all copyright interest in this software to the public domain. I make this dedication for the benefit of the public at large and to the detriment of my heirs and successors. I intend this dedication to be an overt act of relinquishment in perpetuity of all present and future rights to this software under copyright law.

### CODE REVIEW

**Comment by jessemapel** [comment]
@evindunn We can have someone do a build with this and manually check the nomenclature to test this out.

**Comment by AustinSanders** [comment]
I _think_ this is working, but I have no experience whatsoever with the nomenclature tool.   If someone can verify that this is the expected output, then the PR should be good to merge.

Screen Shot 2020-09-24 at 1 50 04 PM

**Comment by jlaura** [comment]
@AustinSanders It looks like the image is self linking back to the webpage?

**Comment by AustinSanders** [comment]
@jlaura I'm not sure what happened there.  Maybe I submitted before it finished uploading?

**Comment by jlaura** [comment]
@lwellerastro Does the screen shot above look like the expected behavior? Thanks!

**Review by jlaura — APPROVED** [review]

**Comment by lwellerastro** [comment]
@jlaura, @AustinSanders , the screen shot looks like what I would expect when the nomenclature tool is enabled.  Is it correct (is it picking up and accounting for the longitude domain of the mosaic)?  I don't know.  Someone would need to load up a mosaic with a known named feature and turn on the tool and verify.  

I see the Themis Oxia Palus tile is loaded - is Jezeero in that one?  If so, it might be worth zooming in on the crater and confirming there is a name there.

**Pull request merged**
