### PR TITLE
Added ingestion support for Kaguya TC Level 2B images. Fixes #4506

### PR DESCRIPTION
**Pull request by jcwbacker**
When merging, updated translation files and test files need to be added to the data area.

### CODE REVIEW

**Review by AgoinsUSGS — DISMISSED** [review]

**Review by ihumphrey — COMMENTED** [review]
comment

**Review by ihumphrey — APPROVED** [review]
test approve

**Comment by ihumphrey** [comment]
@jcwbacker @AgoinsUSGS is this ready to go into dev (when nightly builds are clean)?

**Comment by jlaura** [comment]
@ihumphrey-usgs @AgoinsUSGS I believe that this should go in after you have gotten the RC setup and out the door. So, merged on Wednesday or Thursday?

**Comment by ihumphrey** [comment]
@jlaura I agree this should go in after the RC, so probably Thursday

**Comment by krlberry** [comment]
@ihumphrey Can this get merged now?

**Comment by ihumphrey** [comment]
@kberryUSGS yes this should be ready, since we were just waiting on the release candidate before

**Comment by ihumphrey** [comment]
@kberryUSGS I couldn't find a ticket number for this PR though

**Comment by krlberry** [comment]
@ihumphrey You're right! Thanks for noticing the missing ticket number.

**Pull request merged**
