### PR TITLE
Added uint32 behavior to EndianSwapper. Added lsb support to ControlNetVersioner.

### PR DESCRIPTION
**Pull request by AgoinsUSGS**

### CODE REVIEW

**Comment by AgoinsUSGS** [comment]
[Make sure that point message sizes are always LSB](https://trello.com/c/uAY5Ytki/240-make-sure-that-point-message-sizes-are-always-lsb)

**Review by jessemapel — CHANGES_REQUESTED** [review]
Code all looks good. Can you add a test for this to the unitTest?

**Comment by AgoinsUSGS** [comment]
Tests for uint32 support have been added. Truthdata has been updated.
I also changed the read/write of the versioner to use this new behavior, ensuring that lsb uint32 size is written and read.

**Review by jessemapel — APPROVED** [review]
Looks good, I'm going to pull it and run a quick test, then merge it in

**Pull request merged**
