### PR TITLE
Added documentation for Spatial Plot Tool. Fixes #5281

### LINKED ISSUE #5281: PHOTOMET Won't Accept Pre-Made Backplanes
**ISIS version(s) affected**: 7.2.0

**Description**  
I am attempting to run PHOTOMET on some MARCI images with code that worked fine before in ISIS version 4.3.x and 4.4.0.  I'm using 7.2.0 now (waiting for 8.0.1 to be available with the JIGSAW fix before upgrading) and have a very weird error with PHOTOMET.  It's more efficient for MARCI processing to create the backplanes first, save them, and then use them as a reference for applying a photometric model.  However, with version 7.2.0, when I give it the file names, it says "**PROGRAMMER ERROR** Parameters [PHASE_ANGLE_FILE] is not a filename.

I have tried to use both the command-line and the GUI version with the same results.  I have also renamed the files to something more simple - and ensured they exist - and get the same results.  I verified in QVIEW that the backplanes look good.  It would appear as though somewhere between version 4 and 7, something in PHOTOMET got broken, which is weird because I do not see any changes to it in the overall ISIS changelog.

**How to reproduce**  
See above.  I have not attempted to do this with other mission data.

### PR DESCRIPTION
**Pull request by SgStapleton**
Please verify that explanation is reasonable

### CODE REVIEW

**Comment by SgStapleton** [comment]
Images can be found in /work/users/sgstapleton/qview/assets/image

**Comment by celbal** [comment]
Has the Astro Editor looked at these changes?

**Comment by SgStapleton** [comment]
Copy has been sent to Janet Richie for review

**Comment by celbal** [comment]
Has Janet reviewed these changes? If not it might be time to poke her.

**Review by celbal — APPROVED** [review]

**Pull request merged**
