### PR TITLE
Added north / south pole gtests to demprep

### PR DESCRIPTION
**Pull request by AustinSanders**
Added north/south pole gtests to demprep

## Description
Initial demprep PR was missing 2 gtests.  This PR adds those two tests.

## Related Issue
Testing

## Motivation and Context
Testing

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation change (update to the documentation; no code change)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] I have read and agree to abide by the [Code of Conduct](https://github.com/USGS-Astrogeology/ISIS3/blob/dev/Code-Of-Conduct.md)
- [x] I have read the [**CONTRIBUTING**](https://github.com/USGS-Astrogeology/ISIS3/blob/dev/CONTRIBUTING.md) document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.
- [x] I have added myself to the [.zenodo.json](https://github.com/USGS-Astrogeology/ISIS3/blob/dev/.zenodo.json) document.
- [ ] I have added any user impacting changes to the [CHANGELOG.md](https://github.com/USGS-Astrogeology/ISIS3/blob/dev/CHANGELOG.md) document.

## Licensing
This project is mostly composed of free and unencumbered software released into the public domain, and we are unlikely to accept contributions that are not also released into the public domain. Somewhere near the top of each file should have these words:

> This work is free and unencumbered software released into the public domain. In jurisdictions that recognize copyright laws, the author or authors of this software dedicate any and all copyright interest in the software to the public domain.

- [x] I dedicate any and all copyright interest in this software to the public domain. I make this dedication for the benefit of the public at large and to the detriment of my heirs and successors. I intend this dedication to be an overt act of relinquishment in perpetuity of all present and future rights to this software under copyright law.

### CODE REVIEW

**Review by acpaquette — DISMISSED** [review]
Looks good! Only thing I could think of was maybe subtracting the expected new line from the line it was copied from. So if the "top" (line 0) was copied to pad the top of the cube, you'd subtract line 1 from line 0 and expect to see all zeros from the subtraction. Then do basically the same for the "bottom"

**Comment by acpaquette** [comment]
You should rebase off of dev to remove two old commits. I would suggest doing a `git rebase -i HEAD~3`

**Comment by AustinSanders** [comment]
> You should rebase off of dev to remove two old commits. I would suggest doing a `git rebase -i HEAD~3`

I did it wrong and made it 10x worse.

**Comment by AustinSanders** [comment]
Closing because of how badly I messed up the rebase.

**Pull request closed without merging**
