### PR TITLE
Improved ControlNetVersioner code coverage

### PR DESCRIPTION
**Pull request by jessemapel**
Specifically this tests
- ControlNetVersioner(ControlNet*)
- ControlNetVersioner::CreatePoint(ControlPointV0003)
- ControlNetVersioner::CreateMeasure

Because we are expecting multiple commits to this unit test we're gonna conflict everywhere

### CODE REVIEW

**Comment by jessemapel** [comment]
[Run test coverage on versioner](https://trello.com/c/g0MPSOJa/236-run-test-coverage-on-versioner)

**Review by krlberry — APPROVED** [review]
:+1: Looks good. @jessemapel You mentioned on gitter that you might continue working on this PR if no-one merged it by this morning. Should I go ahead and merge this now, or should I hold off?

**Comment by jessemapel** [comment]
Hold off. I think I'm going to have code coverage on ControlNetVersioner done by the end of the day.

**Comment by krlberry** [comment]
:+1:

**Comment by jessemapel** [comment]
This is now ready to go. It covers a significant portion of the code. There are a handful of safety corner-case checks that are hard to test.

The main pieces of untested code are issues with some of the Pvl formatted networks. We need to generate network files with these problems in them for ControlPointV0001, ControlPointV0002, and ControlPointV0003.  So, once those are made, we'll just test against those files to exercise ControlNetVersioner.

**Review by AgoinsUSGS — APPROVED** [review]

**Pull request merged**
