### PR TITLE
Sumspice App and Test Conversions

### PR DESCRIPTION
**Pull request by amystamile-usgs**
## Description
Sumspice app conversion and tests converted to gtests

## Motivation and Context

Testing sprint

## How Has This Been Tested?

Tested with added gtests

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation change (update to the documentation; no code change)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] I have read and agree to abide by the [Code of Conduct](https://github.com/USGS-Astrogeology/ISIS3/blob/dev/Code-Of-Conduct.md)
- [x] I have read the [**CONTRIBUTING**](https://github.com/USGS-Astrogeology/ISIS3/blob/dev/CONTRIBUTING.md) document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.
- [x] I have added myself to the [.zenodo.json](https://github.com/USGS-Astrogeology/ISIS3/blob/dev/.zenodo.json) document.
- [x] I have added any user impacting changes to the [CHANGELOG.md](https://github.com/USGS-Astrogeology/ISIS3/blob/dev/CHANGELOG.md) document.

## Licensing
This project is mostly composed of free and unencumbered software released into the public domain, and we are unlikely to accept contributions that are not also released into the public domain. Somewhere near the top of each file should have these words:

> This work is free and unencumbered software released into the public domain. In jurisdictions that recognize copyright laws, the author or authors of this software dedicate any and all copyright interest in the software to the public domain.

- [x] I dedicate any and all copyright interest in this software to the public domain. I make this dedication for the benefit of the public at large and to the detriment of my heirs and successors. I intend this dedication to be an overt act of relinquishment in perpetuity of all present and future rights to this software under copyright law.

### CODE REVIEW

**Comment by kaitlyndlee** [comment]
Is it possible to test the other values for the update parameter? Other than that, everything looks good.

**Comment by amystamile-usgs** [comment]
@kaitlyndlee I wasn't sure if you were wanting me to add additional gtests for the other update parameter options or add more asserts/expects to the existing gtests. The reason I did not test for pointing and position is because "update=spice" handles both so I figured they were covered in these tests. Let me know if that is still what you are suggesting and I can add them.

**Comment by kaitlyndlee** [comment]
Sorry for the confusion. I met to say add additional gtests. I think it might be a good idea to test that setting those parameters has the intended behavior.

**Review by kaitlyndlee — APPROVED** [review]
Looks good.

**Pull request merged**
