### PR TITLE
Remove Qt Deprecated Warnings Part 4

### PR DESCRIPTION
**Pull request by amystamile-usgs**
## Description

Final batch of QT deprecated warning removal

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation change (update to the documentation; no code change)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Infrastructure change (changes to things like CI or the build system that do not impact users)

## Checklist:

- [ ] I have read and agree to abide by the [Code of Conduct](https://github.com/USGS-Astrogeology/ISIS3/blob/dev/Code-Of-Conduct.md)
- [ ] I have read the [**CONTRIBUTING**](https://github.com/USGS-Astrogeology/ISIS3/blob/dev/CONTRIBUTING.md) document.
- [ ] My change requires a change to the documentation and I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] I have added myself to the [.zenodo.json](https://github.com/USGS-Astrogeology/ISIS3/blob/dev/.zenodo.json) document.
- [ ] I have added my user impacting change to the [CHANGELOG.md](https://github.com/USGS-Astrogeology/ISIS3/blob/dev/CHANGELOG.md) document. 

## Licensing
This project is mostly composed of free and unencumbered software released into the public domain, and we are unlikely to accept contributions that are not also released into the public domain. Somewhere near the top of each file should have these words:

> This work is free and unencumbered software released into the public domain. In jurisdictions that recognize copyright laws, the author or authors of this software dedicate any and all copyright interest in the software to the public domain.

- [ ] I dedicate any and all copyright interest in this software to the public domain. I make this dedication for the benefit of the public at large and to the detriment of my heirs and successors. I intend this dedication to be an overt act of relinquishment in perpetuity of all present and future rights to this software under copyright law.

### CODE REVIEW

**Review by chkim-usgs — DISMISSED** [review]

**Comment by amystamile-usgs** [comment]
Build started:
https://us-west-2.console.aws.amazon.com/codesuite/codebuild/950438895271/projects/IsisCodeBuild-52nifRxFNgrA/build/IsisCodeBuild-52nifRxFNgrA%3A61143ac2-0e34-481c-9768-7a27846949ec/?region=us-west-2

**Comment by amystamile-usgs** [comment]
**The following tests FAILED:**
```
--
4906 | 197 - isis_unit_test_Pipeline (Failed)
4907 | 233 - isis_unit_test_ProgramLauncher (Failed)
4908 | 397 - center_app_test_default (Failed)
4909 | 420 - cubediff_app_test_sigFigAccuracy (Failed)
4911 | 461 - dstripe_app_test_default (Failed)
4912 | 462 - dstripe_app_test_parallel (Failed)
4913 | 499 - fx_app_test_singleLine (Failed)
4914 | 639 - noseam_app_test_default (Failed)
4917 | 793 - coreg_app_test_cnet (Failed)
4918 | 794 - coreg_app_test_notarget (Failed)
4919 | 795 - coreg_app_test_warp (Failed)
4920 | 796 - coreg_app_test_warp_no_target (Failed)
4921 | 886 - vimscal_app_test_default (Failed)
4922 | 887 - vimscal_app_test_defaultsolarcoef (Failed)
4923 | 888 - vimscal_app_test_flatfield (Failed)
4924 | 889 - vimscal_app_test_irdark (Failed)
4925 | 890 - vimscal_app_test_nodark (Failed)
4926 | 901 - clemnirclean_app_test_default (Failed)
4929 | 930 - amicacal_app_test_iof (Failed)
4930 | 931 - amicacal_app_test_nullpolarpix (Failed)
4931 | 932 - amicacal_app_test_smearCorrection (Failed)
4935 | 992 - mar10clean_app_test_default (Failed)
4936 | 993 - mar10nonoise_app_test_default (Failed)
4937 | 994 - mar10restore_app_test_default (Failed)
4938 | 1013 - mdiscal_app_test_pxlbinnonzero (Failed)
4939 | 1014 - mdiscal_app_test_warnings (Failed)
4940 | 1015 - mdisddr_app_test_NAC (Failed)
4941 | 1016 - mdisddr_app_test_WAC (Failed)
4943 | 1019 - mdisedrinfo_app_test_multi (Failed)
4944 | 1020 - mdisproc_app_test_cdr (Failed)
4945 | 1021 - mdisproc_app_test_default (Failed)
4946 | 1022 - mdisproc_app_test_trim (Failed)
4948 | 1036 - mocproc_app_test_case01 (Failed)
4949 | 1037 - mocproc_app_test_case02 (Failed)
4950 | 1038 - mocproc_app_test_case03 (Failed)
4952 | 1051 - hicalproc_app_test_default (Failed)
4953 | 1052 - hicalproc_app_test_destripe (Failed)
4954 | 1053 - hicalproc_app_test_furrows (Failed)
4955 | 1061 - hidestripe_app_test_summing4 (Failed)
4956 | 1065 - hifurrows_app_test_newVersion (Failed)
4957 | 1069 - hijitter_app_test_default (Failed)
4958 | 1070 - hijitter_app_test_withCrop (Failed)
4959 | 1071 - hinoise_app_test_binningIsOne (Failed)
4960 | 1072 - hinoise_app_test_binningNotOne (Failed)
4961 | 1078 - hisharpen_app_test_default (Failed)
4965 | 1106 - thmproc_app_test_ir (Failed)
4966 | 1107 - thmproc_app_test_vis (Failed)
4968 | 1126 - tgocassismos_app_test_default (Failed)
4969 | 1133 - vikclean_app_test_default (Failed)
4970 | 1135 - viknobutter_app_test_default (Failed)
4971 | 1137 - viknopepper_app_test_default (Failed)
4972 | 1138 - viknosalt_app_test_default (Failed)
4973 | 1484 - DefaultCube.FunctionalTestMaptrimBoth (Failed)
4974 | 1485 - DefaultCube.FunctionalTestMaptrimCrop (Failed)
4976 | 1704 - LargeCube.FunctionalTestSegmentDefault (Failed)
4977 | 1705 - LargeCube.FunctionalTestSegmentBoundary (Failed)
4978 | 1895 - MroHiriseCube.FunctionalTestHicolormosDefault (Failed)
4979 | 1911 - MroHiriseCube.FunctionalTestHimosDefault (Failed)
4980 | 1917 - Hicubeit.Default (Failed)
4981 | 2018 - Leisa2Isis.Leisa2IsisTestQualityReplacement (Failed)
4982 | 2355 - TgoCassisModuleKernels.TgoCassisTestColorMosaic (Failed)
4983 | 2357 - TgoCassisModuleKernels.TgoCassisSingleColorMosaicReingest (Failed)
4984 | 2360 - TgoCassisModuleTests.TgoCassisUncontrolledSingleColorMosaic (Failed)
```

**Comment by amystamile-usgs** [comment]
Tests are passing now. I had to revert the ProgramLauncher changes. We need to wait until updating to qt6 before we can remove the deprecation warning for QProcess::start. This is because qt6 has a startCommand function. Using the`QProcess::start(const QString&program, const QStringList&arguments)` breaks ~80 tests in Isis.

**Review by chkim-usgs — APPROVED** [review]
Tested again on my local Mac machine, looks good.

**Pull request merged**
