### PR TITLE
Fixed complier warnings for jigsaw tests

### PR DESCRIPTION
**Pull request by acpaquette**
Small complier warning fixes.

## Description
Fixes a few complier warnings when building the jigsaw tests.

## Related Issue
N/A

## Motivation and Context
For testing push

## How Has This Been Tested?
N/A

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation change (update to the documentation; no code change)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] I have read and agree to abide by the [Code of Conduct](https://github.com/USGS-Astrogeology/ISIS3/blob/dev/Code-Of-Conduct.md)
- [x] I have read the [**CONTRIBUTING**](https://github.com/USGS-Astrogeology/ISIS3/blob/dev/CONTRIBUTING.md) document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [x] I have added myself to the [.zenodo.json](https://github.com/USGS-Astrogeology/ISIS3/blob/dev/.zenodo.json) document.
- [x] I have added any user impacting changes to the [CHANGELOG.md](https://github.com/USGS-Astrogeology/ISIS3/blob/dev/CHANGELOG.md) document.

## Licensing
This project is mostly composed of free and unencumbered software released into the public domain, and we are unlikely to accept contributions that are not also released into the public domain. Somewhere near the top of each file should have these words:

> This work is free and unencumbered software released into the public domain. In jurisdictions that recognize copyright laws, the author or authors of this software dedicate any and all copyright interest in the software to the public domain.

- [x] I dedicate any and all copyright interest in this software to the public domain. I make this dedication for the benefit of the public at large and to the detriment of my heirs and successors. I intend this dedication to be an overt act of relinquishment in perpetuity of all present and future rights to this software under copyright law.

### CODE REVIEW

**Comment by acpaquette** [comment]
If you are reviewing this, I recommend hiding all whitespace changes.

**Review by jessemapel — APPROVED** [review]

**Comment by jessemapel** [comment]
Is Jenkins not firing new builds off?

**Comment by Kelvinrr** [comment]
@jessemapel Probably give it some time to discover the new PR, 4135 triggered fine not too long ago. Otherwise I'll manually start the scan in like 30 minutes.

**Comment by acpaquette** [comment]
Handled in #4138

**Pull request closed without merging**
