### PR TITLE
Multisegment DSK support for Bullet engine

### LINKED ISSUE #2632: Mutli-Segment DSKs are not being handled correctly
This is issue has been reported by the Dawn mission team. Their comments follow:

> the problem I'm running into is with the DSK/BDS versions of the shape model here:
> 
> https://naif.jpl.nasa.gov/pub/naif/DAWN/kernels/dsk/
> 
> I think the source of the issue is that all of the files there are made up of smaller files that are combined together (with SPICE dlacat perhaps), and ISIS does not seem to work well with compound files.  For example, the file dawn_ceres_grv_m100_m00p03m0p3_v1.bds (a 30x30 degree area covering 0-30 lon and 0-30 lat) actually consists of 9 10x10 degree files combined together:
``` 
commnt -r dawn_ceres_grv_m100_m00p03m0p3_v1.bds | grep dawn_ceres_g

...
dawn_ceres_grv_m100_m00p01m0p1_v1.bds
dawn_ceres_grv_m100_m00p01p1p2_v1.bds
dawn_ceres_grv_m100_m00p01p2p3_v1.bds
dawn_ceres_grv_m100_p01p02m0p1_v1.bds
dawn_ceres_grv_m100_p01p02p1p2_v1.bds
dawn_ceres_grv_m100_p01p02p2p3_v1.bds
dawn_ceres_grv_m100_p02p03m0p1_v1.bds
dawn_ceres_grv_m100_p02p03p1p2_v1.bds
dawn_ceres_grv_m100_p02p03p2p3_v1.bds
...
```

>Now, if I have an image that covers say 13-19 lon and 18-23 lat and I try to associate this shape model with it when running spiceinit, I get what looks like an out of range error:

```
  Error                     = "An unknown NAIF error has been encountered. The
                               short explanation provided by NAIF is
                               [SPICE(NOINTERCEPT)]. The Naif error is [Ray
                               from vertex number 0 having longitude
                               1.7929049593918E-01 and latitude
                               2.7200364968331E-01 (radians) to center of
                               target 2000001 did not intersect the surface 
                               defined by the input handle and descriptor.]"
```

>I don't have that problem if the image is entirely in the range from 0-10 lon and 0-10 lat (which is the range of the first of the subfiles in the list above.  And, when I try and get it into ISIS cube format with dsk2isis, the resulting cube only covers the first of the 9 subfiles in the list above (0-10 lon and 0-10 lat).  So all of this points to ISIS not dealing well with compound DSK files and just reading the first component/subfile of them.
>
>I'm not sure if this is more of a SPICE issue or if it's something to do with how ISIS calls/uses SPICE.  If it's the latter, then it would be a good thing to update.  Let me know if you have any more questions about this.  I can try and put together a few example files to illustrate what I wrote above.

### PR DESCRIPTION
**Pull request by Kelvinrr**
## Description

`BulletDskShape::loadFromDsk` Previously only loaded the first segment from DSKs. This PR simply changes `BulletDskShape::loadFromDsk`'s implementation to iterate through all segments and concat them into the same mesh. 

## Related Issue

Should fix #2632
## How Has This Been Tested?

All ISIS tests pass, added new Bullet DSK tests. 
Tested on problem image mentioned in #2632 

```
spiceinit from=~/Downloads/FC21B0050201_16006200347F1G.cub spkpredicted=yes shape=user model=~/Downloads/dawn_ceres_grv_m100_m00p03m0p3_v1.bds
Group = Kernels
  NaifFrameCode             = -203121
  LeapSecond                = $base/kernels/lsk/naif0012.tls
  TargetAttitudeShape       = ($base/kernels/pck/pck00009.tpc,
                               $dawn/kernels/pck/dawn_ceres_v05.tpc,
                               $dawn/kernels/pck/dawn_ceres_v00.tf)
  TargetPosition            = ($dawn/kernels/tspk/de421.bsp,
                               $dawn/kernels/tspk/sb_ceres_140724.bsp)
  InstrumentPointing        = ($dawn/kernels/ck/dawn_sc_160104_160110.bc,
                               $dawn/kernels/fk/dawn_v15.tf,
                               $dawn/kernels/fk/dawn_fc_v3.bc)
  Instrument                = $dawn/kernels/ik/dawn_fc_v02.ti
  SpacecraftClock           = $dawn/kernels/sclk/DAWN_203_SCLKSCET.00091.tsc
  InstrumentPosition        = $dawn/kernels/spk/dawn_rec_151023-160202_160412-
                              _v1.bsp
  InstrumentAddendum        = $dawn/kernels/iak/dawnfcAddendum002.ti
  ShapeModel                = /Users/kelvin/Downloads/dawn_ceres_grv_m100_m00-
                              p03m0p3_v1.bds
  InstrumentPositionQuality = Reconstructed
  InstrumentPointingQuality = Reconstructed
  CameraVersion             = 2
  RayTraceEngine            = bullet
  OnError                   = fail
  Tolerance                 = 1.0e-05
End_Group
```
```
campt from=~/Downloads/FC21B0050201_16006200347F1G.cub
Group = GroundPoint
  Filename                   = /Users/kelvin/Downloads/FC21B0050201_160062003-
                               47F1G.cub
  Sample                     = 512.0
  Line                       = 512.0
  PixelValue                 = 0.0013587088
  RightAscension             = 290.14778648636 <DEGREE>
  Declination                = -37.955695452586 <DEGREE>
  PlanetocentricLatitude     = 14.439143764664 <DEGREE>
  PlanetographicLatitude     = 16.737574597144 <DEGREE>
  PositiveEast360Longitude   = 13.283490619851 <DEGREE>
  PositiveEast180Longitude   = 13.283490619851 <DEGREE>
  PositiveWest360Longitude   = 346.71650938015 <DEGREE>
  PositiveWest180Longitude   = -13.283490619851 <DEGREE>
  BodyFixedCoordinate        = (451.3723554722, 106.56258521047,
                                119.41645489578) <km>
  LocalRadius                = 478908.00531118 <meters>
  SampleResolution           = 33.955140557281 <meters/pixel>
  LineResolution             = 33.955140557281 <meters/pixel>
  ObliqueDetectorResolution  = 39.924081261985 <meters>
  ObliquePixelResolution     = 39.924081261985 <meters/pix>
  ObliqueLineResolution      = 39.924081261985 <meters>
  ObliqueSampleResolution    = 39.924081261985 <meters>

  # Spacecraft Information
  SpacecraftPosition         = (793.4071950334, 189.35051927198,
                                211.8977380724) <km>
  SpacecraftAzimuth          = NULL
  SlantDistance              = 363.86049694605 <km>
  TargetCenterDistance       = 842.76286562682 <km>
  SubSpacecraftLatitude      = 14.562279765951 <DEGREE>
  SubSpacecraftLongitude     = 13.422840202778 <DEGREE>
  SpacecraftAltitude         = 1.79769313486232e+308 <km>
  OffNadirAngle              = 31.552042638342 <DEGREE>
  SubSpacecraftGroundAzimuth = 47.595139284594 <DEGREE>

  # Sun Information
  SunPosition                = (233086063.40045, 378675971.33493,
                                26875371.427918) <km>
  SubSolarAzimuth            = NULL
  SolarDistance              = 2.9778060694403 <AU>
  SubSolarLatitude           = 3.4587467265198 <DEGREE>
  SubSolarLongitude          = 58.386495468791 <DEGREE>
  SubSolarGroundAzimuth      = 99.415669064089 <DEGREE>

  # Illumination and Other
  Phase                      = 45.525698456225 <DEGREE>
  Incidence                  = 23.664217791 <DEGREE>
  Emission                   = 31.734698923989 <DEGREE>
  NorthAzimuth               = NULL

  # Time
  EphemerisTime              = 505382695.5264 <seconds>
  UTC                        = 2016-01-06T20:03:47.3423232
  LocalSolarTime             = 8.9931330100707 <hour>
  SolarLongitude             = 120.90895691152 <DEGREE>

  # Look Direction Unit Vectors in Body Fixed, J2000, and Camera Coordinate Systems.
  LookDirectionBodyFixed     = (-0.94001641407068, -0.22752657888496,
                                -0.25416686876657)
  LookDirectionJ2000         = (0.27158853416656, -0.74023696344476,
                                -0.61505195395133)
  LookDirectionCamera        = (-4.66742185579738e-05, -4.66448989071555e-05,
                                0.99999999782289)
End_Group
```

## Screenshots (if appropriate):

Jupyter Notebook for visualizing the DSK in #2632 to confirm results: 
https://gist.github.com/Kelvinrr/151e462fd2ddb1664a5b31a5364701e5

Resulting Visualizations: 
[Vertices of DSK Segments](https://plot.ly/~kelvinrr/4/segment-0-segment-1-segment-2-segment-3-segment-4-segment-5-segment-6-segment-7-/#/plot)
[Overlapping Vertices between DSK segments](https://plot.ly/~kelvinrr/2/segment-0-segment-1-seg-1-and-2-overlaped-verts/#/)

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation change (update to the documentation; no code change)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] I have read and agree to abide by the [Code of Conduct](https://usgs-astrogeology.github.io/code/)
- [x] I have read the [**CONTRIBUTING**](https://github.com/USGS-Astrogeology/ISIS3/blob/dev/CONTRIBUTING.md) document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

## Licensing
This project is mostly composed of free and unencumbered software released into the public domain, and we are unlikely to accept contributions that are not also released into the public domain. Somewhere near the top of each file should have these words:

> This work is free and unencumbered software released into the public domain. In jurisdictions that recognize copyright laws, the author or authors of this software dedicate any and all copyright interest in the software to the public domain.

- [x] I dedicate any and all copyright interest in this software to the public domain. I make this dedication for the benefit of the public at large and to the detriment of my heirs and successors. I intend this dedication to be an overt act of relinquishment in perpetuity of all present and future rights to this software under copyright law.

### CODE REVIEW

**Comment by jessemapel** [comment]
Looks good.

We need to either make a test DSK file or find a way to test without one.

**Comment by Kelvinrr** [comment]
For the sake of documenting it, Jupyter Notebook for visualizing the DSK in #2632 to confirm results: 
https://gist.github.com/Kelvinrr/151e462fd2ddb1664a5b31a5364701e5

Resulting Visualizations: 
[DSK Segments](https://plot.ly/~kelvinrr/4/segment-0-segment-1-segment-2-segment-3-segment-4-segment-5-segment-6-segment-7-/#/plot)
[Overlap between DSK segments](https://plot.ly/~kelvinrr/2/segment-0-segment-1-seg-1-and-2-overlaped-verts/#/)

**Comment by Kelvinrr** [comment]
Added tests using Jessie's artificial DSK file. This should be good to go after a quick look over.

**Review by jessemapel — APPROVED** [review]
Looks good to me.

**Comment by jlaura** [comment]
Should this get tagged as 3.7.0 or is the associated issue tagged that way? I am thinking about release note generation for this new functionality.

**Comment by jessemapel** [comment]
This should be tagged. Also, isn't this going out in 3.6.2?

**Comment by jlaura** [comment]
yes and yes

**Pull request merged**
