### PR TITLE
edrget deprecation

### PR DESCRIPTION
**Pull request by gsn9**
Removed all associated files for the edrget application. 

## Related Issue
Solves #4665 

https://github.com/USGS-Astrogeology/ISIS3/issues/4665

## How Has This Been Tested?

Creating a fresh build of ISIS after removing files. 

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation change (update to the documentation; no code change)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] I have read and agree to abide by the [Code of Conduct](https://github.com/USGS-Astrogeology/ISIS3/blob/dev/Code-Of-Conduct.md)
- [ ] I have read the [**CONTRIBUTING**](https://github.com/USGS-Astrogeology/ISIS3/blob/dev/CONTRIBUTING.md) document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [x] I have added myself to the [.zenodo.json](https://github.com/USGS-Astrogeology/ISIS3/blob/dev/.zenodo.json) document.
- [x] I have added any user impacting changes to the [CHANGELOG.md](https://github.com/USGS-Astrogeology/ISIS3/blob/dev/CHANGELOG.md) document.

## Licensing
This project is mostly composed of free and unencumbered software released into the public domain, and we are unlikely to accept contributions that are not also released into the public domain. Somewhere near the top of each file should have these words:

> This work is free and unencumbered software released into the public domain. In jurisdictions that recognize copyright laws, the author or authors of this software dedicate any and all copyright interest in the software to the public domain.

- [x] I dedicate any and all copyright interest in this software to the public domain. I make this dedication for the benefit of the public at large and to the detriment of my heirs and successors. I intend this dedication to be an overt act of relinquishment in perpetuity of all present and future rights to this software under copyright law.

### CODE REVIEW

**Review by acpaquette — APPROVED** [review]
Overall this looks good. @jlaura Should this go in now or wait for a major version tick?

**Comment by jlaura** [comment]
We need to do a bug fix release at the conclusion of this work. We should probably wait for a full RC for this to go in. I am very open to other opinions.

**Comment by jessemapel** [comment]
This is complete but it's waiting because it's not a crucial change and it can wait until we collect more breaking changes and decide to tick the major version number.

**Review by scsides — APPROVED** [review]

**Comment by jlaura** [comment]
This is still active and is awaiting other API breaking changes before being merged.

**Comment by AustinSanders** [comment]
Closed via #5189

**Pull request closed without merging**
