### PR TITLE
Added a refernce to phocube to camdev docs

### LINKED ISSUE #3483: camdev "LOCAL" options unclear
**Description**

I, and most users, will not know what the difference between "EMISSION" and "LOCALEMISSION" is.  Similarly with INCIDENCE and LOCALINCIDENCE.  

**Suggested Edit**

I suspect the difference is easy to explain (one used a DEM and the other doesn't is my guess, but its just a guess).  There is some text related to 90 degrees, but it does not clarify the difference between these options.  Please add a few words to explain what these are, perhaps next to the text describing the 90 emission/incidence limits.  I *think* the other keywords will be understood.  

Thanks!

### PR DESCRIPTION
**Pull request by jessemapel**
Added a note to the warning at the top of the camdev docs recommending phocube.

## Description

See discussion in #3483 

## Related Issue

Fixes #3483 

## Motivation and Context

We moved camdev into the public distribution with the conda distribution system. This should help users who happen upon the application.

## How Has This Been Tested?

Docs were built for the applications and looked good.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Documentation change (update to the documentation; no code change)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] I have read and agree to abide by the [Code of Conduct](https://usgs-astrogeology.github.io/code/)
- [x] I have read the [**CONTRIBUTING**](https://github.com/USGS-Astrogeology/ISIS3/blob/dev/CONTRIBUTING.md) document.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

## Licensing
This project is mostly composed of free and unencumbered software released into the public domain, and we are unlikely to accept contributions that are not also released into the public domain. Somewhere near the top of each file should have these words:

> This work is free and unencumbered software released into the public domain. In jurisdictions that recognize copyright laws, the author or authors of this software dedicate any and all copyright interest in the software to the public domain.

- [x] I dedicate any and all copyright interest in this software to the public domain. I make this dedication for the benefit of the public at large and to the detriment of my heirs and successors. I intend this dedication to be an overt act of relinquishment in perpetuity of all present and future rights to this software under copyright law.

### CODE REVIEW

**Review by jlaura — APPROVED** [review]
This change is tiny, but the review looks large because of all the white space stripping that your IDE is doing...

**Comment by jessemapel** [comment]
ISIS has a lot of whitespace padding from slick edit settings used previously. Atom likes to strip all of that out.

**Review by krlberry — APPROVED** [review]
:+1: Looks good to me!

**Review by acpaquette — APPROVED** [review]
:+1: Thank you atom for removing the extra white space

**Pull request merged**
