### PR TITLE
Disable HRSC from spice server

### LINKED ISSUE #5223: spiceinit error when processing HRSC images
**ISIS version(s) affected: 7.2.0

**Description**  
When I used 'spiceinit' to initialize the HRSC images, the software reported an error to me: "The Server was unable to initialize the cube.The error reported was: Unable to initialize camera model." Spice data has 'use the isis spice web service' checked. CK has 'reconstructed pointing kernels' and 'predicted point kernels' checked. Strangely enough when I processed LROC images there was no such error.

**How to reproduce**  
See Description.

### PR DESCRIPTION
**Pull request by amystamile-usgs**
## Related Issue

closes #5223 

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Documentation change (update to the documentation; no code change)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Infrastructure change (changes to things like CI or the build system that do not impact users)

## Checklist:

- [x] I have read and agree to abide by the [Code of Conduct](https://github.com/USGS-Astrogeology/ISIS3/blob/dev/Code-Of-Conduct.md)
- [x] I have read the [**CONTRIBUTING**](https://github.com/USGS-Astrogeology/ISIS3/blob/dev/CONTRIBUTING.md) document.
- [x] My change requires a change to the documentation and I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] I have added myself to the [.zenodo.json](https://github.com/USGS-Astrogeology/ISIS3/blob/dev/.zenodo.json) document.
- [ ] I have added any user impacting changes to the [CHANGELOG.md](https://github.com/USGS-Astrogeology/ISIS3/blob/dev/CHANGELOG.md) document.

## Licensing
This project is mostly composed of free and unencumbered software released into the public domain, and we are unlikely to accept contributions that are not also released into the public domain. Somewhere near the top of each file should have these words:

> This work is free and unencumbered software released into the public domain. In jurisdictions that recognize copyright laws, the author or authors of this software dedicate any and all copyright interest in the software to the public domain.

- [x] I dedicate any and all copyright interest in this software to the public domain. I make this dedication for the benefit of the public at large and to the detriment of my heirs and successors. I intend this dedication to be an overt act of relinquishment in perpetuity of all present and future rights to this software under copyright law.

### CODE REVIEW

**Comment by Kelvinrr** [comment]
Can we get a test added as well?

**Comment by amystamile-usgs** [comment]
> Can we get a test added as well?

Added a test.

**Comment by Kelvinrr** [comment]
Seems something is wrong with Jenkins atm? Once it comes back good this can be approved and merged.

**Comment by Kelvinrr** [comment]
@amystamile-usgs Jenkins still down :( I'll test locally.

**Review by Kelvinrr — COMMENTED** [review]
Tests look good, add a changelog entry and we can get this merged.

**Comment by amystamile-usgs** [comment]
@Kelvinrr added changelog

**Review by Kelvinrr — APPROVED** [review]

**Pull request merged**
