### PR TITLE
Adds MSL to rclone config

### PR DESCRIPTION
**Pull request by amystamile-usgs**
## Description

MSL kernels added to isis_data area. msl added to config to allow rclone of data.

## Related Issue

CSM sprint

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Documentation change (update to the documentation; no code change)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Infrastructure change (changes to things like CI or the build system that do not impact users)

## Checklist:

- [x] I have read and agree to abide by the [Code of Conduct](https://github.com/USGS-Astrogeology/ISIS3/blob/dev/Code-Of-Conduct.md)
- [x] I have read the [**CONTRIBUTING**](https://github.com/USGS-Astrogeology/ISIS3/blob/dev/CONTRIBUTING.md) document.
- [x] My change requires a change to the documentation and I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] I have added myself to the [.zenodo.json](https://github.com/USGS-Astrogeology/ISIS3/blob/dev/.zenodo.json) document.
- [ ] I have added any user impacting changes to the [CHANGELOG.md](https://github.com/USGS-Astrogeology/ISIS3/blob/dev/CHANGELOG.md) document.

## Licensing
This project is mostly composed of free and unencumbered software released into the public domain, and we are unlikely to accept contributions that are not also released into the public domain. Somewhere near the top of each file should have these words:

> This work is free and unencumbered software released into the public domain. In jurisdictions that recognize copyright laws, the author or authors of this software dedicate any and all copyright interest in the software to the public domain.

- [x] I dedicate any and all copyright interest in this software to the public domain. I make this dedication for the benefit of the public at large and to the detriment of my heirs and successors. I intend this dedication to be an overt act of relinquishment in perpetuity of all present and future rights to this software under copyright law.

### CODE REVIEW

**Review by jessemapel — COMMENTED** [review]
Are we not pulling from naif's public kernel sets?

**Comment by amystamile-usgs** [comment]
@jessemapel yes and no. Since I added in the metakernel, I set up the kernels in the S3 bucket.

**Comment by Kelvinrr** [comment]
@amystamile-usgs does there exist a naif source? If so, we want to pull from there and only upload our own metakernels and kernel.db's

**Comment by amystamile-usgs** [comment]
@Kelvinrr I added in the naif source to the config. Do I need to remove all kernels originally added to the S3 bucket (besides the metakernels)?

**Comment by Kelvinrr** [comment]
@amystamile-usgs yeah, I'd remove anything that isn't in the NAIF source. If you remove them from usgs_data, the sync should remove them from the buckets.

**Comment by amystamile-usgs** [comment]
As an update, I removed everything in usgs_data that is from NAIF but the sync did not remove them from the buckets.

**Comment by Kelvinrr** [comment]
@amystamile-usgs ugh, apparently aws sync specifically wants a --delete flag. They should disappear tonight.

**Comment by jessemapel** [comment]
It seems like this is ready to go then?

**Review by Kelvinrr — APPROVED** [review]

**Pull request merged**
