### PR TITLE
Pin qwt to 6.2.0 or lower

### PR DESCRIPTION
**Pull request by chkim-usgs**
## Description

`qwt`'s latest version was bumped to `6.3.0` which causes an ISIS build error. Pinning `qwt` to `<6.3.0` and creating a conda env with this change resulted in a successful ISIS dev build.

Also found that pinning `qwt==6.2.0` caused a segfault during the ISIS build but `<6.3.0` did not cause any errors.

## Related Issue

Addresses https://github.com/DOI-USGS/ISIS3/issues/5498

## How Has This Been Validated?

Created fresh conda environment with `qwt <6.3.0` and built ISIS dev. 

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation change (update to the documentation; no code change)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Infrastructure change (changes to things like CI or the build system that do not impact users)

## Checklist:

- [x] I have read and agree to abide by the [Code of Conduct](https://github.com/USGS-Astrogeology/ISIS3/blob/dev/Code-Of-Conduct.md)
- [ ] I have read the [**CONTRIBUTING**](https://github.com/USGS-Astrogeology/ISIS3/blob/dev/CONTRIBUTING.md) document.
- [ ] My change requires a change to the documentation and I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] I have added myself to the [.zenodo.json](https://github.com/USGS-Astrogeology/ISIS3/blob/dev/.zenodo.json) document.
- [x] I have added my user impacting change to the [CHANGELOG.md](https://github.com/USGS-Astrogeology/ISIS3/blob/dev/CHANGELOG.md) document. 

## Licensing
This project is mostly composed of free and unencumbered software released into the public domain, and we are unlikely to accept contributions that are not also released into the public domain. Somewhere near the top of each file should have these words:

> This work is free and unencumbered software released into the public domain. In jurisdictions that recognize copyright laws, the author or authors of this software dedicate any and all copyright interest in the software to the public domain.

- [x] I dedicate any and all copyright interest in this software to the public domain. I make this dedication for the benefit of the public at large and to the detriment of my heirs and successors. I intend this dedication to be an overt act of relinquishment in perpetuity of all present and future rights to this software under copyright law.

### CODE REVIEW

**Review by acpaquette — COMMENTED** [review]
Overall looks great! Could this make its way into the meta.yml?

**Comment by chkim-usgs** [comment]
@acpaquette Yes, `qwt` should already be pinned in the meta.yml?

**Comment by acpaquette** [comment]
@chkim-usgs Looks like it has `pin_compatibility` in the run section but we should pin the version in the build section

**Comment by chkim-usgs** [comment]
@acpaquette `qwt` is pinned as `<6.3.0` in the build section, should it be something else?

**Comment by acpaquette** [comment]
@chkim-usgs My bad, poor reading comp on my end. Looks good!

**Review by acpaquette — APPROVED** [review]

**Pull request merged**
