### PR TITLE
Adds support for JAXA archive Level 2B2 images to Kaguya MI in ISIS.

### PR DESCRIPTION
**Pull request by krlberry**
##  Description
Adds support for JAXA archive Level 2B2 images to Kaguya MI in ISIS and associated tests. 
Includes updated unit test for camera model with new data format and updated ingestion test.

## Related Issue
Is there an issue for this work? 

## Motivation and Context
Supports work on Kaguya MI level 2b2 images in ISIS. 

## How Has This Been Tested?
Local tests pass and newly added tests for new functionality pass.

To test the camera model: 
I took 4-5 of these images and compared them against an internal Lola/Kaguya merged DEM that was `map2cam`'d with the test cubes as the match images. These were blinked in qview and I used the 'measure' tool to get some rough estimates of offset and they were 5+ pixels, but due to them being uncontrolled and without smithed spice, this seemed like a reasonable offset to Jesse and Stuart (and me.) If you're internal and would like to take a look at these cubes, they are at `/work/projects/kberry/kaguya2020`.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Documentation change (update to the documentation; no code change)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] I have read and agree to abide by the [Code of Conduct](https://usgs-astrogeology.github.io/code/)
- [x] I have read the [**CONTRIBUTING**](https://github.com/USGS-Astrogeology/ISIS3/blob/dev/CONTRIBUTING.md) document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

## Licensing
This project is mostly composed of free and unencumbered software released into the public domain, and we are unlikely to accept contributions that are not also released into the public domain. Somewhere near the top of each file should have these words:

> This work is free and unencumbered software released into the public domain. In jurisdictions that recognize copyright laws, the author or authors of this software dedicate any and all copyright interest in the software to the public domain.

- [x] I dedicate any and all copyright interest in this software to the public domain. I make this dedication for the benefit of the public at large and to the detriment of my heirs and successors. I intend this dedication to be an overt act of relinquishment in perpetuity of all present and future rights to this software under copyright law.

### CODE REVIEW

**Comment by kaitlyndlee** [comment]
Wanted to mention in this PR that we ran camtest on a VIS level 2B2 image ingested by kaguyami2isis. The highest DN value was around .009, under the ground to image tolerance of .01. This means that we can go from ground to image and image to ground with little offset.

**Review by kaitlyndlee — APPROVED** [review]
Looks good!

**Review by jessemapel — APPROVED** [review]
Looks great.

**Comment by jessemapel** [comment]
@kberryUSGS Is it expected that the kaguymi2isis test will fail until updated test data is checked in?

**Comment by krlberry** [comment]
@jessemapel This looks like an actual test failure. I'm guessing more keywords need to be added to the pvl ignore file.

**Comment by krlberry** [comment]
The tests are passing now after updating the test data (no code changes.) Does someone else want to merge this?

**Pull request merged**
