### PR TITLE
Fixes Cassini position NAIF errors due to incorrect center body in spkwriter.

### PR DESCRIPTION
**Pull request by amystamile-usgs**
For Cassini Titan images spiceinited with spkwriter images were returning different positions than the same image spiceinited with a default cassini spk kernel.

The issue was that spkwriter was writing positions of Cassini relative to Titan but labeling
it in the kernel as the position relative to the Saturn Barycenter. This is due to the camera models hardcoding the center body as Saturn Barycenter.

 
## Description
This PR removes the hardcoded functions in the Cassini camera models. This is the results of campt from the two results:

Default spiceinited cube:
```
Group = GroundPoint
  Filename                   = /Users/astamile/testData/NAIFError/Finaltest_r-
                               egspice.cub
  Sample                     = 512.0
  Line                       = 512.0
  PixelValue                 = 1973
  RightAscension             = 116.13215283233 <DEGREE>
  Declination                = -1.1326024410936 <DEGREE>
  PlanetocentricLatitude     = -0.45931134252056 <DEGREE>
  PlanetographicLatitude     = -0.45931134252056 <DEGREE>
  PositiveEast360Longitude   = 213.42739550192 <DEGREE>
  PositiveEast180Longitude   = -146.57260449808 <DEGREE>
  PositiveWest360Longitude   = 146.57260449808 <DEGREE>
  PositiveWest180Longitude   = 146.57260449808 <DEGREE>
  BodyFixedCoordinate        = (-2148.986188821, -1418.4700411369,
                                -20.64225409362) <km>
  LocalRadius                = 2575000.0 <meters>
  SampleResolution           = 930.54010794526 <meters/pixel>
  LineResolution             = 930.54010794526 <meters/pixel>
  ObliqueDetectorResolution  = 930.54081760077 <meters>
  ObliquePixelResolution     = 930.54081760077 <meters/pix>
  ObliqueLineResolution      = 930.54081760077 <meters>
  ObliqueSampleResolution    = 930.54081760077 <meters>

  # Spacecraft Information
  SpacecraftPosition         = (-131745.51596537, -86981.58912533,
                                -1074.5876729846) <km>
  SpacecraftAzimuth          = 307.95635855922 <DEGREE>
  SlantDistance              = 155297.83861498 <km>
  TargetCenterDistance       = 157872.83668325 <km>
  SubSpacecraftLatitude      = -0.38999624702609 <DEGREE>
  SubSpacecraftLongitude     = 213.43376164131 <DEGREE>
  SpacecraftAltitude         = 155297.83668325 <km>
  OffNadirAngle              = 0.0011541531672208 <DEGREE>
  SubSpacecraftGroundAzimuth = 5.2474026169712 <DEGREE>

  # Sun Information
  SunPosition                = (-879514799.08957, -929599477.90723,
                                -460513070.24518) <km>
  SubSolarAzimuth            = 89.820124125382 <DEGREE>
  SolarDistance              = 9.0914496844703 <AU>
  SubSolarLatitude           = -19.791397298449 <DEGREE>
  SubSolarLongitude          = 226.58580801267 <DEGREE>
  SubSolarGroundAzimuth      = 147.11119332649 <DEGREE>

  # Illumination and Other
  Phase                      = 23.288232219596 <DEGREE>
  Incidence                  = 23.232536820009 <DEGREE>
  Emission                   = 0.070760962912729 <DEGREE>
  NorthAzimuth               = 302.70895137818 <DEGREE>

  # Time
  EphemerisTime              = 183716769.81247 <seconds>
  UTC                        = 2005-10-27T20:25:05.63
  LocalSolarTime             = 11.122772499283 <hour>
  SolarLongitude             = 309.34315015565 <DEGREE>

  # Look Direction Unit Vectors in Body Fixed, J2000, and Camera Coordinate Systems.
  LookDirectionBodyFixed     = (0.8345031130655, 0.55096142900174,
                                0.0067866071304697)
  LookDirectionJ2000         = (-0.44035699831055, 0.89760514998248,
                                -0.019766354338873)
  LookDirectionCamera        = (-2.99598538134119e-06, -2.99598538134119e-06,
                                0.99999999999102)
End_Group

```

spkwriter spiceinited cube:

```
Group = GroundPoint
  Filename                   = /Users/astamile/testData/NAIFError/Finaltest_s-
                               pkwriterspice.cub
  Sample                     = 512.0
  Line                       = 512.0
  PixelValue                 = 1973
  RightAscension             = 116.13215283233 <DEGREE>
  Declination                = -1.1326024410936 <DEGREE>
  PlanetocentricLatitude     = -0.45931134252055 <DEGREE>
  PlanetographicLatitude     = -0.45931134252055 <DEGREE>
  PositiveEast360Longitude   = 213.42739550192 <DEGREE>
  PositiveEast180Longitude   = -146.57260449808 <DEGREE>
  PositiveWest360Longitude   = 146.57260449808 <DEGREE>
  PositiveWest180Longitude   = 146.57260449808 <DEGREE>
  BodyFixedCoordinate        = (-2148.986188821, -1418.4700411369,
                                -20.64225409362) <km>
  LocalRadius                = 2575000.0 <meters>
  SampleResolution           = 930.54010794526 <meters/pixel>
  LineResolution             = 930.54010794526 <meters/pixel>
  ObliqueDetectorResolution  = 930.54081760077 <meters>
  ObliquePixelResolution     = 930.54081760077 <meters/pix>
  ObliqueLineResolution      = 930.54081760077 <meters>
  ObliqueSampleResolution    = 930.54081760077 <meters>

  # Spacecraft Information
  SpacecraftPosition         = (-131745.51596537, -86981.58912533,
                                -1074.5876729846) <km>
  SpacecraftAzimuth          = 307.95635855922 <DEGREE>
  SlantDistance              = 155297.83861498 <km>
  TargetCenterDistance       = 157872.83668325 <km>
  SubSpacecraftLatitude      = -0.38999624702609 <DEGREE>
  SubSpacecraftLongitude     = 213.43376164131 <DEGREE>
  SpacecraftAltitude         = 155297.83668325 <km>
  OffNadirAngle              = 0.0011541531672208 <DEGREE>
  SubSpacecraftGroundAzimuth = 5.2474026169712 <DEGREE>

  # Sun Information
  SunPosition                = (-879514799.08957, -929599477.90723,
                                -460513070.24518) <km>
  SubSolarAzimuth            = 89.820124125382 <DEGREE>
  SolarDistance              = 9.0914496844703 <AU>
  SubSolarLatitude           = -19.791397298449 <DEGREE>
  SubSolarLongitude          = 226.58580801267 <DEGREE>
  SubSolarGroundAzimuth      = 147.11119332649 <DEGREE>

  # Illumination and Other
  Phase                      = 23.288232219596 <DEGREE>
  Incidence                  = 23.232536820009 <DEGREE>
  Emission                   = 0.070760962912729 <DEGREE>
  NorthAzimuth               = 302.70895137818 <DEGREE>

  # Time
  EphemerisTime              = 183716769.81247 <seconds>
  UTC                        = 2005-10-27T20:25:05.63
  LocalSolarTime             = 11.122772499283 <hour>
  SolarLongitude             = 309.34315015565 <DEGREE>

  # Look Direction Unit Vectors in Body Fixed, J2000, and Camera Coordinate Systems.
  LookDirectionBodyFixed     = (0.8345031130655, 0.55096142900174,
                                0.0067866071304697)
  LookDirectionJ2000         = (-0.44035699831055, 0.89760514998248,
                                -0.019766354338873)
  LookDirectionCamera        = (-2.99598538134119e-06, -2.99598538134119e-06,
                                0.99999999999102)
End_Group
```

## Related Issue

#4942 

## Motivation and Context

Q4 ISIS Support Sprint

## How Has This Been Tested?

Compared with campt. Check Jenkins for any potential broken tests.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation change (update to the documentation; no code change)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] I have read and agree to abide by the [Code of Conduct](https://github.com/USGS-Astrogeology/ISIS3/blob/dev/Code-Of-Conduct.md)
- [x] I have read the [**CONTRIBUTING**](https://github.com/USGS-Astrogeology/ISIS3/blob/dev/CONTRIBUTING.md) document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [ ] I have added myself to the [.zenodo.json](https://github.com/USGS-Astrogeology/ISIS3/blob/dev/.zenodo.json) document.
- [x] I have added any user impacting changes to the [CHANGELOG.md](https://github.com/USGS-Astrogeology/ISIS3/blob/dev/CHANGELOG.md) document.

## Licensing
This project is mostly composed of free and unencumbered software released into the public domain, and we are unlikely to accept contributions that are not also released into the public domain. Somewhere near the top of each file should have these words:

> This work is free and unencumbered software released into the public domain. In jurisdictions that recognize copyright laws, the author or authors of this software dedicate any and all copyright interest in the software to the public domain.

- [x] I dedicate any and all copyright interest in this software to the public domain. I make this dedication for the benefit of the public at large and to the detriment of my heirs and successors. I intend this dedication to be an overt act of relinquishment in perpetuity of all present and future rights to this software under copyright law.

### CODE REVIEW

**Review by jessemapel — COMMENTED** [review]
Change looks good. The only thing I see different in the campt results is a very very tiny change in lat/lon 14 decimal places out. Definitely within the error from re-interpolation in the kernel write and read process.

I'm holding approval until CI runs. Currently Jenkins is having a bad week. I'm working to fix it so this and other PRs can get a good CI run.

**Comment by amystamile-usgs** [comment]
Tried rerunning the CI run this morning and we are still seeing build errors at the tail-end of the build.

**Review by jessemapel — DISMISSED** [review]
If you want to run local tests go for it and post the output. Otherwise we can sit until Jenkins is sorted.

**Comment by amystamile-usgs** [comment]
Struggled with cmake not building the tests correctly. Kept getting the following error:
```CMake Error at /Users/astamile/opt/anaconda3/envs/isis/share/cmake-3.23/Modules/GoogleTestAddTests.cmake:112 (message):
CMake Error at /Users/astamile/opt/anaconda3/envs/isis/share/cmake-3.23/Modules/GoogleTestAddTests.cmake:112 (message):
  Error running test executable.

    Path: '/Users/astamile/isis/ISIS3/build/tests/runISISTests'
    Result: Segmentation fault
```
I was able to run the unit tests with the following failures:
```
	128 - isis_unit_test_JP2Importer (Failed)
	321 - isis_unit_test_SqlRecord (Failed)
	1043 - mex_unit_test_MexHrscSrcCamera (Failed)
```

They don't seem applicable to these PR changes.

**Comment by amystamile-usgs** [comment]
Ran tests on prog28 with the following results:
```
	128 - isis_unit_test_JP2Importer (Failed)
	1042 - mex_unit_test_MexHrscSrcCamera (Failed)
	811 - deltack_app_test_directOffTarget (Failed)
	984 - lronaccal_app_test_nacl-full (Failed)
	985 - lronaccal_app_test_nacl-summed (Failed)
	986 - lronaccal_app_test_nacr-full (Failed)
	987 - lronaccal_app_test_nacr-summed (Failed)
	1759 - TempTestingFiles.FunctionalTestStd2isisJp2 (Failed)
	1765 - TempTestingFiles.UnitTestImageImporterStd2IsisJp2 (Failed)
	1912 - IsisTruthCube.FunctionalTestsIsis2StdJpeg2KGray (Failed)
	1913 - IsisTruthCube.FunctionalTestsIsis2StdJpeg2KU16 (Failed)
	1914 - IsisTruthCube.FunctionalTestsIsis2StdJpeg2KS16 (Failed)
	1924 - SmallARGBCube.FunctionalTestsIsis2StdJpeg2KRGB (Failed)
	1925 - SmallARGBCube.FunctionalTestsIsis2StdJpeg2KARGB (Failed)
	905 - cassini_module_test_vims (Failed)
	951 - hayabusa_module_test_fullframe (Failed)
	952 - hayabusa_module_test_subframe (Failed)
	1109 - mro_module_test_hirise (Failed)
	1110 - near_module_test_msi (Failed)
```

These same tests also failed in my caminfo branch.

**Comment by jessemapel** [comment]
All of the tests with JPEG 2000 are likely failing because you didn't pass the JP2KFLAG to CMake so we can ignore them. The rest are likely existing failures in dev we missed due to #5000 

So, I think this is ready to go

**Comment by jessemapel** [comment]
Can you check why this test is failing for me? cassini_module_test_vims

**Comment by amystamile-usgs** [comment]
> Can you check why this test is failing for me? cassini_module_test_vims

Looks like cassini_module_test_vims failed on the nightly build so I don't believe this test failure is relating to these changes.

**Comment by jessemapel** [comment]
@amystamile-usgs Go ahead and fix the merge conflicts and this is good to go

**Review by jessemapel — APPROVED** [review]

**Pull request merged**
