### PR TITLE
Modifying how ProcessRubberSheet::transformPatch() handles buffers

### PR DESCRIPTION
**Pull request by SgStapleton**
## Description

A Buffer of size 1x1x1 was originally being used and written out to the ouput cube for every single pixel in the image. There is now a bigger Buffer being created (size depending on parameters to function) and it is only being written to the cube once fully filled.

## Related Issue

This was a general improvement for LROC efficiency, but will have positive impact on ISIS as a whole. #3192

## Motivation and Context

The LROC mission team was experiencing long run times for cam2map for their data.

## How Has This Been Tested?

I ran the nightly testing suite as well as confirmed that other working cubes matched to an older version of the run of cam2map on ISIS (isis3.6.2).

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation change (update to the documentation; no code change)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] I have read and agree to abide by the [Code of Conduct](https://usgs-astrogeology.github.io/code/)
- [ ] I have read the [**CONTRIBUTING**](https://github.com/USGS-Astrogeology/ISIS3/blob/dev/CONTRIBUTING.md) document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

## Licensing
This project is mostly composed of free and unencumbered software released into the public domain, and we are unlikely to accept contributions that are not also released into the public domain. Somewhere near the top of each file should have these words:

> This work is free and unencumbered software released into the public domain. In jurisdictions that recognize copyright laws, the author or authors of this software dedicate any and all copyright interest in the software to the public domain.

- [x] I dedicate any and all copyright interest in this software to the public domain. I make this dedication for the benefit of the public at large and to the detriment of my heirs and successors. I intend this dedication to be an overt act of relinquishment in perpetuity of all present and future rights to this software under copyright law.

### CODE REVIEW

**Comment by SgStapleton** [comment]
The tests for this are running right now. I will let you know when this is ready to go.

**Review by scsides — APPROVED** [review]

**Comment by scsides** [comment]
Other enhancements are underway to address this issues. It will most likely require more than one specific fix to get significant speed improvements.

**Comment by jlaura** [comment]
Can we merge this? If not, what is the plan on this?

**Comment by scsides** [comment]
This is one of the pieces I'm working on now. If I can get the last problem fixed it should go in.

**Comment by scsides** [comment]
This is currently waiting on a full test. All other work discussed has been isolated from this one change.

**Comment by SgStapleton** [comment]
This is now being handled in https://github.com/USGS-Astrogeology/ISIS3/pull/3381

Closing this PR...

**Pull request closed without merging**
