### PR TITLE
Updated GCC4 environment

### PR DESCRIPTION
**Pull request by jessemapel**
## Description

I pushed a GCC4 compatible ALE build so that the GCC4 environment can use it. I also changed the pin on the nn dependency, the most recent build uses GCC7 so I had to push it back to an earlier build.

## Related Issue

CentOS is not building on Jenkins

## Motivation and Context

CentOS uses an older version of GCC which is not compatible with GCC 7 compiled binaries. This updates the handful of dependencies which are different.

## How Has This Been Tested?

Built and tested on CentOS with a new environment. All tests passed except for the failures being addressed by #3888 

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation change (update to the documentation; no code change)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] I have read and agree to abide by the [Code of Conduct](https://usgs-astrogeology.github.io/code/)
- [x] I have read the [**CONTRIBUTING**](https://github.com/USGS-Astrogeology/ISIS3/blob/dev/CONTRIBUTING.md) document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

## Licensing
This project is mostly composed of free and unencumbered software released into the public domain, and we are unlikely to accept contributions that are not also released into the public domain. Somewhere near the top of each file should have these words:

> This work is free and unencumbered software released into the public domain. In jurisdictions that recognize copyright laws, the author or authors of this software dedicate any and all copyright interest in the software to the public domain.

- [x] I dedicate any and all copyright interest in this software to the public domain. I make this dedication for the benefit of the public at large and to the detriment of my heirs and successors. I intend this dedication to be an overt act of relinquishment in perpetuity of all present and future rights to this software under copyright law.

### CODE REVIEW

**Review by krlberry — DISMISSED** [review]
:+1: Looks good to me!

**Comment by jessemapel** [comment]
I'm re-running tests post #3888

**Comment by jessemapel** [comment]
This is ready for review now

**Review by krlberry — APPROVED** [review]
:+1: Looks good!

**Pull request merged**
