### PR TITLE
ISIS Application Docs style overhaul

### PR DESCRIPTION
**Pull request by jrcain-usgs**
## Description

Updates the ISIS Application docs pages to modern styling, including required header and footer, as well as styling reflecting USWDS guidance.

## Related Issue

#5619 

## How Has This Been Validated?

Docs have been built and visited locally.  In particular, the docs Homepage, TOCs, and random Application docs pages have been visited.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Documentation change (update to the documentation; no code change)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Infrastructure change (changes to things like CI or the build system that do not impact users)

## Checklist:

- [x] I have read and agree to abide by the [Code of Conduct](https://github.com/USGS-Astrogeology/ISIS3/blob/dev/Code-Of-Conduct.md)
- [x] I have read the [**CONTRIBUTING**](https://github.com/USGS-Astrogeology/ISIS3/blob/dev/CONTRIBUTING.md) document.
- [x] My change requires a change to the documentation and I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] I have added myself to the [.zenodo.json](https://github.com/USGS-Astrogeology/ISIS3/blob/dev/.zenodo.json) document.
- [ ] I have added my user impacting change to the [CHANGELOG.md](https://github.com/USGS-Astrogeology/ISIS3/blob/dev/CHANGELOG.md) document. 

## Licensing
This project is mostly composed of free and unencumbered software released into the public domain, and we are unlikely to accept contributions that are not also released into the public domain. Somewhere near the top of each file should have these words:

> This work is free and unencumbered software released into the public domain. In jurisdictions that recognize copyright laws, the author or authors of this software dedicate any and all copyright interest in the software to the public domain.

- [x] I dedicate any and all copyright interest in this software to the public domain. I make this dedication for the benefit of the public at large and to the detriment of my heirs and successors. I intend this dedication to be an overt act of relinquishment in perpetuity of all present and future rights to this software under copyright law.

### CODE REVIEW

**Comment by amystamile-usgs** [comment]
It doesn't seem super clear that you can click the parameters to expand them. Would it be possible to add the down arrowhead simpler to the up arrowhead when it's expanded?

Screenshot 2024-09-30 at 9 12 40 AM
Screenshot 2024-09-30 at 9 12 57 AM

**Comment by jrcain-usgs** [comment]
Hmm, what browser are you using?  There is a down arrow that's supposed to be there, it shows up in my testing so far.

Line 34 of ISISApplicationDocStyle.css is meant to put it there:
```
    /* Change Expansion symbols */
    .acc-flex-head[aria-expanded="false"], .acc-flex-head[aria-expanded="false"]:hover {
      background-image: url(../../../../assets/img/usa-icons/expand_more.svg);
    }
```
I wonder if your browser doesn't recognize the [aria-expanded="false"] css condition for some reason?

**Comment by jrcain-usgs** [comment]
Is there a down arrow on the government "Here's how you know" banner at the top?

**Comment by amystamile-usgs** [comment]
> Is there a down arrow on the government "Here's how you know" banner at the top?

No, that is missing as well for me.

**Comment by amystamile-usgs** [comment]
I checked my console and I am getting a CORs error for that particular svg. I am using Google Chrome.

Screenshot 2024-09-30 at 1 57 00 PM

**Comment by amystamile-usgs** [comment]
I do see the arrows on firefox for the parameters but not on the banner.

Screenshot 2024-09-30 at 2 02 32 PM

This may not be an issue once it is deployed in aws.

**Comment by jrcain-usgs** [comment]
I can't reproduce, all icons show up on Chrome and Firefox for me.  Did you try your browser's hard reload (Cmd + Shift + R, I think)?  I wonder if it cached a gov-banner from a different site where it's positioned slightly different?  Really weird the inconsistency though, only up arrows work in chrome, down arrows in parameters but not banner in Firefox.

Are you building the docs differently than me?  From `~/ISIS3/build` I do:
```
ninja docs -j7
cd docs #(or cd docs/8.3.0)
http-server
```

**Comment by amystamile-usgs** [comment]
> I can't reproduce, all icons show up on Chrome and Firefox for me. Did you try your browser's hard reload (Cmd + Shift + R, I think)? I wonder if it cached a gov-banner from a different site where it's positioned slightly different? Really weird the inconsistency though, only up arrows work in chrome, down arrows in parameters but not banner in Firefox.
> 
> Are you building the docs differently than me? From `~/ISIS3/build` I do:
> 
> ```
> ninja docs -j7
> cd docs #(or cd docs/8.3.0)
> http-server
> ```

That was my issue. I was just opening the index.html into a browser.

**Review by amystamile-usgs — APPROVED** [review]

**Pull request merged**
