### PR TITLE
Fix: translate 2nd coord of ROI to (X4, Y4), not (X2, Y2), as expected by hyb2onccal

### PR DESCRIPTION
**Pull request by foobarbecue**
A small update to make hyb2onccal work after recent changes in the Hayabusa2 FITS header format.

## Description
I helped with a recent update to the .trn file in which we assumed that ROI_URX and ROI_URY should be translated to SelectedImageAreaX2 and SelectedImageAreaY2, but it's clear from https://github.com/USGS-Astrogeology/ISIS3/blob/53af27e53c06fb38d7cadcfc1b5754c1be3baf45/isis/src/hayabusa2/apps/hyb2onccal/main.cpp#L134 that X4 and Y4 are expected.

## Related Issue
https://github.com/USGS-Astrogeology/ISIS3/issues/3698
https://github.com/USGS-Astrogeology/ISIS3/pull/3813

## How Has This Been Tested?

Tried on 4.1.0 RC

```
(isis4) $ hyb2onccal from=hyb2_onc_20180801_163925_tvf_l2a.cub to=hyb2_onc_20180801_163925_tvf_l2a.cal.cub
bias: 289.9

dark current: 0.0293015
Group = RadiometricCalibration
  SoftwareName        = hyb2onccal
  SoftwareVersion     = 1.0
  ProcessDate         = 2020-04-05T17:11:22
  CalibrationFile     = $hayabusa2/calibration/onc/hyb2oncCalibration0001.trn
  FlatFieldFile       = $hayabusa2/calibration/flatfield/flat_v.cub
  CompressionFactor   = 16
  Bias_Bn             = (289.9, -1.5847, 0.01211)
  Bias                = 289.9 <DN>
  CalibrationUnits    = IOF
  RadianceStandard    = 1.0
  RadianceScaleFactor = 1.0
  SolarDistance       = 1.0 <AU>
  SolarFlux           = 1880.5
  IOFFactor           = 1.0
  Units               = DN
End_Group
```

## Types of changes

- [ x ] Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [x] I have read and agree to abide by the [Code of Conduct](https://usgs-astrogeology.github.io/code/)
- [x] I have read the [**CONTRIBUTING**](https://github.com/USGS-Astrogeology/ISIS3/blob/dev/CONTRIBUTING.md) document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

## Licensing
This project is mostly composed of free and unencumbered software released into the public domain, and we are unlikely to accept contributions that are not also released into the public domain. Somewhere near the top of each file should have these words:

> This work is free and unencumbered software released into the public domain. In jurisdictions that recognize copyright laws, the author or authors of this software dedicate any and all copyright interest in the software to the public domain.

- [x] I dedicate any and all copyright interest in this software to the public domain. I make this dedication for the benefit of the public at large and to the detriment of my heirs and successors. I intend this dedication to be an overt act of relinquishment in perpetuity of all present and future rights to this software under copyright law.

### CODE REVIEW

**Comment by foobarbecue** [comment]
Hm, I don't know why this is failing tests. I don't think I have Jenkins access to go look.

**Comment by jlaura** [comment]
@foobarbecue We'll take a look at this today. This could be a known Jenkins failure. We're working on our CI as well!

**Comment by jlaura** [comment]
[Review #3827](https://trello.com/c/DIicCOCc/210-review-3827)

**Review by krlberry — APPROVED** [review]
:+1: This looks good and works as expected!

The test failure is real, but happened because this fix slightly changes the ISIS cube label generated for the ingestion test by adding the `SelectedImageAreaY4` and `X4` keywords. I will update the test data to expect the updated cube label format.

**Comment by jessemapel** [comment]
Ci always comes back as failing right now because the Mac builds aren't running and cleaning up correctly yet.

**Comment by jessemapel** [comment]
I forgot to mention this, but right now the CI is running internally at the ASC, so only ASC devs can access it. We're working on a login solution for non ASC contributors right now. In the mean-time we'll let any external contributors know if they had any CI failures on their PRs.

**Pull request merged**
