### PR TITLE
The cneteditor app has been modified to display & edit point coordinates and a priori sigmas in both lat/lon/radius and XYZ format

### PR DESCRIPTION
**Pull request by kledmundson**
## Description
Cneteditor has been modified to allow the display and edit of 3D point coordinates and their associated a priori sigmas in either Lat/Lon/Radius or XYZ format. Additionally, new filters have been implemented for XYZ coordinates and sigmas. This addition is particularly useful for the photogrammetric control of small and/or irregularly shaped bodies in XYZ coordinates. When bundle adjusting in XYZ it is necessary to set a priori 3D point coordinate uncertainties in that format. This work was originally implemented at the U. of Arizona to support the OSIRIS-REx mission. Note that these modifications apply as well to the control net editor view in the IPCE application.

## Related Issue
https://github.com/DOI-USGS/ISIS3/issues/5421

## How Has This Been Validated?

Validation has been primarily via manual testing of cneteditor. Additionally, edited control networks have been tested in jigsaw to confirm that a priori coordinate sigmas are handled properly when bundle adjusting in either lat/lon/radius or XYZ format. 
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Documentation change (update to the documentation; no code change)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Infrastructure change (changes to things like CI or the build system that do not impact users)

## Checklist:

- [X] I have read and agree to abide by the [Code of Conduct](https://github.com/USGS-Astrogeology/ISIS3/blob/dev/Code-Of-Conduct.md)
- [X] I have read the [**CONTRIBUTING**](https://github.com/USGS-Astrogeology/ISIS3/blob/dev/CONTRIBUTING.md) document.
- [X] My change requires a change to the documentation and I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [X] I have added myself to the [.zenodo.json](https://github.com/USGS-Astrogeology/ISIS3/blob/dev/.zenodo.json) document.
- [X] I have added my user impacting change to the [CHANGELOG.md](https://github.com/USGS-Astrogeology/ISIS3/blob/dev/CHANGELOG.md) document. 

## Licensing
This project is mostly composed of free and unencumbered software released into the public domain, and we are unlikely to accept contributions that are not also released into the public domain. Somewhere near the top of each file should have these words:

> This work is free and unencumbered software released into the public domain. In jurisdictions that recognize copyright laws, the author or authors of this software dedicate any and all copyright interest in the software to the public domain.

- [X] I dedicate any and all copyright interest in this software to the public domain. I make this dedication for the benefit of the public at large and to the detriment of my heirs and successors. I intend this dedication to be an overt act of relinquishment in perpetuity of all present and future rights to this software under copyright law.

### CODE REVIEW

**Comment by Kelvinrr** [comment]
Can you add visualizations on how to use the new features, will make local testing easier.

**Comment by kledmundson** [comment]
Kelvin,

Just to be clear, do you mean add images to the PR, to the cneteditor
documentation (or both)?

Thanks.

**Comment by Kelvinrr** [comment]
Just the PR, was trying to test locally and couldn't figure out how to switch between XYZ and lat/lon/rad. If we add that kind of very specific docs to the app docs, we will have to do it for every feature in the app and I dont think we want to do that right now.

**Comment by kledmundson** [comment]
image

After you import a control net, you should see two icons (buttons) at the right of the menubar. When the net is opened it defaults to the Lat/Lon/Radius view and the corresponding menu button (LLR) should indicate that. Clicking the  XYZ button next to it should toggle the display to XYZ and change the column headers accordingly. And you can go back and forth between the two.

Additionally, if you create a new filter when in XYZ mode, you'll see that the coordinate and sigma filters listed are in XYZ as well.

image

**Comment by amystamile-usgs** [comment]
@kledmundson This PR also has merge conflicts. Will test PR once conflicts are fixed. Thanks!

**Comment by kledmundson** [comment]
okeydoke, thanks for that

**Comment by amystamile-usgs** [comment]
Tests are passing. @Kelvinrr this is good for a rereview.

**Review by Kelvinrr — APPROVED** [review]
Apologies for the delay Ken, as you know it's been kinda hectic from a support standpoint lately so I appreciate ya'lls patience. 

I think this is good to go.

**Comment by kledmundson** [comment]
Not a problem at all, I really appreciate you having a look and getting it
in.

**Pull request merged**
