### PR TITLE
Fixes Jenkins errors: Revert "updated with new isd format"

### PR DESCRIPTION
**Pull request by krlberry**
Reverts USGS-Astrogeology/ISIS3#3839

This is causing some failures on Jenkins (most of the test failures we are seeing across systems.) Basically, ISIS was partially updated to use the new unified ISD format ("ale") but not completely, since the new ISD format wasn't completely ready. Reverting this PR should cause these tests to start passing again: 

module tests: 
	1326 - mex_module_test_hrsc (Failed)
	1462 - newhorizons_module_test_newhorizons (Failed)

app tests:
	404 - ckwriter_app_test_messenger (Failed)
	906 - spkwriter_app_test_messenger (Failed)
	1315 - mdisedrinfo_app_test_kernelchk (Failed)
	1325 - hrsc2isis_app_test_srcImage (Failed)
	1545 - voycal_app_test_linear (Failed)
	1546 - voycal_app_test_nonlinear (Failed)

### CODE REVIEW

**Comment by jessemapel** [comment]
Is this going to cause failures with ALE 0.8?

**Comment by krlberry** [comment]
> Is this going to cause failures with ALE 0.8?

I can build and test this locally. I hand-made many of these changes earlier (before Kelvin pointed out this PR) and it started working, but I didn't fully test reverting this PR.

**Comment by jessemapel** [comment]
> > Is this going to cause failures with ALE 0.8?
> 
> I can build and test this locally. I hand-made many of these changes earlier (before Kelvin pointed out this PR) and it started working, but I didn't fully test reverting this PR.

I'm concerned about accidentally pulling in ALE 0.8 when creating the environment because of the >=0.7.1

**Comment by krlberry** [comment]
Oh yeah, you're right, it won't work with ALE 0.8 unless I keep the changes for the header file location (and maybe there will be more failures beyond the initial `cmake` step.)

**Comment by krlberry** [comment]
The previously failing tests pass locally using the changes in this PR, including using ale 0.8. Letting full tests run overnight.

**Comment by krlberry** [comment]
Results from running full tests: still a few test failures (no overlaps with previous Jenkins failures) but upon examination of failing tests, they appear to require only "test data" updates, not code changes, so this PR is ready for review. (Primarily updating PVL.DIFF files and increasing tolerances for campt output that has changed due to different spice.)

For reference, these are the tests that are failing still with this PR, but I can fix by updating test data:
        1215 - kaguyami2isis_app_test_level2b2 (Failed)
        1326 - hrsc2isis_app_test_srcImage (Failed)
        1327 - mex_module_test_hrsc (Failed)

Also, something really strange happened with my unit tests, so I didn't get a complete local unit test run. (About 25% of the unit tests failed due to comparing, for example, classA.output with classB.truth. I'm not sure how this occurred, and it's persisting this morning.)

**Review by jessemapel — APPROVED** [review]

**Comment by jessemapel** [comment]
UnitTest errors are strange. If they occur post merge on Jenkins we can look into it.

**Review by scsides — APPROVED** [review]

**Pull request merged**
