### PR TITLE
Adds a draft .zenodo file to get authors names

### PR DESCRIPTION
**Pull request by jlaura**
Adds a .zenodo.json file.
## Description

This addition is in order to get a listing of the authors in some defined order. This is just a draft because I am honestly not sure how best to order these. What I have done (that I do not like):

- List the project lead
- List the USGS folks by number of commits (I'm lazy and pulled this from git)
- List everyone else by number of commits on git
- List anyone not on GitHub but who made the Authors.rst list as generated by @AndrewAnnex 

## Related Issue

#3810 

## Motivation and Context

We need to have an accurate author ordering for citations.

## How Has This Been Tested?

It honestly hasn't and I am not sure how best to test this with Zenodo. The JSON is valid and I see that Zenodo has `sandbox.zenodo.org`, but I am not sure how to use the sandbox for testing.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Documentation change (update to the documentation; no code change)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] I have read and agree to abide by the [Code of Conduct](https://usgs-astrogeology.github.io/code/)
- [x] I have read the [**CONTRIBUTING**](https://github.com/USGS-Astrogeology/ISIS3/blob/dev/CONTRIBUTING.md) document.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

## Licensing
This project is mostly composed of free and unencumbered software released into the public domain, and we are unlikely to accept contributions that are not also released into the public domain. Somewhere near the top of each file should have these words:

> This work is free and unencumbered software released into the public domain. In jurisdictions that recognize copyright laws, the author or authors of this software dedicate any and all copyright interest in the software to the public domain.

- [ ] I dedicate any and all copyright interest in this software to the public domain. I make this dedication for the benefit of the public at large and to the detriment of my heirs and successors. I intend this dedication to be an overt act of relinquishment in perpetuity of all present and future rights to this software under copyright law.

### CODE REVIEW

**Comment by rbeyer** [comment]
So this `.zenodo.json` file is going to be manually managed, or do you have a script that does the deed based on the `AUTHORS` file, and the rules you described above?  If so, then authors would just have to worry about the `AUTHORS` file, and only those who are involved in release engineering have to deal with the .zenodo.json file.  Then the `.zenodo.json` file is a compiled thing based on info in AUTHORS and GitHub stats, which would free us from having to content track two different files that track the same info.

Of course, the thing that occurred to me before was that the .zenodo.json file allows for 'affiliation' and 'orcid' fields, so maybe the `.zenodo.json` file should be the canonical source of "author" information and maybe we create the human-readable `AUTHORS` file from it?  And then I realized I was in a loop, and ran away from the topic screaming.  Seems like we should do one or the other, but I honestly don't know which.

Did you ever find a way to test this .zenodo.json file?  When I looked into this, they didn't appear to have a linter or any reasonable way to test the contents of the .zenodo.json without cutting a GitHub release and just seeing what happens.

**Comment by jlaura** [comment]
@rbeyer I definitely punted with the update both approach because I also am not sure which is 'of record'. I think the .zenodo.json file should be, but it is so alpha that I'm not brave enough to assert that.

I did not see any method for linting these. I saw mention of the sandbox URL in an issue on the zenodo GitHub, but the documentation for doing this is rough. I initially thought this was going to have to be 100% scripted through their REST API, but it looks like zenodo will magically parse this file....maybe? I am not super confident in this hence the first paragraph above.

So my 1/2 way solution for now is to do both and then, if zenodo looks like it is working, fully automate that (maybe with a GitHub action on a PR assuming we can get a post merge action to alter a file in the repo; this seems insanely dangerous for a code file by the way?) and then go from there. 🤷‍♂️

**Review by rbeyer — APPROVED** [review]

**Comment by jessemapel** [comment]
I am in favor of just keeping one thing around. It would be easier to keep the zenodo file around and then generate the AUTHORS file from it. It would be straight forward to have CMAKE run a small Python script to do that and then install it wherever we want in the distribution.

I think we're going to have to hand-maintain the zenodo file because it contains things like affiliation and ORCID that are not available programmatically.

For order, I do not like number of commits for two reasons:

1. It's a bogus metric that doesn't mean anything. It also biases towards git commits over SVN commits because of how the two tools differ.
1. The order of the file will change. If we're hand maintaining the file, then keeping the order of the file fixed would be greatly preferable. Having to re-order the file every time we pull a new release would suck.

I would rather the order be project lead first and then everyone else alphabetically.

**Comment by jlaura** [comment]
I'm all for lead and then alphabetical. I think this is on the TC agenda today, so if that sounds good for everyone I will get the list alphabetized. I can have this PR updated with a script to generate the authors.txt by the end of the week.

**Comment by jessemapel** [comment]
@jlaura Where is this at? Generating a script for this/working on the authors/zenodo management is a good candidate for the process work this week.

**Comment by jlaura** [comment]
I have not made it to do the generation, so if someone wants to pick that up, that would be ideal

**Comment by jessemapel** [comment]
I am going to merge this PR and open an issue on the repo to improve the zenodo and authors file management.

**Pull request merged**
