### PR TITLE
ISIS Docs build fix for incorrect path and -WEBHELP issues

### LINKED ISSUE #4510: Build Problems with ISIS Docs and -WEBHELP Usage
**ISIS version(s) affected**: 5.0+ (Perhaps others)

**Description**  
Several problems were discovered when building ISIS documentation. Note that my development environment is as follows:

```
MacBook Pro (15 inch, 2017)
MacOSX 10.15.3
Xcode 11.3.1

> g++ -v
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/4.2.1
Apple clang version 11.0.0 (clang-1100.0.33.17)
Target: x86_64-apple-darwin19.3.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

Python 3.6.7 (via Miniconda)
conda 4.9.2
```

### Build Fails on Programmer/Developer Documentation
First, when building the docs (using `ninja docs -j7` as per [instructions](https://github.com/USGS-Astrogeology/ISIS3/wiki/Developing-ISIS3-with-cmake#building-isis3-documentation)), it issues an error during the generation of the Programmer and Developer documentation. The error generated is show in the following docs build sequence:

```
warning: Tag 'MSCGEN_PATH' at line 2148 of file '/Users/kbecker/ISIS/Isis4Dev/Repo/ISIS3/build/docBuild/src/docsys/Object/build/Programmer_temp.conf' has become obsolete.
         To avoid this warning please remove this line from your configuration file or upgrade it using "doxygen -u"
warning: argument 'a4wide' for option PAPER_TYPE is not a valid enum value
Using the default: a4!
sh: dot: command not found
sh: dot: command not found
```
Essentially, many, many lines of the dot command missing error occurs here and I assume none of the programmer documentation is successfully created.

It looks like the dot program is part of the [graphviz](https://anaconda.org/anaconda/graphviz) package. 

### -WEBHELP Usage
Then, when attempting to use –web or –webhelp, the following error is thrown:

```
# In the ISIS installation shell
msi2isis -web
The file /Users/kbecker/miniconda3/envs/isis5eros/doc/Application/presentation/Tabbed/msi2isis/msi2isis.html does not exist.
**PROGRAMMER ERROR** Executing command [open $ISISROOT/doc/Application/presentation/Tabbed/msi2isis/msi2isis.html] failed with return status [256].


# In the build environment
msi2isis -web
The file /Users/kbecker/ISIS/Isis4Dev/Repo/ISIS3/build/doc/Application/presentation/Tabbed/msi2isis/msi2isis.html does not exist.
**PROGRAMMER ERROR** Executing command [open $ISISROOT/doc/Application/presentation/Tabbed/msi2isis/msi2isis.html] failed with return status [256].
```
This is due to an incorrect path hardcoded in [UserInterface.cpp](https://github.com/USGS-Astrogeology/ISIS3/blob/29b517e68fc04d695a1085a3cf1f6e8d2797763c/isis/src/base/objs/UserInterface/UserInterface.cpp#L683).

**How to reproduce**  

Here are the [commands](https://github.com/USGS-Astrogeology/ISIS3/wiki/Developing-ISIS3-with-cmake#getting-started-with-github) I used for the build:

```
cd ISIS/Isis4Dev/Repo/ISIS3
conda env create -n isis5eros -f environment.yml
conda activate isis5eros
mkdir build install
cd build
cmake -DisisData=/opt/isis4/data -DisisTestData=/opt/isis4/testData -DJPK2KFLAG=OFF -DCMAKE_BUILD_TYPE=RELEASE -GNinja  ../isis
export ISISROOT=$PWD
export ISISDATA=/opt/isis4/data
ninja install
ninja docs -j7
```
I am surprised there is no ISIS initialization in there somewhere.

Also, the ./install directory is not used. The `ninja install` command installs ISIS in $CONDA_PREFIX.

To reproduce the -WEBHELP error:
```
algebra -web
```

**Possible Solution**  

I have a PR coming to fix the single line in [UserInterface](https://github.com/USGS-Astrogeology/ISIS3/blob/29b517e68fc04d695a1085a3cf1f6e8d2797763c/isis/src/base/objs/UserInterface/UserInterface.cpp#L683) to correct the path. I also added the Graphviz package to both environment YAML files.

**Additional context**  

There is a $CONDA_PREFIX/doc directory that contains other package documentation. However, ISIS documentation is in $CONDA_PREFIX/docs. Seems pretty confusing/inconsistent.

Why not put ISIS document in $CONDA_PREFIX/doc/isis which would also be $ISISROOT/doc/isis/docs in this context.

### PR DESCRIPTION
**Pull request by KrisBecker**
When Building ISIS documentation, the dot command that builds graphics for Programmer and Developer documentation is not found. 

Also, applications built in this environment cannot get web documentation due to a path error.

## Description
$ISISROOT/doc/ path specification is invalid in UserInterface. An "s" was added to "doc".

Also, the Graphviz package was added to the environment files to provide the `dot` command for Doxygen builds.

## Related Issue

This PR fixes #4510

## Motivation and Context

Corrects localized access to ISIS documentation

## How Has This Been Tested?

The fix was tested in my build environment.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation change (update to the documentation; no code change)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] I have read and agree to abide by the [Code of Conduct](https://github.com/USGS-Astrogeology/ISIS3/blob/dev/Code-Of-Conduct.md)
- [x] I have read the [**CONTRIBUTING**](https://github.com/USGS-Astrogeology/ISIS3/blob/dev/CONTRIBUTING.md) document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [ ] I have added myself to the [.zenodo.json](https://github.com/USGS-Astrogeology/ISIS3/blob/dev/.zenodo.json) document.
- [ ] I have added any user impacting changes to the [CHANGELOG.md](https://github.com/USGS-Astrogeology/ISIS3/blob/dev/CHANGELOG.md) document.

## Licensing
This project is mostly composed of free and unencumbered software released into the public domain, and we are unlikely to accept contributions that are not also released into the public domain. Somewhere near the top of each file should have these words:

> This work is free and unencumbered software released into the public domain. In jurisdictions that recognize copyright laws, the author or authors of this software dedicate any and all copyright interest in the software to the public domain.

- [x] I dedicate any and all copyright interest in this software to the public domain. I make this dedication for the benefit of the public at large and to the detriment of my heirs and successors. I intend this dedication to be an overt act of relinquishment in perpetuity of all present and future rights to this software under copyright law.

### CODE REVIEW

**Review by krlberry — APPROVED** [review]
This all looks good to me!

**Comment by KrisBecker** [comment]
Ok, so I am not sure what happens now.

Will someone just merge this into dev?

I see the Jenkins test for this PR is failing but the 10 errors in the build seem completely unrelated to this PR. All other PRs I checked have the same errors, so no PR Jenkins tests are passing right now? Are passing Jenkins tests a pre-requisite for a merge?

**Comment by jessemapel** [comment]
We are having a few issues with our Jenkins builds at the moment that we're working to fix. This is also missing a CHANGELOG entry, but we'll add that to the PRs for the bug fix release we're prepping right now.

**Comment by KrisBecker** [comment]
Ok, thanks. Hope you can indulge a few more questions.

I notice that my PR has every PR I used to update/sync my Astrogeology/ISIS3 fork. What is the recommended way to only see the relevant commits and and not the sync PRs on my fork? For example, I have another PR coming that depends on this PR. I want now to sync my GitHub ISIS3 fork and branch off that state of dev. What is the best way to do this and prevent the sync PR from following me around? 

Thanks for the CHANGELOG update. So every PR requires a change log entry?

Finally, I don't appear to have merge permissions (I am not asking for it either). Following the process as outlined in the contributing [docs](https://github.com/USGS-Astrogeology/ISIS3/blob/dev/CONTRIBUTING.md) and [howtos](https://github.com/USGS-Astrogeology/ISIS3/wiki/How-to-Start-Contributing), it seems after the PR is submitted and reviewed, it is not clear to me how to get the PR merged and closed out. Is there someone at Astro who is the designated external Committer for a particular time frame or is the decision to merge mostly adhoc once comments/reviews cease? Is there a customary review/comment period? I am trying to understand what are the steps and average expected time frame to complete a PR.

Thanks in advance...

**Comment by jessemapel** [comment]
The best way to sync your changes with upstream is to rebase them using `git rebase`.

Generally once a PR is approved it can be merged as long as it's been open for more than a handful of hours. The submitter can merge their own PR after it has been approved by another, the reviewer may or may-not merge it. Generally if a reviewer thinks a PR looks good, but wants another person to review they should indicate that in their review.

**Comment by KrisBecker** [comment]
Ok, I finally found something that works. Here are the instructions I used to fix the `commits ahead` state created by using PRs to sync my ISIS3 fork:

```
git checkout dev
git remote add upstream https://github.com/USGS-Astrogeology/ISIS3.git
git fetch upstream
git rebase upstream/dev
git push -f origin dev
```

The `-f` is important to force the update.

See also this [post](https://stackoverflow.com/questions/7244321/how-do-i-update-or-sync-a-forked-repository-on-github/31836086#31836086).

**Pull request merged**
