### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by PROMETHUES**
Line 58: Specify the python version for isis 7.1.0

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Documentation change (update to the documentation; no code change)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Infrastructure change (changes to things like CI or the build system that do not impact users)

## Checklist:

- [ ] I have read and agree to abide by the [Code of Conduct](https://github.com/USGS-Astrogeology/ISIS3/blob/dev/Code-Of-Conduct.md)
- [ ] I have read the [**CONTRIBUTING**](https://github.com/USGS-Astrogeology/ISIS3/blob/dev/CONTRIBUTING.md) document.
- [x] My change requires a change to the documentation and I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] I have added myself to the [.zenodo.json](https://github.com/USGS-Astrogeology/ISIS3/blob/dev/.zenodo.json) document.
- [ ] I have added any user impacting changes to the [CHANGELOG.md](https://github.com/USGS-Astrogeology/ISIS3/blob/dev/CHANGELOG.md) document.

## Licensing
This project is mostly composed of free and unencumbered software released into the public domain, and we are unlikely to accept contributions that are not also released into the public domain. Somewhere near the top of each file should have these words:

> This work is free and unencumbered software released into the public domain. In jurisdictions that recognize copyright laws, the author or authors of this software dedicate any and all copyright interest in the software to the public domain.

- [x] I dedicate any and all copyright interest in this software to the public domain. I make this dedication for the benefit of the public at large and to the detriment of my heirs and successors. I intend this dedication to be an overt act of relinquishment in perpetuity of all present and future rights to this software under copyright law.

### CODE REVIEW

**Comment by PROMETHUES** [comment]
Previously, the corresponding Python version of ISIS was specified, but not in this dev branch. To make it easier to use, Line 58 has been modified。

**Comment by jlaura** [comment]
@PROMETHUES  It should not be required to specify the python version like this any longer. This is why that section in the README was updated. Are you submitting this PR because you are seeing different behavior on your system?

**Comment by PROMETHUES** [comment]
Yes, I tried to install ISIS 7.1.0 with no specific python version first, and it is not working. It always showing some conflict in the environment (Anaconda installed in WSL2). Then I tried create another Anaconda environment with Python 3.6 and 3.9.15, and the ISIS 7.1.0 was successfully installed. I think it is better to specify a python version that you are developing with.

**Comment by jlaura** [comment]
@PROMETHUES I am glad that you got ISIS installed.

Two issues still exist: (1) WSL is not explicitly supported, so an update to support WSL that is not tested across the supported platforms can not be merged and (2) Python 3.6 release was six (yes six!) years ago and EOL was 1+ years ago. Probably better to get an issue open (sorry if I missed one!) where you report the install error when not specifying a python version.

**Pull request closed without merging**
