### PR TITLE
Create IssueLifecycle.md

### PR DESCRIPTION
**Pull request by jlaura**
## Description
This is a documentation change to adopt an issue policy in this repository.

## Related Issue
#3951 

## Motivation and Context
- We believe that the project has too many issues that have little to no chance of being addressed for a number of reasons (e.g., the problem no longer exists in the current version, the user that reported is no longer working on a project the issue is impacting due to issue age, the enhancement is now out of scope due to time and project evolution, etc.). We assert that none of these are necessarily inherently negative.
- We do not have a policy document at this point. Having a policy document would be a nice thing to have
- We do not need to be prescriptive of the process, we need a set of guidelines on what/when/how things are pruned

## How Has This Been Tested?
N/A - This is a documentation change

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Documentation change (update to the documentation; no code change)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] I have read and agree to abide by the [Code of Conduct](https://usgs-astrogeology.github.io/code/)
- [x] I have read the [**CONTRIBUTING**](https://github.com/USGS-Astrogeology/ISIS3/blob/dev/CONTRIBUTING.md) document.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [ ] I have added myself to the [AUTHORS.rst](https://github.com/USGS-Astrogeology/ISIS3/blob/dev/AUTHORS.rst) document.

## Licensing
This project is mostly composed of free and unencumbered software released into the public domain, and we are unlikely to accept contributions that are not also released into the public domain. Somewhere near the top of each file should have these words:

> This work is free and unencumbered software released into the public domain. In jurisdictions that recognize copyright laws, the author or authors of this software dedicate any and all copyright interest in the software to the public domain.

- [x] I dedicate any and all copyright interest in this software to the public domain. I make this dedication for the benefit of the public at large and to the detriment of my heirs and successors. I intend this dedication to be an overt act of relinquishment in perpetuity of all present and future rights to this software under copyright law.

### CODE REVIEW

**Comment by rbeyer** [comment]
This looks good to me.  I might suggest adding some additional information to your proposed "automatically_closed" tag, maybe "automatically closed: inactivity" or something similar. (just in case there is any other future reason to automatically close something).

**Review by rbeyer — APPROVED** [review]

**Comment by jlaura** [comment]
@rbeyer Agreed! In fact, I started to implement that change. Then I thought: 

It should have both the `inactive` and `automatically_closed` tags because it picks up the first one at 6 months and the second at the year mark. The downside to this is that we have to search using two tags, but I think I'm okay with that. Thoughts?

**Comment by rbeyer** [comment]
I'm not as savvy as I should be with tags.  Is the "inactive" tag automatically applied / removed based on Issue activity?  If so, that sounds fine to me.

**Comment by jlaura** [comment]
I'll have to get the bot to remove it when activity occurs, but yes. We will auto apply it at 6 months, and then stack it with the auto close tag at 12 months. The bot will have to iterate over all the issues tagged with inactive and check for activity with some regular cadence. I might even be able to have GitHub ping the bot when activity occurs (like we get a ping for PRs on our CI). 

I'm still waiting to hear back on a question on the GitHub API for some of the implementation specifics on how to efficiently use the REST API.

**Review by rfergason — APPROVED** [review]
Overall, I think this policy is needed, provides warning and notification to all watchers on the project when an issue has been inactive and is being prepared for automatic closure, and provides a means to clean up the backlog of issues in a manner that allows old, but still relevant, issues to remain open.

I think this policy is particularly effective for managing new issues that are posted, and cleaning out those posts as they become inactive.

"As a one time cleanup all issues >= 11 months in age will be closed with a message to the original poster (sent via GitHub) to reopen the issue, add a reaction emoji, or comment to have the issue go back to being live. In cases of a bug, we will ask the re-opener to confirm they can reproduce on the current ISIS version."
The above action sounds good, but I am concerned that it will not be effective in practice. I think this workload could be high for some of our more active and long-time users and question whether a month (at the end of the fiscal year, no less) is a reasonable amount of time to sort through old issues.  I recommend that we allow more than 1 month for this one-time clean-up.

**Comment by jlaura** [comment]
@rfergason From a quick scan of the repo, we only have 3 issues (one of which is mine) that fall into the 11 month window. Therefore, I am not sure that extending that window is going to have the desired effect. 

In terms of work load, I would also suggest that no work needs to be done at this time by a submitter if they are busy. A submitter can re-open or re-create an issue at their convenience if said issue is of importance to them.

**Comment by rfergason** [comment]
@jlaura  There are currently 508 issues open.  So, for the one-time clean up event, I would expect there to be something like 450+ issues that could qualify as inactive and be automatically closed (i.e., 450 emails sent to the contact information available).  This understanding is inconsistent with your statement that there are "3 issues (one of which is mine) that fall into the 11 month window."  What am I missing?

If my understanding above is incorrect, then the following comment is moot.  Regarding "In terms of work load, I would also suggest that no work needs to be done at this time by a submitter if they are busy. A submitter can re-open or re-create an issue at their convenience if said issue is of importance to them."  If 450 emails are sent, then some of our long-time users could see a very large number of emails.  Just deleting them them with no other action will take time.  And many of our users are very conscientious and will want to do more than simply delete them.  However, a notice (maybe on AstroDiscuss?) to users so they can anticipate this clean-up event and understand that they can always re-open a ticket may go a long way.

**Comment by jlaura** [comment]
Ahh - I misread your comment. You are right, that some users that are watching issues could get a large number of emails telling them that the issue has been automatically closed. I thought you meant the issues at the 11 month mark (of which, we only have 3).

My opinion is that at some point we need to close those issues which meet our close criteria. Whether they are done now or in a few months, it will never be a good time for everyone. 

I do think that an added AstroDiscuss post is a great idea. I can get one cooked to let folks know when this is going to happen. Then they can set up a filter for GitHub, stop watching the project for a day (in their GitHub settings), or simply be ready for the deluge of potential emails.

**Comment by lwellerastro** [comment]
> Whether they are done now or in a few months, it will never be a good time for everyone.

The end of the fiscal year is definitely a worse time than any other.  I have commented on any of this because I simply do not have the time or energy to get involved.  Any sort of evaluation or clean up of posts that involve in-house users is best done at any time other than the days of the fiscal year.

**Comment by jlaura** [comment]
@lwellerastro Thanks for the input! This does not involve any synchronous input from contributors, so I think we are all good. The messages will be sent such that anyone can look at or reopen stuff at their convenience. Also, I'm with you. The end of the fiscal is crazy for all of us!

For everyone doing a review, where is the best place for us to put the bot code? I have [a gist here](https://gist.github.com/jlaura/a0c2a456bb2f2d9c31f178ae287fe870) of a working prototype and we can get this running off our Jenkins CI pretty easily. Not sure if this code (plus tests) should sit in this repo? Putting it into our other bot repo isn't good form I think because that is a private, internal only repo (and I would like all contributors to also be able to modify the bot). 

To see the bot in action, checkout the linked issue above (#3974).

**Comment by jessemapel** [comment]
@jlaura maybe an isis_bots repo? Really make our search history look bad.

**Review by jessemapel — APPROVED** [review]

**Comment by jlaura** [comment]
The gitbot to manage issues is [available for review here](https://github.com/USGS-Astrogeology/gitissuebot). If anyone wants to play around with this:

1. Update the config with the repo name, repo owner (e.g., organization or you), and [API Key](https://docs.github.com/en/github/authenticating-to-github/creating-a-personal-access-token).
1. Create your env, setup.py develop, etc.
1. Fire up a notebook, or an interactive python session (I still need to make a main inside a Docker container) and run:
1. Set an env variable to you config file, e.g., `GITISSUEBOT_CONFIG=path_to/config.yml`

```
from gitissuebot.main import get_issues, find_and_update_inactive_issues

issues = get_issues()
find_and_update_inactive_issues(issues)
```

You will likely want to aim this at a new repo and then go in an modify main.py to set the ages (in days) to something else. Maybe even seconds (lines 221, 225, 227).

Also, see the linked issue in this PR for how the bot's posts will look.

**Comment by rbeyer** [comment]
The 11-month message needs to say "I will close" in its last para.  

I'm too lazy to eval the code, but I assume that the bot ignores its own messages and emoji when doing an activity test?

**Comment by jlaura** [comment]
:+1:

It does ignore itself and any of it's own labels/emojis. At least in the tests that I ran and then the canned responses/tests that I wrote. I am confident an edge case exists in there and am also confident that we can fix it when we find it.

**Comment by jessemapel** [comment]
This PR looks complete and discussion has shifted over to the bot that will help with implementation so I'm merging this.

**Pull request merged**
