### PR TITLE
Updated cisscal to match IDL version 3.9

### LINKED ISSUE #3351: CISSCAL update to 3.91
**Description**  

The released `cisscal` IDL routine was updated to 3.91 (current ISIS3 cisscal uses 3.8), with 3.9 having a significant upgrade in the calibration compared to 3.8 (at least it sounds like it).

A nice changelog and links to cisscal and docs can be found here, maintained by the Rings/Moons node:
https://pds-rings.seti.org/cassini/iss/index.html

### PR DESCRIPTION
**Pull request by kaitlyndlee**
## Description

Updated cisscal to match IDL version 3.9. In addition to code changes, calibration files needed to also be updated. 

## Related Issue

Fixes https://github.com/USGS-Astrogeology/ISIS3/issues/3351

## Motivation and Context

Updates cisscal to match current IDL version.

## How Has This Been Tested?

Testing right now.
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Documentation change (update to the documentation; no code change)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] I have read and agree to abide by the [Code of Conduct](https://usgs-astrogeology.github.io/code/)
- [x] I have read the [**CONTRIBUTING**](https://github.com/USGS-Astrogeology/ISIS3/blob/dev/CONTRIBUTING.md) document.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

## Licensing
This project is mostly composed of free and unencumbered software released into the public domain, and we are unlikely to accept contributions that are not also released into the public domain. Somewhere near the top of each file should have these words:

> This work is free and unencumbered software released into the public domain. In jurisdictions that recognize copyright laws, the author or authors of this software dedicate any and all copyright interest in the software to the public domain.

- [x] I dedicate any and all copyright interest in this software to the public domain. I make this dedication for the benefit of the public at large and to the detriment of my heirs and successors. I intend this dedication to be an overt act of relinquishment in perpetuity of all present and future rights to this software under copyright law.

### CODE REVIEW

**Comment by jessemapel** [comment]
@kaitlyndlee Do you want a review on this before or after it's tested?

**Comment by kaitlyndlee** [comment]
@jessemapel Whenever you are free to do a review I am fine with.

**Review by jessemapel — COMMENTED** [review]
This all looks good to me, I'm curious why it's producing different results.

**Review by jessemapel — COMMENTED** [review]
The version # on line 135 of the main needs to be updated to 3.9.1

See #3375

**Review by jessemapel — APPROVED** [review]

**Comment by jessemapel** [comment]
@kaitlyndlee Go ahead and merge this when you are ready to check in the test data.

**Pull request merged**
