### PR TITLE
Removed Z from end of StartTime on re-ingested cubes

### PR DESCRIPTION
**Pull request by SgStapleton**
Would this potentially make recent changes to iTime obsolete as any ingestion program will need to handle this individually anyway?

And should I create a redmine ticket for this one? (I wasn't sure what to reference in the history comment without a ticket number...)

### CODE REVIEW

**Comment by celbal** [comment]
Your changes do make the iTime changes obsolete. Kristin and I have talked about this and we think that this is the correct place to deal with the trailing Z. Could you please delete the changes to iTime and test this again?

**Comment by SgStapleton** [comment]
Done. Everything appears to be passing.

**Comment by krlberry** [comment]
@SgStapleton :+1: Looks good!

**Comment by krlberry** [comment]
@SgStapleton One more question -- is there any test data that will need to be updated for this once the CaSSIS branch is merged into trunk, and if so, where is the updated test data.

**Comment by jcwbacker** [comment]
@kberryUSGS @SgStapleton I think we should put the data in /work/projects/tgo/testData (for app/cat tests) and when it's merged into dev, the reviewer check the data in from there.

**Comment by SgStapleton** [comment]
Just removed the history comment from the reverted changes to iTime (as this never went into dev anyway).

**Comment by SgStapleton** [comment]
Other than iTime truthdata, this should only really be affecting our catTests that are testing the re-ingestion of exported .xmls. I have updated the catTest I created. I will let Adam know to update his.

**Pull request merged**
