### PR TITLE
Remove unused Parabola class

### PR DESCRIPTION
**Pull request by krlberry**
While looking for good classes for test refactoring, I noticed that the Parabola class is no longer used. It is removed in this PR.

### CODE REVIEW

**Comment by krlberry** [comment]
Fixes #575

**Comment by kaitlyndlee** [comment]
Should this also go into dev instead?

**Comment by krlberry** [comment]
Yes, good point @kdl222 !

**Comment by krlberry** [comment]
@kdl222 See PR #586

**Pull request closed without merging**
