### PR TITLE
Install guide changes to release

### LINKED ISSUE #3148: Installation instructions for the /base data is incorrect
**ISIS version(s) affected**: All

**Description**  
If you follow the instructions on our installation page you make a royal mess on your computer and ISIS does not run.  

**How to reproduce**  
Go to https://isis.astrogeology.usgs.gov/documents/InstallGuide/index.html
Follow the instructions methodically and exactly
You will get /data folders being installed in random locations on your computer.  

**Possible Solution**  
Simplest solution takes two steps
(1) make where you cd to explicitly clear.  Right now it seems to suggest that you should 
cd $ISIS3DATA
but it is ambiguous if you need to do this if all you want to download is the /base or mission specific data.  I suggest you make it clear that step one is to cd $ISIS3DATA.
(2) correct the rsync commands so they work if you are in $ISIS3DATA.  Specifically, get rid of the /data at the end of every command.  You just need a .

**Additional context**  
This mistake has cost my student and I literally all of November, December, January, and February.  I could not figure out why ISIS would not run on his machine.  He would bring it in and there would be data folders scattered all over the place because he ran the rsync from wherever he happened to be. I know, we no longer support users who are not technically savvy so the real problem is that I am too stupid to use ISIS.

### PR DESCRIPTION
**Pull request by jessemapel**
Ported install guide to release for web doc updates.

## Description

I checked-out the dev version of the install guide file so that we can build and push the release docs.

## Related Issue

Fixes #3148 

## Motivation and Context

The this concludes the work from #3170 

## How Has This Been Tested?

Documentation changes were tested by building the documentation.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Documentation change (update to the documentation; no code change)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] I have read and agree to abide by the [Code of Conduct](https://usgs-astrogeology.github.io/code/)
- [x] I have read the [**CONTRIBUTING**](https://github.com/USGS-Astrogeology/ISIS3/blob/dev/CONTRIBUTING.md) document.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

## Licensing
This project is mostly composed of free and unencumbered software released into the public domain, and we are unlikely to accept contributions that are not also released into the public domain. Somewhere near the top of each file should have these words:

> This work is free and unencumbered software released into the public domain. In jurisdictions that recognize copyright laws, the author or authors of this software dedicate any and all copyright interest in the software to the public domain.

- [x] I dedicate any and all copyright interest in this software to the public domain. I make this dedication for the benefit of the public at large and to the detriment of my heirs and successors. I intend this dedication to be an overt act of relinquishment in perpetuity of all present and future rights to this software under copyright law.

### CODE REVIEW

**Comment by jessemapel** [comment]
I'm not sure why github thinks it's pulling in 82269cf. There's no changes coming in from it.

**Review by krlberry — APPROVED** [review]
:+1: This all looks good to me.

**Comment by krlberry** [comment]
@jessemapel Can I merge this?

**Comment by jessemapel** [comment]
@kberryUSGS Yep, this is ready to go

**Pull request merged**
