### PR TITLE
Updated ISIS3 references to ISIS 

### PR DESCRIPTION
**Pull request by amystamile-usgs**
Remove references to ISIS3 and replace with references to ISIS 

## Description
Updated any references of ISIS3 to ISIS. I left any mention of ISIS3 in history comments and anything pertaining specifically to ISIS3 version.

## Motivation and Context
ISIS 3/4 Transition Cleanup FY21

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Documentation change (update to the documentation; no code change)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] I have read and agree to abide by the [Code of Conduct](https://github.com/USGS-Astrogeology/ISIS3/blob/dev/Code-Of-Conduct.md)
- [x] I have read the [**CONTRIBUTING**](https://github.com/USGS-Astrogeology/ISIS3/blob/dev/CONTRIBUTING.md) document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [x] I have added myself to the [.zenodo.json](https://github.com/USGS-Astrogeology/ISIS3/blob/dev/.zenodo.json) document.
- [x] I have added any user impacting changes to the [CHANGELOG.md](https://github.com/USGS-Astrogeology/ISIS3/blob/dev/CHANGELOG.md) document.

## Licensing
This project is mostly composed of free and unencumbered software released into the public domain, and we are unlikely to accept contributions that are not also released into the public domain. Somewhere near the top of each file should have these words:

> This work is free and unencumbered software released into the public domain. In jurisdictions that recognize copyright laws, the author or authors of this software dedicate any and all copyright interest in the software to the public domain.

- [x] I dedicate any and all copyright interest in this software to the public domain. I make this dedication for the benefit of the public at large and to the detriment of my heirs and successors. I intend this dedication to be an overt act of relinquishment in perpetuity of all present and future rights to this software under copyright law.

### CODE REVIEW

**Review by scsides — COMMENTED** [review]
Good catch on the "ISIS 3"s.

Do you want to handle the "Isis" and "isis" occurrences in this PR or would it be easier as a new PR?

**Comment by amystamile-usgs** [comment]
> Good catch on the "ISIS 3"s.
> 
> Do you want to handle the "Isis" and "isis" occurrences in this PR or would it be easier as a new PR?

I can do another sweep for Isis and isis and add it to this PR.

**Comment by amystamile-usgs** [comment]
@scsides I checked through again and did not find any additional Isis3 or isis3 references other than in file paths or in history comments. Are you referring to updating "Isis" and "isis" to "ISIS"?

**Comment by amystamile-usgs** [comment]
Updated "isis" and "Isis" to "ISIS". Ignored any disclaimers with "Isis" since these will be updated in another PR.

**Review by kaitlyndlee — DISMISSED** [review]

**Review by scsides — APPROVED** [review]

**Review by scsides — DISMISSED** [review]

**Review by scsides — APPROVED** [review]

**Pull request merged**
