### PR TITLE
Fixed ControlNet not handling ignoring measures correctly

### PR DESCRIPTION
**Pull request by jessemapel**
This fixes the errors in cnetwinnow. I also added the edge strength to the graphToString method in ControlNet because it's very helpful for debugging and ensuring the integrity of the graph.

### CODE REVIEW

**Review by krlberry — COMMENTED** [review]
This isn't part of your new changes, for line 677, shouldn't that (the edge strength ++)  be inside of the if(edgeAdded) ?

**Review by krlberry — APPROVED** [review]
:+1: This all looks good!

**Comment by jessemapel** [comment]
@kberryUSGS Increasing the edge strength should happen when adding a new edge and when the edge already exists.. So, it needs to stay outside of the if statement.

**Comment by krlberry** [comment]
@jessemapel Yep, you're right that's the whole point of incrementing the edge, isn't it? :) Must have had a brain-o.

**Pull request merged**
