### PR TITLE
Moved Cassini data into source

### PR DESCRIPTION
**Pull request by kaitlyndlee**
## Description

Moved translation, serial numbers, and templates into src code so that it is versioned. Updated ciss2isis and vims2isis to grab translation files from $ISISROOT.

## Related Issue

#3727 

## Motivation and Context

This change is a part of moving the isis3data area, some files going into the source code.

## How Has This Been Tested?

Reran all cassini tests and the ciss2isis tests fail because of the template files not being copied into the build dir. ckwriter_app_test_cassini and cassini_module_test_vims are failing because of MissionName2DataDir.trn not existing in the translations build dir yet.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation change (update to the documentation; no code change)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] I have read and agree to abide by the [Code of Conduct](https://usgs-astrogeology.github.io/code/)
- [x] I have read the [**CONTRIBUTING**](https://github.com/USGS-Astrogeology/ISIS3/blob/dev/CONTRIBUTING.md) document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

## Licensing
This project is mostly composed of free and unencumbered software released into the public domain, and we are unlikely to accept contributions that are not also released into the public domain. Somewhere near the top of each file should have these words:

> This work is free and unencumbered software released into the public domain. In jurisdictions that recognize copyright laws, the author or authors of this software dedicate any and all copyright interest in the software to the public domain.

- [x] I dedicate any and all copyright interest in this software to the public domain. I make this dedication for the benefit of the public at large and to the detriment of my heirs and successors. I intend this dedication to be an overt act of relinquishment in perpetuity of all present and future rights to this software under copyright law.

### CODE REVIEW

**Review by paarongiroux — APPROVED** [review]
Looks good

**Comment by kaitlyndlee** [comment]
Since the calibration .trn files weren't in the translation directory, I didn't move them over. I will update the PR with this.

**Comment by krlberry** [comment]
@kaitlyndlee I talked to @scsides and he actually said to not move the calibration translation files into the source. Reasoning: there is already a calibration data directory, so don't separate the calibration-related translation files specifically by moving them into revision control. We can talk about this more when you're in on Thursday, if you'd like.

**Review by krlberry — APPROVED** [review]
:+1: This all looks good to me!

**Comment by kaitlyndlee** [comment]
Okay to merge?

**Pull request merged**
