### PR TITLE
Adding ostruthdata for ProgramLauncher on Fedora28

### PR DESCRIPTION
**Pull request by SgStapleton**

### CODE REVIEW

**Comment by jlaura** [comment]
@SgStapleton @kdl222 @chrisryancombs  Are you seeing OS dependent issues with the CMake build and conda dependencies?

**Comment by SgStapleton** [comment]
This test in particular involves OS exit codes, so it has always needed ostruthdata for the different OS. Aside from the nan/-nan issue, we really haven't had much os-specific issues that hasn't been expected. At least not that I am aware of. @kdl222  and @chrisryancombs did a bit of work on the tests before I started on the project though, so it might be good to have their input.

**Comment by ihumphrey** [comment]
@SgStapleton This can be closed (w/out merging), right? (since #448 is merged into the `cmake` branch now)

**Comment by SgStapleton** [comment]
@ihumphrey-usgs Actually, https://github.com/USGS-Astrogeology/ISIS3/pull/448 contains the ostruthdata for a different system. I do still need to update this PR due to the changes in that one, though.

**Comment by SgStapleton** [comment]
This one was fixed in another PR (https://github.com/USGS-Astrogeology/ISIS3/pull/478)

**Pull request closed without merging**
