### PR TITLE
The explode application has been refactored to be callable and Makefile test converted to a gtest.

### PR DESCRIPTION
**Pull request by kledmundson**
## Description

The explode application has been refactored to be callable. The one existing Makefile test has been converted to a gtest utilizing the DefaultCube test fixture. The Makefile test has been removed.

## Related Issue

https://github.com/DOI-USGS/ISIS3/issues/5557
## How Has This Been Validated?

The one ISIS Makefile test has been replaced with the gtest ExplodeDefault.

Results of ctest suite...

ctest -R FunctionalTestExplodeDefault --output-on-failure
Test project /Users/kledmundson/ISISDev/explode/Jul192024/ISIS3/build
    Start 1444: DefaultCube.FunctionalTestExplodeDefault
1/1 Test #1444: DefaultCube.FunctionalTestExplodeDefault ...   Passed    2.57 sec

100% tests passed, 0 tests failed out of 1

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation change (update to the documentation; no code change)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [X] Infrastructure change (changes to things like CI or the build system that do not impact users)

## Checklist:

- [X] I have read and agree to abide by the [Code of Conduct](https://github.com/USGS-Astrogeology/ISIS3/blob/dev/Code-Of-Conduct.md)
- [X] I have read the [**CONTRIBUTING**](https://github.com/USGS-Astrogeology/ISIS3/blob/dev/CONTRIBUTING.md) document.
- [ ] My change requires a change to the documentation and I have updated the documentation accordingly.
- [X] I have added tests to cover my changes.
- [X] I have added myself to the [.zenodo.json](https://github.com/USGS-Astrogeology/ISIS3/blob/dev/.zenodo.json) document.
- [X] I have added my user impacting change to the [CHANGELOG.md](https://github.com/USGS-Astrogeology/ISIS3/blob/dev/CHANGELOG.md) document. 

## Licensing
This project is mostly composed of free and unencumbered software released into the public domain, and we are unlikely to accept contributions that are not also released into the public domain. Somewhere near the top of each file should have these words:

> This work is free and unencumbered software released into the public domain. In jurisdictions that recognize copyright laws, the author or authors of this software dedicate any and all copyright interest in the software to the public domain.

- [X] I dedicate any and all copyright interest in this software to the public domain. I make this dedication for the benefit of the public at large and to the detriment of my heirs and successors. I intend this dedication to be an overt act of relinquishment in perpetuity of all present and future rights to this software under copyright law.

### CODE REVIEW

**Review by acpaquette — CHANGES_REQUESTED** [review]
Looks like the main.cpp changes got missed and the old make test should be removed. Once that's in this can get a better review

**Comment by kledmundson** [comment]
Sorry, major mistake, hopefully addressed now.

**Review by acpaquette — COMMENTED** [review]
Overall looks good! Could we get a changelog entry for the conversion?

**Review by amystamile-usgs — DISMISSED** [review]

**Comment by Kelvinrr** [comment]
I think this needs approval from @acpaquette

**Review by acpaquette — DISMISSED** [review]

**Comment by acpaquette** [comment]
@kledmundson Change log now has merge conflicts after merging another refactor PR

**Review by acpaquette — APPROVED** [review]

**Pull request merged**
