### PR TITLE
Initial version bump action

### PR DESCRIPTION
**Pull request by AustinSanders**
Creates a bot to bump version on specified branch.  Currently set to fake "lts" branch.  Will need to be updated when LTS branches are released.

## Description
Bumps patch version specified in meta.yaml and cmakelists.txt.

I'm a noob at awk/sed, so there's probably a better way to hit this regex.  It was a difficult for me to balance generality and specificity.

## Related Issue
LTS Release + CI/CD work

## How Has This Been Validated?
Bot commit visible at https://github.com/AustinSanders/ISIS3/commit/29f55d1dd4a47333e230d140229a4ddf73f7e153

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation change (update to the documentation; no code change)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Infrastructure change (changes to things like CI or the build system that do not impact users)

## Checklist:

- [x] I have read and agree to abide by the [Code of Conduct](https://github.com/USGS-Astrogeology/ISIS3/blob/dev/Code-Of-Conduct.md)
- [x] I have read the [**CONTRIBUTING**](https://github.com/USGS-Astrogeology/ISIS3/blob/dev/CONTRIBUTING.md) document.
- [ ] My change requires a change to the documentation and I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] I have added myself to the [.zenodo.json](https://github.com/USGS-Astrogeology/ISIS3/blob/dev/.zenodo.json) document.
- [x] I have added any user impacting changes to the [CHANGELOG.md](https://github.com/USGS-Astrogeology/ISIS3/blob/dev/CHANGELOG.md) document.

## Licensing
This project is mostly composed of free and unencumbered software released into the public domain, and we are unlikely to accept contributions that are not also released into the public domain. Somewhere near the top of each file should have these words:

> This work is free and unencumbered software released into the public domain. In jurisdictions that recognize copyright laws, the author or authors of this software dedicate any and all copyright interest in the software to the public domain.

- [x] I dedicate any and all copyright interest in this software to the public domain. I make this dedication for the benefit of the public at large and to the detriment of my heirs and successors. I intend this dedication to be an overt act of relinquishment in perpetuity of all present and future rights to this software under copyright law.

### CODE REVIEW

**Comment by chkim-usgs** [comment]
Looks good, question though: do version updates to the `code.json` and `CHANGELOG.md` have different qualifications for them to occur? Or would these updates happen in a different step of the pipeline?

**Comment by AustinSanders** [comment]
> Looks good, question though: do version updates to the `code.json` and `CHANGELOG.md` have different qualifications for them to occur? Or would these updates happen in a different step of the pipeline?

I think I can add code.json here, but I think the changelog should be updated in a different job.  The idea is that this will be run when something is merged into the LTS branch, and the triggering commit will likely already include an updated changelog, so I'm viewing it as a separate step.

**Comment by amystamile-usgs** [comment]
@chkim-usgs Do you have time to review this? Not sure if this is waiting on another CI sprint or if it's okay to merge now.

**Comment by chkim-usgs** [comment]
@AustinSanders, I think it looks good, incrementing the patch version whenever the bot is triggered. Are there any other version updates that can affect this PR since it has been open? Only thing that comes to mind is the new isis_version.txt but that seems to be generated after.

**Comment by AustinSanders** [comment]
I don't think any of the changes that we've made will affect the way that this bot works.  This grabs the version number from meta.yml, increments, and overwrites the version number in meta.yml + cmakelists.txt

**Review by chkim-usgs — APPROVED** [review]

**Pull request merged**
